### ISSUE TITLE
Command not found only overwritten sometimes

### ISSUE THREAD

**Issue by crimsonknave** [errbotio/errbot#1000]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug

### I am running...

* Errbot version: 5.0.0
* OS version: Linux
* Python version: 3.5.3
* Using a virtual environment: yes

### Issue description

I'm attempting to override the default command not found behavior. It works... sometimes... Without changing any config I can start errbot multiple times and get the default and my behavior. It does not seem to be swapping on a given run.

### Steps to reproduce

* Define a new cnf entry using ```@cmdfilter(catch_unprocessed=True)```
* Start errbot
* Enter a non existent command (you will get the new or the old)
* Restart errbot
* Enter a non existent command (you will get the new or the old)
* Repeat about 4-5 times and you should have gotten both.

**Comment by crimsonknave** [comment]
This appears to be due to core.py pulling the first command filter with catch_unprocessed true and self.command_filters isn't in a consistent order run to run.

**Comment by gbin** [comment]
Can you try #1005 and tell me if it is ok like this ? You'll have to exclude the CommandNotFoundFilter plugin from the CORE_PLUGINS setting in config.py if you don't want both behavior to happen at the same time.

**Comment by crimsonknave** [comment]
@gbin For my specific purposes disabling the plugin is all I need. I just want to replace the default behavior. 

It would, however, be nice to have a blacklist setting instead of having to specifically list out all of the plugins I want. First, I've now got to figure out all the core plugins that exist and add them. Second, I'll never get any new core plugins unless I notice that they exist and then add them to the whitelist.
