### ISSUE TITLE
Make botplugin._recurse_check_plugin_configuration public again

### ISSUE THREAD

**Issue by sheluchin** [errbotio/errbot#1007]
### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.0.1

### Issue description

In https://github.com/errbotio/errbot/pull/991/ the `utils.recurse_check_structure` was moved to `botplugin._recurse_check_plugin_configuration`. This is a method that I was relying on in several of my plugins in order to allow for a list item in the project configuration ([example](https://github.com/netquity/err-github-merger/blob/75e92c3e71feac8429de15d3f711e619a67ce01f/merge.py#L78)). It's a useful method and I'd like to see it made public again.

**Comment by zoni** [comment]
I'm perfectly okay with making this public again, as `botplugin.recurse_check_structure`. I don't think we should move it back into `utils` since it's very botplugin specific and changed on a major version, but definitely agree it's useful to expose publicly.
