### ISSUE TITLE
Clash renames are non-deterministic

### ISSUE THREAD

**Issue by TimJones** [errbotio/errbot#1010]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [x] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.0.1
* OS version: Debian Jessie
* Python version: 3.4.2
* Using a virtual environment: Docker (https://hub.docker.com/r/rroemhild/errbot/)

### Issue description

I have a plugin with a `status` command defined. This of course clashes with the core `status` command. It is unknown until start-up if my `status` gets renamed to `myplugin-status` or the core to `health-status`.

### Steps to reproduce

Just create a 'helloworld' plugin but call the function `status`...

    $ errbot -T
    ...
    HelloWorld.status clashes with Health.status so it has been renamed hellowworld-status
    ...

Run it a few times and eventually it will respond differently

    $ errbot -T
    ...
    Health.status clashes with HelloWorld.status so it has been renamed health-status
    ...
    

### Additional info

Is there a way for my plugin to ensure it gets the preferred command name?
For now, I just use a different command name :)

**Comment by KimNorgaard** [comment]
The problem is that `find_roots` and `collect_roots` in `utils.py` use `set` and sets are unordered. They should probably use `OrderedDict`, a sorted, flattened list or maybe `OrderedSet` [link](http://code.activestate.com/recipes/576694/) to retain order.
