### ISSUE TITLE
Unknown preprocessing of text

### ISSUE THREAD

**Issue by meetmangukiya** [errbotio/errbot#1018]
`this is [some](markdown link)` is outputted as `this is some (markdown link)` in `testbot.pop_message()` which shows there is some preprocessing being done. There shouldn't be any pre-processing, or there should be an option to disable pre-processing at least

**Comment by meetmangukiya** [comment]
Escaping the square brackets does the job for the time being. `\[some\]`. Please fix this asap

**Comment by gbin** [comment]
The output of commands IS markdown and will be change d on every back end so testing should account for that. For example if your plugin was not escaping brackets and you wanted brackets you would never have caught it. If you want pure text always use triple backquotes.

**Comment by gbin** [comment]
Looking at the original issue you actually want a link, so on backends supporting them they'll show up as link.

**Comment by meetmangukiya** [comment]
hmm.. that means doesn't gitter backend doesn't support links

**Comment by meetmangukiya** [comment]
however, yeah enclosing in triple ticks sound better then escaping

**Comment by gbin** [comment]
It should otherwise it is a bug. Did you try on gitter?

**Comment by meetmangukiya** [comment]
no, but in config it is mentioned gitter, so testbot should account for that?

**Comment by meetmangukiya** [comment]
@gbin does the `TestBot` expose the processor, then I can use the processor and then assert again the output, so I don't have to do any manual processing to match the output?

**Comment by gbin** [comment]
For the gitter backend it uses the converter called errbot.rendering.md which transform the errbot extended markdown to the standard markdown. So links, tables, images etc should either work by being rendered by gitter in markdown or by being rendered by errbot if not cannot.

**Comment by meetmangukiya** [comment]
so errbot has its own flavor of markdown

**Comment by meetmangukiya** [comment]
I think for `TestBot` backend `errbot.rendering.text` is being used, right?
