### ISSUE TITLE
plugin wizard/scaffolder: Don't create an empty errbot section altogether if min and max versions are not specified

### ISSUE THREAD

**Issue by meetmangukiya** [errbotio/errbot#1024]
An example plug file:

```
[Core]
module = github
name = github

[Documentation]
description = GitHub utilities exposed through errbpt

[Python]
version = 3

[Errbot]

```

complete file https://github.com/coala/corobo/blob/21cbe0d84c17f3bb61772da100d4f19c572ed599/plugins/github.plug

**Comment by meetmangukiya** [comment]
@zoni do you think there is a way we can avoid the trailing blank new line? It seems like a `configparser`  thing. But it'd be nice if we can get around that :D

**Comment by zoni** [comment]
Unlikely. As you say, it's a configparser thing.

-- 
Nick Groenen
https://nick.groenen.me/
