### ISSUE TITLE
Github webhooks comment plugin

### ISSUE THREAD

**Issue by albruz** [errbotio/errbot#1035]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [x] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.0.1
* OS version: Mac OS X 10.12.4
* Python version: 3.6.1
* Using a virtual environment: no

### The problem ###

Hi everyone! I need your help!

I'm using slack and i created a slackapp that uses errbot.
I want to write a plugin that runs a command when the git webhook that I installed on slack write a comment on the channel where the bot lives.
I can't use the webhook feature of errbot and I tried with the callbacks but that didn't work..there a way for the bot to read it like the others comment? There is a workaround?

Thank You!

**Comment by zoni** [comment]
>  I can't use the webhook feature of errbot and I tried with the callbacks but that didn't work..there a way for the bot to read it like the others comment? There is a workaround?

The messages generated by that git webhook should trigger the `callback_message` handler so this should work. What have you tried exactly that didn't work?

**Comment by albruz** [comment]
Hi!
I've tried this:
`from errbot import BotPlugin

class PluginExample(BotPlugin):
    def callback_message(self, mess):
        if mess.body.find('commit') != -1:
            self.send(
                mess.frm,
                "somebody committed!",
            )`

**Comment by zoni** [comment]
It's quite possible those messages don't have regular text set, but rely on the "attachment" attributes slack webhooks offer. Try looking at (off the top of my head, excuse possible typos) `mess.extras['attachments']` for one of those messages.

It's possible it's in there somewhere.

**Comment by zoni** [comment]
Closing this issue due to age. Please let us know if you are still experiencing issues.
