### ISSUE TITLE
Plugin unable to read x node in precence stanzas (xmpp)

### ISSUE THREAD

**Issue by pirxthepilot** [errbotio/errbot#1038]
I'm trying to get my plugin to get this particular stanza from `callback_presence` but the Presence object does not seem to have it?

```
<x xmlns="http://jabber.org/protocol/muc#user">
    <item affiliation="owner" jid="user@server.tld/resource" role="moderator"/>
</x>
```

What's the best way to get this information? (the data inside <item> in particular)

**Comment by sijis** [comment]
I'm not sure its possible and I have no way to test this.

If you've found a workaround that would be great to share.

I'm going to close this for now, but please re-open if needed.
