### ISSUE TITLE
Cannot initialize webhook decorator with only raw=True parameter

### ISSUE THREAD

**Issue by sponsfreixes** [errbotio/errbot#1043]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.0.1
* OS version: macOS Sierra Version 10.12.5
* Python version: Python 3.6.1
* Using a virtual environment: yes

### Issue description

When setting a webhook as `@webhook(raw=True)` I notice that `*args` is passed to the webhook decorator as an empty tuple, which makes the following line fail with and IndexError exception (errbot/_init.py, L441): `if isinstance(args[0], str): # first param is uri_rule.`

This is the example on the documentarion: http://errbot.io/en/latest/user_guide/plugin_development/webhooks.html#the-raw-request

### Steps to reproduce

1. Create a webhook, defining only the raw argument: `@webhook(raw=True)`. 
2. Use the webhook. It will raise the IndexError exception described above.

**Comment by gbin** [comment]
Confirmed, I am working on it.
