### ISSUE TITLE
Create a setter for extras property

### ISSUE THREAD

**Issue by meetmangukiya** [errbotio/errbot#1045]
`errbot.backends.base.Message` doesn't have a `setter` for `extras` property which had caused this bug, well, technically because I made an assumption that the setter existed and reviewing didn't catch that either. 

The question would be do we want this setter? One can modify it, if it is initialised with one.

/cc @gbin @zoni

**Comment by gbin** [comment]
self._extras in message is already:
```
self._extras = extras or dict()
```
So you can modify it, no need for a setter.
