### ISSUE TITLE
Update flow docs to use literalinclude

### ISSUE THREAD

**Issue by sijis** [errbotio/errbot#1046]
### I am...

* [x] Here about something else

### Issue description
I think it may be simpler to manage the code examples in the documentation if they are complete code files and just literalinclude them into the docs.

**Comment by zoni** [comment]
I raised some concerns over in https://github.com/errbotio/errbot/pull/923#pullrequestreview-47909041 that directly apply to this (I suggest keeping discussion in there instead of here to avoid having it scattered across two issues).

**Comment by sijis** [comment]
I closed #923 and that applies here too.
