### ISSUE TITLE
Is there functionality to hold a conversation?

### ISSUE THREAD

**Issue by jkornblum** [errbotio/errbot#1048]
### I am...

* [X] Suggesting a new feature?
* [X] Requesting help with running my bot

### I am running...

* Errbot version: 5.0.1
* OS version: Windows 7
* Python version: 3.5.2
* Using a virtual environment: yes/no (yes, conda environment)

Hello, I've used errbot for a bit to implement a number of bot commands for Slack and it works great.
However, is there functionality or best practice to hold a conversation?
When I've worked with other bot frameworks (like BotKit) there is functionality to hold a conversation and respond directly to the user or channel (through promises or callbacks in JavaScript).

Is there similar functionality in Errbot? I see Flows but this doesn't seem to be exactly that.
(I.e. it's not a chain of errbot commands, just looking for text input)

I want to achieve functionality similar to the following
User: !sendmsg
Bot: To whom should I send the message?
User: john.doe
Bot: What message?
User: Hello
Bot: Okay, I've sent "Hello" to john.doe

**Comment by gbin** [comment]
The Flows are that: check this example: https://github.com/errbotio/err-guess-a-number
It starts a conversation then asks the user to guess a number

**Comment by jkornblum** [comment]
Okay wow, looking at the guess-a-number example makes it very clear how works. I guess the documentation was a little more confusing to me (but makes sense now after that example)
Awesome
Thanks!
