### ISSUE TITLE
Access Control Doesn't Work for Slack Backend

### ISSUE THREAD

**Issue by liangyungong** [errbotio/errbot#1050]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [x] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.0.1
* OS version: Ubuntu 14.04.5 LTS
* Python version: 3.4.3
* Using a virtual environment: yes

### Issue description

Permission control doesn't work. Non-admin user can use command with "admin_only=True".

config.py:
`**ACCESS_CONTROLS** = { '*': {'allowusers': BOT_ADMINS}, }
`
code:
`    @arg_botcmd('first_name', type=str)
    @arg_botcmd('--last-name', dest='last_name', type=str)
    @arg_botcmd('--favorite', dest='favorite_number', type=int, default=42, admin_only=True, unpack_args=False)
    def test(self, message, args):
        return testplugin.testplugin()
`

**Comment by gbin** [comment]
Which backend do you use ?

**Comment by liangyungong** [comment]
slack.

**Comment by liangyungong** [comment]
Found the problem.

`ACLs` must be enabled in`CORE_PLUGINS`. Closing this issue.
