### ISSUE TITLE
A simple return from the web hook raises an error

### ISSUE THREAD

**Issue by ab9-er** [errbotio/errbot#1058]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [x] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.0.1
* OS version: MacOS 10.12.5
* Python version: 3.6
* Using a virtual environment: yes

### Issue description

To avoid the timeout from Slack, whenever my web hook receives a hit, it does a `return "OK"` to the user and continues asynchronously completing the job in the background. This return causes an error as described here,

https://github.com/errbotio/errbot/blob/e4b872084a3a617257e1952a8a756439d0de2838/errbot/backends/slack.py#L127

### Steps to reproduce

Spin up a web hook and try doing a return with some string.

**Comment by sijis** [comment]
I cannot reproduce this, however, please reopen if the issue is still present.

Please include a code sample of the webhook command used.
