### ISSUE TITLE
Add link attribute to Message

### ISSUE THREAD

**Issue by meetmangukiya** [errbotio/errbot#1061]
A link attribute that'll contain the link to that particular message.

**Comment by meetmangukiya** [comment]
Backends that support:
1. Slack
2. Gitter
Backends that don't support:
1. IRC
2. Text
3. Telegram(?)

**Comment by SirEdvin** [comment]
Slack backend already has link to message in `msg.extras['url']. I guess, gitter has something like this too.

**Comment by andrewthetechie** [comment]
It doesn't look like Telegram supports a link. Of all the backend in errbot core, only slack does and it already supports this feature.

For gitter, you should open a feature request on https://github.com/errbotio/err-backend-gitter

#closeit
