### ISSUE TITLE
Backticks for code formatting is broken. 

### ISSUE THREAD

**Issue by 7--** [errbotio/errbot#1066]
I entered this into a slack message and it didn't format the text at all
...Code:
"`Configuration paymentConfig =
    paymentApp.configurationService.getConfiguration("DEV");
            System.out.println("HELLO:"+paymentConfig.getString("hello"));`

Can..."

I see github notices the backticks but slack doesnt

In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version:
* OS version: Win 7
* Python version: 
* Using a virtual environment: yes/no

### Issue description

Please describe your bug/feature/problem here.
The more information you can provide, the better.

### Steps to reproduce

In case of a bug, please describe the steps we need to take in order to reproduce your issue.
If you cannot easily reproduce the issue please let us know and provide as much information as you can which might help us pinpoint the problem.

### Additional info

If you have any more information, please specify it here.

**Comment by gbin** [comment]
Can you try triple backtick, new line, code, new line triple backtick new line ?

**Comment by r3m0t** [comment]
I use triple backtick, no newline, code, and no closing triple backtick.

**Comment by gbin** [comment]
So simple backticks are line based IIRC the closing backtick needs to be on the same line.

tripple backticks needs to be formatted like this:

``````
```
def code:
something
```
``````
