### ISSUE TITLE
Move plugin list to somewhere to allow sorting them with github stats

### ISSUE THREAD

**Issue by k1-hedayati** [errbotio/errbot#1067]
### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* Here about something else

### Issue description
Just searching "test" in wiki page results in 31 plugins, there are 500 plugins in that page, and many of them have just a few commits from some years ago, searching through this list is very time consuming, if there was mechanism to sort them using their stats it would be much easier to discover good and active plugins, I guess there should be a project to get list of github repos and sort them by stats and other metrics.

**Comment by gbin** [comment]
This is a good idea, I gonna try to see if I cannot sort this list by github stats (stars, date of last change, activity ...)  instead of just names.

**Comment by gbin** [comment]
So I made up a dummy "activity" metric based on stars, watchers, forks and last update. And I sorted the page by that, it is way better ! https://github.com/errbotio/errbot/wiki

**Comment by k1-hedayati** [comment]
@gbin great, is it gonna be updated automatically?

**Comment by k1-hedayati** [comment]
@gbin oh, it seems there is some issue with links, all of them point to same location
