### ISSUE TITLE
cnf_filter doesn't work well for custom bot prefixes

### ISSUE THREAD

**Issue by meetmangukiya** [errbotio/errbot#1070]
### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### Steps to reproduce

1. Set `BOT_PREFIX='test '`
2. Run
3. `test upt`
4. Command "test" not found

**Comment by zoni** [comment]
I think you meant "cmd_filter" instead of "cnf_filter", correct?

What do you expect to see instead of `Command "test" not found`? (because `test upt` isn't a default errbot command..?)

**Comment by meetmangukiya** [comment]
> I think you meant "cmd_filter" instead of "cnf_filter", correct?

Isn't Command not found message given by `cnf_filter`?

> What do you expect to see instead of Command "test" not found? (because test upt isn't a default errbot command..?)

I expect to see `Command "upt" not found` since `test ` is the bot prefix

**Comment by zoni** [comment]
> Isn't Command not found message given by `cnf_filter`?

Yes, you're absolutely correct. Though `cnf_filter` is itself [a cmdfilter](https://github.com/errbotio/errbot/blob/e9f4ea8a8d79f8d5c40f53100a97c79e4f4b0a2b/errbot/core_plugins/cnf_filter.py#L5).

> I expect to see `Command "upt" not found` since `test ` is the bot prefix

Gotcha, I fully understand the issue now.

**Comment by gbin** [comment]
Damned, I failed hard reviewing this cnf_filter PR, it was full of bugs.
