### ISSUE TITLE
"!plugin config" doesn't work in Text mode

### ISSUE THREAD

**Issue by natewang341124** [errbotio/errbot#1072]
### I am...

* [x] Reporting a bug

### I am running...

* Errbot version: 5.1.0
* OS version:
* Python version: 3.4
* Using a virtual environment: yes

### Issue description

When the bot is activated in text mode, the !plugin config stops working, and giving this message:
"This command requires bot-admin privileges", when I'm in admin(red color) mode.

**Comment by Djiit** [comment]
Hi there,

Could you confirm your username (with and without a '@') is listed in `BOT_ADMINS` in your configuration file (usually `config.py`) ?

**Comment by sijis** [comment]
This is no longer relevant in the latest version. I believe it was fixed in a later 5.x release.
```
[@luser ➡ @errbot] >>> !plugin config Webserver {'HOST': '0.0.0.0', 'PORT': 3141, 'SSL': {'certificate': '', 'enabled': False, 'host': '0.0.0.0', 'key': '', 'port': 3142}}
This command requires bot-admin privileges

[@luser ➡ @errbot] >>> !asadmin
You are now an admin: @sijis.

[@sijis ➡ @errbot] >>> !plugin config Webserver {'HOST': '0.0.0.0', 'PORT': 3141, 'SSL': {'certificate': '', 'enabled': False, 'host': '0.0.0.0', 'key': '', 'port': 3142}}
Plugin configuration done.
```
