### ISSUE TITLE
send_stream_request generate an exception for channel identifier

### ISSUE THREAD

**Issue by roidayan** [errbotio/errbot#1079]
bot version: 5.1.0

send_stream_request works fine if I use msg.frm in Botcmd callback.
it also works when I specify a user like this:
to = self.build_identifier('@roid')

but it raise an exception when using a channel like this:
to = self.build_identifier('#test')

the code:
self.send_stream_request(to, open(filename, 'rb'),
                                          name=name,
                                          stream_type='image/png')

the exception:

  File "/root/venv2/lib/python3.6/site-packages/errbot/botplugin.py", line 625, in send_stream_request
    return self._bot.send_stream_request(user, fsource, name, size, stream_type)
  File "/root/venv2/lib/python3.6/site-packages/errbot/backends/slack.py", line 697, in send_stream_request
    identifier.channelname, size, stream_type))
AttributeError: 'SlackRoom' object has no attribute 'channelname'

**Comment by roidayan** [comment]
seems SlackPerson has channelname attribute but for SlackRoom its name

**Comment by roidayan** [comment]
a quick fix is I added channelname to SlackRoom.

the issue itself can come only from 2 places which both are log print.

slack.py
line 691
            log.exception("Upload of {0} to {1} failed.".format(stream.name, stream.identifier.channelname))

line 697
        log.debug("Requesting upload of {0} to {1} (size hint: {2}, stream type: {3})".format(name,
                  identifier.channelname, size, stream_type))

not sure the best fix for here so I didn't do a pull request.
can do what i did to add channelname attribute or have a conditional here if to use name if the identifier is SlackRoom or name otherwise (because rest of the options inherit from SlackPerson which has channelname attribute)

**Comment by gbin** [comment]
It makes sense Thx!
