### ISSUE TITLE
Text backend : you need to press enter twice

### ISSUE THREAD

**Issue by patrickpxp** [errbotio/errbot#1080]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [x] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.1.0
* OS version: macOS 10.12.6
* Python version: 3.6.0
* Using a virtual environment: **yes**/no

### Issue description

Need to press enter twice to validate a command in text mode. Nothing very urgent but could be more detailed in the documentation

### Steps to reproduce

[@pato ➡ @errbot] >>> !whoami
[@pato ➡ @errbot] [␍] 
┏━━━━━━━━━━┳━━━━━━━┓
┃ key      ┃ value ┃
┡━━━━━━━━━━╇━━━━━━━┩
│ person   │ pato  │
├──────────┼───────┤
│ nick     │ None  │
├──────────┼───────┤
│ fullname │ None  │
├──────────┼───────┤
│ client   │ None  │
└──────────┴───────┘
• string representation is '@pato'
• class is 'TextPerson'

[@pato ➡ @errbot] >>> 

### Additional info

If you have any more information, please specify it here.

**Comment by gbin** [comment]
So this is coming from users trying to test the configuration command for errbot. For example copy pasting multiline configs.

It is possible to do that easily under various backends (Slack and al.) but it was impossible to test on text.

I added the kludge to ask for an extra empty C/R at the end so you can do that. If you have a better idea or a PR to do that more conveniently, I am really open.

**Comment by patrickpxp** [comment]
it think the implementation is great :-)
just that a small note regarding entering twice for newbies
