### ISSUE TITLE
err-cracksh plugin not listed in registry

### ISSUE THREAD

**Issue by frozenfoxx** [errbotio/errbot#1082]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [X] Here about something else

### I am running...

* Errbot version: 5.0.1
* OS version: raspbian jessie
* Python version: 3.4.2
* Using a virtual environment: no

### Issue description

A plugin developed and tagged for Errbot [err-cracksh](https://github.com/frozenfoxx/err-cracksh) is not listed in the Wiki.

### Steps to reproduce

Looked in the wiki at the plugin list, did not see err-cracksh.

### Additional info

I looked for another way to submit either changes to the wiki list or to submit new plugins to be included and did not see a method documented. The primary locations I expected to find documentation were on the wiki page itself or in the Plugin Development section of the Errbot documentation. If I've missed the documentation for the proper channel to resolve this please let me know and close this ticket. Thank you very much.

**Comment by gbin** [comment]
Thanks for your contribution!

I currently update this page manually, generating it from the script included with errbot (looking for plugins directly in github). I am doing a round just for cracksh now ;)

**Comment by gbin** [comment]
https://github.com/errbotio/errbot/wiki#84---cracksh :)

**Comment by frozenfoxx** [comment]
Thank you so much!
