### ISSUE TITLE
Hipchat backend frequently hits the rate-limit

### ISSUE THREAD

**Issue by cryptk** [errbotio/errbot#1092]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.1.2
* OS version: CentOS 7.3
* Python version: 3.6
* Using a virtual environment: yes

### Issue description

When using the HipChat backend, errbot quickly hits the API rate limit when joining a room

### Steps to reproduce

Configure errbot to connect to a room in HipChat

### Additional info

here are some logs indicative of the "flood" of API requests causing errbot to be rate-limited and eventually disconnect.  They aren't running quite exactly back to back... but definitely more than frequently enough to hit the hipchat API limit (which a quick google indicates might be as low as 100/5min

```2017-08-28 17:34:48,587 DEBUG    urllib3.connectionpool    https://api.hipchat.com:443 "GET /v2/user?include-guests=true HTTP/1.1" 200 3472
2017-08-28 17:34:48,740 DEBUG    urllib3.connectionpool    https://api.hipchat.com:443 "GET /v2/user?include-guests=true&start-index=100&max-results=100 HTTP/1.1" 200 3810
2017-08-28 17:34:48,881 DEBUG    urllib3.connectionpool    https://api.hipchat.com:443 "GET /v2/user?include-guests=true&start-index=200&max-results=100 HTTP/1.1" 200 1021
2017-08-28 17:34:48,985 DEBUG    urllib3.connectionpool    https://api.hipchat.com:443 "GET /v2/user/USER_NUMBER HTTP/1.1" 200 485```

It looks like errbot might not be properly caching perhaps?

**Comment by totally** [comment]
Seeing this as well.  

We have more than 1024 rooms and 1024 users, so we might be blowing the `lru_cache(1024)`, eg:

https://github.com/errbotio/errbot/blob/8caf0db889442524ebf7ac56ba1c103c717a4334/errbot/backends/hipchat.py#L457

One more thing is that the bot doesn't process commands while processing these fetches.  eg. `!help` does not return.  This happens both before and during RateLimit backoff.

**Comment by woz5999** [comment]
+1
i had to switch to the XMPP backend as well

**Comment by vipradwivedi** [comment]
+1
Currently max-results=100 for user and room api of hypchat, this can be easily increased to 1000

**Comment by hari95kishore** [comment]
+1

**Comment by andrewthetechie** [comment]
https://www.theverge.com/2018/7/26/17619482/slack-hipchat-acquisition-stride-atlassian-partnership-microsoft-teams-competition

Hipchat is going away here very soon.

#closeit

**Comment by sijis** [comment]
Based on that article, there is no need to do this as the service is being shutdown in about 5 weeks.

Atlassian is providing instructions (https://www.atlassian.com/partnerships/slack/migration) how migrate to Slack.

We do have a functional Slack backend to support those organizations migrating.
