### ISSUE TITLE
Help with runing my bot 

### ISSUE THREAD

**Issue by NishaMurarka** [errbotio/errbot#1095]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [0] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version:  latest
* OS version: Ubuntu 14.04
* Python version: python 3.3+
* Using a virtual environment: I am using ubuntu 14.04 installed in a virtual box

### Issue description
My errbot was sucessfully installed. It got initalized also when I tried to open it by issuing the command errbot I am getting this error -
02:11:39 INFO     errbot.specific_plugin_ma storage search paths {'/usr/local/lib/python3.4/dist-packages/errbot/storage'}
02:11:39 INFO     errbot.specific_plugin_ma Found those plugings available:
02:11:39 INFO     errbot.specific_plugin_ma 	     Shelf  (/usr/local/lib/python3.4/dist-packages/errbot/storage/shelf.py)
02:11:39 INFO     errbot.specific_plugin_ma 	    Memory  (/usr/local/lib/python3.4/dist-packages/errbot/storage/memory.py)
02:11:39 INFO     errbot.bootstrap          Found Storage plugin: 'Shelf'
Description: This is the storage plugin for the traditional shelf store for errbot.
02:11:39 DEBUG    errbot.specific_plugin_ma Refilter the plugins...
02:11:39 WARNING  yapsy                     Plugin candidate '/usr/local/lib/python3.4/dist-packages/errbot/storage/memory.plug'  rejected by strategy 'SpecificBackendLocator'
02:11:39 DEBUG    errbot.specific_plugin_ma Load the one remaining...
02:11:39 DEBUG    errbot.specific_plugin_ma Class to load ShelfStoragePlugin
02:11:39 DEBUG    errbot.storage            Opening storage 'repomgr'
02:11:39 DEBUG    errbot.storage.shelf      Open shelf storage /home/nisha/errbot/data/repomgr.db
02:11:39 DEBUG    errbot.storage            Opening storage 'core'
02:11:39 DEBUG    errbot.storage.shelf      Open shelf storage /home/nisha/errbot/data/core.db
02:11:39 INFO     errbot.specific_plugin_ma backends search paths {'/usr/local/lib/python3.4/dist-packages/errbot/backends'}
02:11:39 INFO     errbot.specific_plugin_ma Found those plugings available:
02:11:39 INFO     errbot.specific_plugin_ma 	     Slack  (/usr/local/lib/python3.4/dist-packages/errbot/backends/slack.py)
02:11:39 INFO     errbot.specific_plugin_ma 	      Null  (/usr/local/lib/python3.4/dist-packages/errbot/backends/null.py)
02:11:39 INFO     errbot.specific_plugin_ma 	      Text  (/usr/local/lib/python3.4/dist-packages/errbot/backends/text.py)
02:11:39 INFO     errbot.specific_plugin_ma 	      XMPP  (/usr/local/lib/python3.4/dist-packages/errbot/backends/xmpp.py)
02:11:39 INFO     errbot.specific_plugin_ma 	       IRC  (/usr/local/lib/python3.4/dist-packages/errbot/backends/irc.py)
02:11:39 INFO     errbot.specific_plugin_ma 	   Graphic  (/usr/local/lib/python3.4/dist-packages/errbot/backends/graphic.py)
02:11:39 INFO     errbot.specific_plugin_ma 	  Telegram  (/usr/local/lib/python3.4/dist-packages/errbot/backends/telegram_messenger.py)
02:11:39 INFO     errbot.specific_plugin_ma 	      Test  (/usr/local/lib/python3.4/dist-packages/errbot/backends/test.py)
02:11:39 INFO     errbot.specific_plugin_ma 	   Hipchat  (/usr/local/lib/python3.4/dist-packages/errbot/backends/hipchat.py)
02:11:39 INFO     errbot.bootstrap          Found Backend plugin: 'Text'
						Description: This is the text backend for Err.
02:11:39 DEBUG    errbot.specific_plugin_ma Refilter the plugins...
02:11:39 WARNING  yapsy                     Plugin candidate '/usr/local/lib/python3.4/dist-packages/errbot/backends/slack.plug'  rejected by strategy 'SpecificBackendLocator'
02:11:39 WARNING  yapsy                     Plugin candidate '/usr/local/lib/python3.4/dist-packages/errbot/backends/null.plug'  rejected by strategy 'SpecificBackendLocator'
02:11:39 WARNING  yapsy                     Plugin candidate '/usr/local/lib/python3.4/dist-packages/errbot/backends/xmpp.plug'  rejected by strategy 'SpecificBackendLocator'
02:11:39 WARNING  yapsy                     Plugin candidate '/usr/local/lib/python3.4/dist-packages/errbot/backends/irc.plug'  rejected by strategy 'SpecificBackendLocator'
02:11:39 WARNING  yapsy                     Plugin candidate '/usr/local/lib/python3.4/dist-packages/errbot/backends/graphic.plug'  rejected by strategy 'SpecificBackendLocator'
02:11:39 WARNING  yapsy                     Plugin candidate '/usr/local/lib/python3.4/dist-packages/errbot/backends/telegram_messenger.plug'  rejected by strategy 'SpecificBackendLocator'
02:11:39 WARNING  yapsy                     Plugin candidate '/usr/local/lib/python3.4/dist-packages/errbot/backends/test.plug'  rejected by strategy 'SpecificBackendLocator'
02:11:39 WARNING  yapsy                     Plugin candidate '/usr/local/lib/python3.4/dist-packages/errbot/backends/hipchat.plug'  rejected by strategy 'SpecificBackendLocator'
02:11:39 DEBUG    errbot.specific_plugin_ma Load the one remaining...
02:11:39 DEBUG    errbot.specific_plugin_ma Class to load TextBackend
02:11:39 DEBUG    errbot.core               ErrBot init.
02:11:39 DEBUG    errbot.backends.base      Backend init.
02:11:39 DEBUG    errbot.core               created a thread pool of size 10.
02:11:39 DEBUG    errbot.backends.text      Text Backend Init.
02:11:39 DEBUG    errbot.backends.text      Bot username set at @errbot.
02:11:39 DEBUG    MARKDOWN                  Successfuly imported extension module "markdown.extensions.smart_strong".
02:11:39 DEBUG    MARKDOWN                  Successfully loaded extension "markdown.extensions.smart_strong.SmartEmphasisExtension".
02:11:39 DEBUG    MARKDOWN                  Successfuly imported extension module "markdown.extensions.fenced_code".
02:11:39 DEBUG    MARKDOWN                  Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension".
02:11:39 DEBUG    MARKDOWN                  Successfuly imported extension module "markdown.extensions.footnotes".
02:11:39 DEBUG    MARKDOWN                  Successfully loaded extension "markdown.extensions.footnotes.FootnoteExtension".
02:11:39 DEBUG    MARKDOWN                  Successfuly imported extension module "markdown.extensions.attr_list".
02:11:39 DEBUG    MARKDOWN                  Successfully loaded extension "markdown.extensions.attr_list.AttrListExtension".
02:11:39 DEBUG    MARKDOWN                  Successfuly imported extension module "markdown.extensions.def_list".
02:11:39 DEBUG    MARKDOWN                  Successfully loaded extension "markdown.extensions.def_list.DefListExtension".
02:11:39 DEBUG    MARKDOWN                  Successfuly imported extension module "markdown.extensions.tables".
02:11:39 DEBUG    MARKDOWN                  Successfully loaded extension "markdown.extensions.tables.TableExtension".
02:11:39 DEBUG    MARKDOWN                  Successfuly imported extension module "markdown.extensions.abbr".
02:11:39 DEBUG    MARKDOWN                  Successfully loaded extension "markdown.extensions.abbr.AbbrExtension".
02:11:39 DEBUG    MARKDOWN                  Successfully loaded extension "markdown.extensions.extra.ExtraExtension".
02:11:39 DEBUG    MARKDOWN                  Successfully loaded extension "errbot.rendering.ansiext.AnsiExtension".
02:11:39 ERROR    yapsy                     Unable to create plugin object: /usr/local/lib/python3.4/dist-packages/errbot/backends/text
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/yapsy/PluginManager.py", line 512, in loadPlugins
    plugin_info.plugin_object = self.instanciateElement(element)
  File "/usr/local/lib/python3.4/dist-packages/errbot/specific_plugin_manager.py", line 59, in instanciateElement
    return element(self._config)
  File "/usr/local/lib/python3.4/dist-packages/errbot/backends/text.py", line 252, in __init__
    self.user = self.build_identifier(self.bot_config.BOT_ADMINS[0])
  File "/usr/local/lib/python3.4/dist-packages/errbot/backends/text.py", line 409, in build_identifier
    raise ValueError('An identifier for the Text backend needs to start with # for a room or @ for a person.')
ValueError: An identifier for the Text backend needs to start with # for a room or @ for a person.
02:11:39 ERROR    errbot.bootstrap          Unable to load or configure the backend.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/errbot/bootstrap.py", line 135, in setup_bot
    bot = backendpm.get_plugin_by_name(backend_name)
  File "/usr/local/lib/python3.4/dist-packages/errbot/specific_plugin_manager.py", line 86, in get_plugin_by_name
    raise Exception('Error loading plugin %s:\nError:\n%s\n' % (name, formatted_error))
Exception: Error loading plugin Text:
Error:
<class 'ValueError'>:
  File "/usr/local/lib/python3.4/dist-packages/yapsy/PluginManager.py", line 512, in loadPlugins
    plugin_info.plugin_object = self.instanciateElement(element)
  File "/usr/local/lib/python3.4/dist-packages/errbot/specific_plugin_manager.py", line 59, in instanciateElement
    return element(self._config)
  File "/usr/local/lib/python3.4/dist-packages/errbot/backends/text.py", line 252, in __init__
    self.user = self.build_identifier(self.bot_config.BOT_ADMINS[0])
  File "/usr/local/lib/python3.4/dist-packages/errbot/backends/text.py", line 409, in build_identifier
    raise ValueError('An identifier for the Text backend needs to start with # for a room or @ for a person.')

**Comment by vlcinsky** [comment]
I had exactly the same issue.

Fixed that by modifying end of `config.py`


	BOT_ADMINS = ('@jajabot', )  # !! Don't leave that to "CHANGE ME" if you connect your errbot to a chat system !!

	BOT_IDENTITY = {"username": "@jajabot"}

**Comment by zoni** [comment]
This was fixed in #1122. For users still on an older version, the above workaround will get you around the problem as well in the mean time.
