### ISSUE TITLE
Access Original Plugin from Dynamic Plugin 

### ISSUE THREAD

**Issue by dgarros** [errbotio/errbot#1096]
### I am...

* [X] Requesting help writing plugins
* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Here about something else

### I am running...

* Errbot version: 5.1.2
* OS version: Ubuntu 
* Python version:  3.5
* Using a virtual environment: no but I'm using Docker

### Issue description
Hi

I'm new to Errbot and I'm currently trying to write some plugins to learn the architecture and solve some of my use cases.
I would like to dynamically create commands but each of these commands need to talk to an API so I need some information (server address, token etc .. )

Currently my idea was to save these information into another plugin and access them within my dynamic plugin with `self.get_plugins('PluginName')`. But I tried and I'm getting an error message because the dynamic plugin is not activated. 

My Dynamic plugin is named `queries`, in the example `getdevices` and `getinterfaces` are dynamically created. 
```
[@* ➡ @errbot] >>> help queries
[@* ➡ @errbot] [␍]
queries
 Library of Graph Queries to execute on AOS
• !getdevices - Get list of all devices
• !getinterfaces - Get list of all interfaces

[@* ➡ @errbot] >>> getdevices
[@* ➡ @errbot] [␍]
Computer says nooo. See logs for details:
 Plugin needs to be in activated state to be able to get its dependencies.
```

Here is my `Command` function
```python
Command(
                lambda plugin, msg, args: plugin.get_plugin('PluginName').run_query(file, msg, args),
                name='getinterfaces',
                doc='Get list of all interfaces')
```

is there a way to activate a dynamic plugin or just to access the value of another plugin ?
Or am I approaching this problem the wrong way ?
 
Thanks in advance for your help

**Comment by gbin** [comment]
maybe simply make a normal python module for the API?

**Comment by dgarros** [comment]
Thanks for your response but not sure if that would work
is it possible to activate a plugin manually ? for example would i be able to do something like that.

```python
plugin.activate()
plugin.get_plugin('PluginName').run_query(file, msg, args),
```

**Comment by zoni** [comment]
Closing this issue due to age. Please let us know if you are still experiencing issues (I have some ideas to share if you're still stuck with this).
