### ISSUE TITLE
Does errbot support Stride, the new Hipchat Cloud?

### ISSUE THREAD

**Issue by yangliping** [errbotio/errbot#1100]
Atlassian announced a new product called Stride. All HipChat Cloud teams will upgrade to Stride. Can I use errbot with Stride now? Is it compatible?

**Comment by sijis** [comment]
There is no Stride backend in Errbot and I'm not seeing any mentions of one being worked on. I'd say it's currently compatibility is unknown.

The Stride API is currently in Early Access.
https://developer.atlassian.com/blog/2017/09/apply-for-the-stride-api-early-access-program/

We would obviously welcome any PRs on this.

**Comment by sijis** [comment]
Looks like the way forward here is to use the Slack backend.

https://slackhq.com/atlassian-and-slack-partnership.

**Comment by andrewthetechie** [comment]
#closeit

**Comment by sijis** [comment]
Based on that article, there is no need to do this as the service is being shutdown in about 5 weeks.

Atlassian is providing instructions (https://www.atlassian.com/partnerships/slack/migration) how migrate to Slack.

We do have a functional Slack backend to support those organizations migrating.
