### ISSUE TITLE
Hipchat backend is failing with certificate expired error 

### ISSUE THREAD

**Issue by iliakhovskyi** [errbotio/errbot#1101]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [x] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.1.2
* OS version: Ubuntu 14.04.5 LTS
* Python version:  3.4.3
* Using a virtual environment: yes

### Issue description

After restarting the bot I was unable to run it against Hipchat backend anymore. 
In debug logs I constantly see certificate errors like:

> 11:55:24 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: ssl_cert
> 11:55:24 ERROR    sleekxmpp.xmlstream.xmlst Certificate has expired.
> 11:55:24 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: session_end
> 11:55:24 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: disconnected
> 11:55:24 INFO     errbot.core               Disconnect callback, deactivating all the plugins.
> 11:55:24 DEBUG    sleekxmpp.thirdparty.stat  ==== TRANSITION connected -> disconnected
> 11:55:24 DEBUG    sleekxmpp.xmlstream.xmlst SEND (IMMED): <stream:stream to='chat.hipchat.com' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client' xml:lang='en' version='1.0'>
> 11:55:24 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: socket_error
> 11:55:24 WARNING  sleekxmpp.xmlstream.xmlst Failed to send b"<stream:stream to='chat.hipchat.com' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client' xml:lang='en' version='1.0'>"
> 11:55:24 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: session_end
> 11:55:24 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: socket_error
> 11:55:24 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: disconnected
> 11:55:24 INFO     errbot.core               Disconnect callback, deactivating all the plugins.
> 11:55:24 DEBUG    sleekxmpp.thirdparty.stat  ==== TRANSITION connected -> disconnected
> 11:55:24 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: socket_error
> 11:55:24 ERROR    sleekxmpp.xmlstream.xmlst Socket Error #9: Bad file descriptor
> 11:55:24 DEBUG    sleekxmpp.xmlstream.xmlst reconnecting...
> 11:55:24 DEBUG    sleekxmpp.xmlstream.xmlst connecting...
> 11:55:24 DEBUG    sleekxmpp.xmlstream.xmlst Waiting 1.8599474133756573 seconds before connecting.
> ^C11:55:26 DEBUG    errbot.backends.xmpp      Trigger disconnect callback
> 11:55:26 DEBUG    sleekxmpp.xmlstream.xmlst Stopped event runner thread. 2 threads remain.
> 11:55:26 INFO     errbot.core               Disconnect callback, deactivating all the plugins.
> 11:55:26 DEBUG    errbot.backends.xmpp      Trigger shutdown
> 11:55:26 DEBUG    errbot.storage            Closed storage 'hipchat_backend'
> 11:55:26 INFO     errbot.plugin_manager     Shutdown.

Also I've checked the certificate it is complaining about - it's valid till December 2017. 
Hipchat is cloud hosted, so there shouldn't be any certificate issue. 

I will be grateful for any help. 

### Steps to reproduce

Set 'Hipchat' backend in config. 
Specify hipchat user password and token.  

Run errbot in test mode. 
### Additional info

If you have any more information, please specify it here.

**Comment by jereze** [comment]
Same problem for us.

**Comment by andy-grandy** [comment]
Same problem:
Ubuntu 16.04.3 x64
errbot 5.1.2
Python 3.5.2

**Comment by andy-grandy** [comment]
Problem in sleekxmpp 1.3.3
Uninstall 1.3.3 and install 1.3.1 (release version), it works!
`pip3 install -Iv sleekxmpp==1.3.1`

**Comment by iliakhovskyi** [comment]
@andy-grandy thanks, that was the problem!

**Comment by Neustradamus** [comment]
Have you tested 1.3.2?
