### ISSUE TITLE
Multiple modules for one plugin

### ISSUE THREAD

**Issue by dwickwire** [errbotio/errbot#1104]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [x] Requesting help with running my bot
* [x] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5
* OS version: xenial
* Python version: 2+
* Using a virtual environment: no

### Issue description

My plugin has grown and I would like to break it apart into separate modules but the plugin is unable to start up when I import other modules from the same directory.

Example:

```python
# plugins/myplugin/myplugin.py
from myothermodule import LegitClass
```

Throws:
```
Some plugins failed to start during bot startup:
 File ".../venv/lib/python3.6/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
  File ".../venv/lib/python3.6/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File ".../venv/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File ".../errbot/plugins/myplugin/myplugin.py", line 2, in <module>
    from myothermodule import LegitClass
```

It seems each module must be registered to Errbot, but I don't see any way to register multiple modules to a plugin in the docs.  How can I do that?

**Comment by sijis** [comment]
I'm not sure if it will work, but what happens if you try a local import?
`from .myothermodule import LegitClass`

**Comment by dwickwire** [comment]
I tried this as well, it also fails.

**Comment by SirEdvin** [comment]
If you run errbot in `/errbot` directory, try to import `plugins.myplugin.myplugin`

All you additional modules should be in python path

**Comment by dwickwire** [comment]
That's it.  Thanks.

**Comment by sr105** [comment]
For posterity... The comments here didn't work for me, but I figured it out and documented it on this similar issue (which is still open as of this time): https://github.com/errbotio/errbot/issues/1109#issuecomment-479912958
