### ISSUE TITLE
Update docs for start_poller() and stop_poller()

### ISSUE THREAD

**Issue by slickriptide** [errbotio/errbot#1105]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [x ] Here about something else

### I am running...

* Errbot version: 5.1.2
* OS version: Windows 10 (Creator Edition)
* Python version: 3.6
* Using a virtual environment: no

### Issue description

The online docs for start_poller() and stop_poller() need to be updated. Somewhere along the way, somebody added another parameter (times:integer) to both functions and stuck the new parameter between the method and args parameters. The upshot is that any older plugin that upgrades to the newest errbot will mysteriously fail if it uses pollers because errbot will be trying to use the args parameter as the times parameter.

### Steps to reproduce

Call stop_poller() following the online docs.

**Comment by sijis** [comment]
I'm not sure I completely follow the issue.

I was able to run the following without an error:

```
from errbot import BotPlugin

class PluginExample(BotPlugin):

    counter = 0

    def my_callback(self):
        self.log.debug('I am called every minute')
        self.counter += 1
        print('calling callback')
        if self.counter > 5:
            self.stop_poller(self.my_callback)
            print('poller for callback killed')

    def activate(self):
        super().activate()
        self.start_poller(5, self.my_callback)
```

If there's a more concrete example, that would be great.

**Comment by slickriptide** [comment]
Instead of this:

self.start_poller(5, self.my_callback)

try this:

self.start_poller(5, self.my_callback, (arg1,arg2))

The above worked in errbot 3.x. In errbot 5.x, there's a new "times" parameter between the callback and the arguments. 

Using keywordargs would most likely work fine. Using ordered args failed because there is now a new, undocumented argument in start_poller.

Here's what the documentation says:
----
start_poller(interval: float, method: typing.Callable[..., NoneType], args: typing.Tuple = None, kwargs: typing.Mapping = None)
----

It should actually read:
-----
start_poller(interval: float, method: typing.Callable[..., NoneType], times:integer,args: typing.Tuple = None, kwargs: typing.Mapping = None)
-----

The "times" parameter appears to be an integer that indicates "activate this poller X number of times only".

So, to show the concrete example from my own code, I had to change from this:

self.start_poller(timer,self.send_u_stanza,(baseRoom,flags))

to this:

self.start_poller(timer,self.send_u_stanza,None,(baseRoom,flags))

and then my bot started working again.

Just to be clear, the initial bug report is for the missing documentation. I have no reason to believe that "times" is malfunctioning - only that it's undocumented and that affects anyone who is passing parameters to their callback function.

**Comment by zoni** [comment]
> (I have no idea why the bolding and font-size went wonky in the middle. It was not intentional.)

GitHub uses markdown for formatting, which uses triple backticks for code blocks, not dashes. Underlining causes the previous sentence to become a header. See also https://guides.github.com/features/mastering-markdown/

> The above worked in errbot 3.x. In errbot 5.x, there's a new "times" parameter between the callback and the arguments.
>
> Using keywordargs would most likely work fine. Using ordered args failed because there is now a new, undocumented argument in start_poller.

Meh. This is an unfortunately (and likely unforeseen) side-effect of the changes made to `start_poller`. I'm glad you've pointed out the issue.

It seems ReadTheDocs was still building and defaulting to the 5.0 branch instead of 5.1, caused by a combination of our branch-based versioning strategy and my not updating the RTD configuration. I've updated the necessary settings and believe that should resolve this issue. Please let me know if things still appear incorrect.

Thank you for reporting this to us!
