### ISSUE TITLE
Errbot doesn't return the string to hipchat using flows

### ISSUE THREAD

**Issue by hari95kishore** [errbotio/errbot#1106]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug

### I am running...

* Errbot version: 5.0.1
* OS version: ubuntu 14.04
* Python version: 3.4.3
* Using a virtual environment: yes/no

### Issue description

Return statement doesn't return to hipchat using flows. I have a flow with the first node as autoTrigger = True. The flow continues for another three nodes (linear graph) and the last node is being triggered automatically without user intervention using predicate lambda function. I have a return statement in the last node. The defined functionality in the last node is performed, and i could even print it in the console what i want to return to hipchat. But when i put the same print statement in return, its not working.

### Steps to reproduce

I have a flow like below:

Flow [jiraflow]  <br>  ↪ jira_issue  <br>    ↪ issue_type  <br>      ↪ summary  <br>        ↪ description  <br>          ↪ create_issue  <br>

The flow definition is as follows:

@botflow
def jiraflow(self, flow: FlowRoot):
     project = flow.connect('jira_issue', auto_trigger=True)
     issue_type = project.connect('issue_type')
     summary = issue_type.connect('summary')
     description = summary.connect('description')
     description.connect('create_issue', predicate=lambda ctx: 'description' in ctx)

and create_issue has a return statement in it and it doesn't send it back to hipchat

@botcmd
def create_issue(self, msg, _):
      print("triggered")
      issue_details = {'project': msg.ctx['project'],
                                 'issuetype': {'name': msg.ctx['issue_type']},
                                 'summary': msg.ctx['summary'],
                                 'description': msg.ctx['description'],
      }
      issue = self.jira.create_issue(fields=issue_details)
      print(' JIRA issue created successfully. The ticket number is '+ str(issue))
      return ' JIRA issue created successfully. The ticket number is '+ str(issue)

Here the print statement is printed in the console but return doesn't send a message to hipchat backend.

I have tried self.send(msg.frm.room, ' JIRA issue created successfully. The ticket number is '+ str(issue))
 It throws error as msg.from unknown and this is triggered automatically without user intervention.

**Comment by hari95kishore** [comment]
@janemarshal nope I couldn’t find a solution for it. Use yield instead. But mind that combination of yield and return doesn’t work.

**Comment by janemarshal** [comment]
Thanks @hari95kishore Using yield did not work for me. Instead I replaced all the yields with return and then used self.send(room, msg). And that worked for me. 

"But mind that combination of yield and return doesn’t work." This actually helped to solve the issue. Thank you.

**Comment by ppff** [comment]
I confirm: you can't mix yield and return statements. (Tested on errbot 5.2.0 with python 3.5.2.)

Note however that return statements will indeed quit the function, it won't send the message though.

**Comment by andrewthetechie** [comment]
https://www.theverge.com/2018/7/26/17619482/slack-hipchat-acquisition-stride-atlassian-partnership-microsoft-teams-competition

Hipchat is going away here very soon.

#closeit

**Comment by sijis** [comment]
Using `self.send(room, msg)` is the right approach. Hipchat is no longer available too.
