### ISSUE TITLE
Errbot Import error on the class same package with module

### ISSUE THREAD

**Issue by aliaramli** [errbotio/errbot#1109]
### I am.

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [x ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version:5.1.2
* OS version: Debian 8
* Python version: 3.6
* Using a virtual environment: yes

### Issue description
```
|----/opt/errbot/plugins/Vm/
                         |---vm.py
                         |---vm.plug
                         |---model.py
                         |---*
```

I have a plugin module, in the plugin module directory i included a python class name M_Vm to act as a modeler in model.py

How ever, when i run errbot, im not able to import the M_Vm class

```
errbot_1  |   File "/usr/local/lib/python3.6/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
errbot_1  |     candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
errbot_1  |   File "/usr/local/lib/python3.6/imp.py", line 234, in load_module
errbot_1  |     return load_source(name, filename, file)
errbot_1  |   File "/usr/local/lib/python3.6/imp.py", line 172, in load_source
errbot_1  |     module = _load(spec)
errbot_1  |   File "<frozen importlib._bootstrap>", line 675, in _load
errbot_1  |   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
errbot_1  |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
errbot_1  |   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
errbot_1  |   File "/opt/errbot/plugins/Vm/vm.py", line 3, in <module>
errbot_1  |     from model import M_Vm
```

running pylint on vm.py doesnt complaint anything on no name module error...

```
No config file found, using default configuration
************* Module vm
C:212, 0: Trailing newlines (trailing-newlines)
C:  1, 0: Missing module docstring (missing-docstring)
R: 33, 0: Too many ancestors (11/7) (too-many-ancestors)
W: 45,33: Unused argument 'args' (unused-argument)
R: 45, 4: Method could be a function (no-self-use)
R: 51, 4: Method could be a function (no-self-use)
R: 60, 4: Method could be a function (no-self-use)
R: 70, 4: Method could be a function (no-self-use)
R:110, 4: Method could be a function (no-self-use)
W:128, 8: Redefining built-in 'list' (redefined-builtin)
R:121, 4: Method could be a function (no-self-use)
W:139,41: Unused argument 'polled_time' (unused-argument)
R:153, 4: Method could be a function (no-self-use)
E:169, 4: method already defined line 121 (function-redefined)
R:169, 4: Method could be a function (no-self-use)
C:196, 4: Missing method docstring (missing-docstring)
R:196, 4: Method could be a function (no-self-use)
C:200, 4: Missing method docstring (missing-docstring)
R:200, 4: Method could be a function (no-self-use)
C:204, 4: Missing method docstring (missing-docstring)
R:204, 4: Method could be a function (no-self-use)
C:  9, 0: Imports from package errbot are not grouped (ungrouped-imports)

```

**Comment by gbin** [comment]
Can you try: ` from .model import M_Vm` ?

**Comment by aliaramli** [comment]
` from .model import M_Vm`

seems like still having the same behaviour

**Comment by aliaramli** [comment]
The current workaround is not to use python script named model..then it works~

**Comment by quimmontal** [comment]
I am having the same error when trying to import directly a function from a python script in the same folder. 

In my case the script name is prepareAlerts.py and the function in it analyse(args), but when executing the errbot daemon I get this error:


> Some plugins failed to start during bot startup:
File "/home/user/.errbot-ve/lib/python3.4/site-packages/yapsy/PluginManager.py", line 488, in loadPlugins
   candidate_module = imp.load_module(plugin_module_name,plugin_file,candidate_filepath+".py",("py","r",imp.PY_SOURCE))
 File "/home/user/.errbot-ve/lib/python3.4/imp.py", line 235, in load_module
   return load_source(name, filename, file)
 File "/home/user/.errbot-ve/lib/python3.4/imp.py", line 171, in load_source
   module = methods.load()
 File "<frozen importlib._bootstrap>", line 1220, in load
 File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
 File "<frozen importlib._bootstrap>", line 1129, in _exec
 File "<frozen importlib._bootstrap>", line 1471, in exec_module
 File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
 File "/home/user/.errbot-ve/bin/plugins/test/test.py", line 8, in <module>
   from  prepareAlerts import analyse

The error is the same when I try to import only the script doing "import prepareAlerts". It doesn't go further than that import.

**Comment by sr105** [comment]
Here's how I solved it for my "Finance" plugin:

```none
plugins/finance
├── finance
│   ├── __init__.py
│   ├── date_methods.py
│   └── finance.py
├── finance.plug
└── requirements.txt
```

You're going to create a Python package and tell the PluginManager to import that.

plugins/finance/finance.plug:
```ini
[Core]
Name = Finance
Module = finance

[Documentation]
Description = Contains commands for doing finance-like things

[Python]
Version = 3
```

You must "export" your Bot classes that you want the the PluginManager to find in your package __init__.py.

plugins/finance/finance/__init__.py
```python
"""The Finance plugin."""

from .finance import Finance

__all__ = (
    "Finance",
)
```

plugins/finance/finance/finance.py:
```python
"""Finance tasks plugin."""

from errbot import BotPlugin, botcmd

from .date_methods import MultiDict, get_datetime_range, DateRangeForm


class Finance(BotPlugin):
    """Commands for doing Finance things."""

    @botcmd(split_args_with=None)
    def fin_demo(self, msg, args):
         # ...
        pass
```

**Comment by jeremymec** [comment]
sr105 I have tried your solution but get a 'file not found' error relating to the plugin.py file. Do you have any suggestions?

**Comment by nzlosh** [comment]
@jeremymec Can you share the exact error message you're getting as well as the version of errbot and Python you are using please?

**Comment by sr105-tm** [comment]
@jeremymec also, can you share your file/folder layout?

**Comment by jeremymec** [comment]
Sure! The error is 
`FileNotFoundError: [Errno 2] No such file or directory:'C:\dev\Errbot-project\bot\plugins\finance\finance.py'`

(To use the names from the above example).

If I change the `module =` in the .plug file to `finance/finance` instead of `finance`, the error I get is the same as when it's not in its own folder - `ModuleNotFoundError: No module named 'errbot.plugins'`

Errbot version 6.1.2
Python version 3.6.8

**Comment by jeremymec** [comment]
Folder structure is

Errbot-project/bot/plugins/confluence
├── confluence
│   ├── __init__.py
│   ├── confluence-service.py
│   └── confluence.py
├── confluence.plug
├── create-confluence.flow
├── create-confluence-flow.py

**Comment by nzlosh** [comment]
It's quite confusing to have messages that don't correspond to your actual directory structure.  Let's stick to unedited error messages going forward and talk about your setup.

Does `confluence.plug` contain:

```ini
[Core]
Name = Confluence
module = confluence
```
and `confluence/__init__.py` contain:
```python
from .confluence import Confluence

__all__ = (
    "Confluence",
)
```

**Comment by jeremymec** [comment]
Yes. Verbatim!

**Comment by jeremymec** [comment]
Hi future people.
I have fixed this problem. The only thing that works was doing an *absolute* import, but ensure the module is located in the folder you run `errbot` in, in my case the project/bot folder.
