### ISSUE TITLE
Broken argument parsing for channel names with whitespaces.

### ISSUE THREAD

**Issue by derAnfaenger** [errbotio/errbot#1115]
### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.1.2 (latest pip package)
* OS version: Windows 10
* Python version: 3.5
* Using a virtual environment: no

### Issue description

I think I've noticed some issues with the ErrBot command handing: Some channel names can contain whitespaces.  The command /room occupants "channel name" works and correctly calls query_room() with 'channel name', but /room join "channel name" calls query_room() with '"channel' - the string encapsulation didn't work.

### Steps to reproduce

1. Create a channel and include whitespace characters in its name.
2. Try out the above commands.

**Comment by sijis** [comment]
What's backend you are using?

**Comment by derAnfaenger** [comment]
@sijis sorry, completely missed that. If still of interest, I encuntered this when developing a backend for Zulip.
