### ISSUE TITLE
HipChat: Documentation seems to be wrong or something has broken.

### ISSUE THREAD

**Issue by AnZaNaMa** [errbotio/errbot#1123]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.1.2
* OS version: Xubuntu 16.04.2 LTS
* Python version: 3.5.2
* Using a virtual environment: yes

### Issue description

I have been noticing that the information provided about the HipChat backend is wrong in some places. I've been referencing [this](http://errbot.io/en/latest/user_guide/configuration/hipchat.html) page. It states that the BOT_ADMINS can be set using HipChat @ mention names. However, I've found this to be false and learned that the Jabber/XMPP names must be used instead. 

Also, I've found that attempting to connect to a room that doesn't exist just automatically and fairly silently creates a new one. This may be intentional but seems kind of strange.

**Comment by Fabio101** [comment]
Noticed this too on 5.1.3

**Comment by andrewthetechie** [comment]
https://www.theverge.com/2018/7/26/17619482/slack-hipchat-acquisition-stride-atlassian-partnership-microsoft-teams-competition

Hipchat is going away here very soon.

#closeit

**Comment by sijis** [comment]
Based on that article, there is no need to do this as the service is being shutdown in about 5 weeks.

Atlassian is providing instructions (https://www.atlassian.com/partnerships/slack/migration) how migrate to Slack.

We do have a functional Slack backend to support those organizations migrating.
