### ISSUE TITLE
Using specific features of some backends in ErrBot

### ISSUE THREAD

**Issue by fernand0** [errbotio/errbot#1131]
In order to let us help you better, please fill out the following fields as best you can:

### I am...
* [x] Suggesting a new feature

### I am running...
* Errbot version: Last one
* OS version: Ubuntu 17.10
* Python version:  3.5.3
* Using a virtual environment: yes (pyenv)

### Issue description
I'm using the telegram backend for ErrBot. I know that telegram API allows for messages to use markdown and html. If I understand everything well, I could change:

    self.telegram.sendMessage(msg.to.id, body)

for something using parse_mode indicating, for example, Markdown but I was wondering if there are any plans to change this (maybe adding a parameter in the configuration or in the communication functions for the bot). Or, maybe, there is a better way to do this.

**Comment by gbin-argo** [comment]
It has been there for a while: http://errbot.io/en/latest/user_guide/plugin_development/backend_specifics.html

**Comment by fernand0** [comment]
Thanks!
I didn't find it.

**Comment by fernand0** [comment]
Code example (just in case), for telegram backend:

            if (self._bot.mode == "telegram"):
                self._bot.telegram.send_message(mess.frm.id, formattedUpdates, parse_mode = 'Markdown')
            else:
                yield(formattedUpdates)

formattedUpdates contains the text with markdown.
