### ISSUE TITLE
Chatbot Creation

### ISSUE THREAD

**Issue by 9880649203** [errbotio/errbot#1132]
In order to let us help you better, please fill out the following fields as best you can:

### I am...ashwini 

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...OS Version

* Errbot version:
* OS version:
* Python version: 
* Using a virtual environment: yes/no

### Issue description  I Actually Want to Create a chatbot From angular Js Can Enyone Guide Me how To create From The Scratch In my Company There Is No Senior Person I should Create A chatbots itseems IAm Very Freshers Related To this Currently Iam Working as webdeveloper..

Please describe your bug/feature/problem here.
The more information you can provide, the better.

### Steps to reproduce

In case of a bug, please describe the steps we need to take in order to reproduce your issue.
If you cannot easily reproduce the issue please let us know and provide as much information as you can which might help us pinpoint the problem.

### Additional info
Please Can enybody Email me Regarding The procedure at ashwinibj7@gmail.com[9880649203]

If you have any more information, please specify it here.

**Comment by sijis** [comment]
I can point you to a few locations for documentation on how to set an Errbot bot up:
* https://alimac.io/adventures-with-errbot-part-1/
* http://errbot.io/en/latest/user_guide/setup.html#installation
* http://errbot.io/en/latest/#community
