### ISSUE TITLE
Can't get ACLs to work with the Slack backend

### ISSUE THREAD

**Issue by jbfriedrich** [errbotio/errbot#1133]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [x] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.1.3
* OS version: CentOS 7.3
* Python version: 3.4.5
* Using a virtual environment: yes

### Issue description

I have enabled the core plugins in the configuration that I want to use and also successfully specified the backend I want to use. Without defining any ACLs, the bot replies fine.

```
CORE_PLUGINS = ('ACLs', 'Help', 'Plugins', 'Health', 'Utils',)
BACKEND = 'Slack'
BOT_IDENTITY = {
    'token': 'xoxb-12345',
}
BOT_ALT_PREFIXES = ('@botname',)
CHATROOM_PRESENCE = ()
```

As soon as I try to define ACLs though, the bot is either open for everyone or is telling everyone, including the admin(s) that they are nto allowed to access this command from that user:

```
BOT_ADMINS = ('@jason')
HIDE_RESTRICTED_COMMANDS = True
HIDE_RESTRICTED_ACCESS = False
ACCESS_CONTROLS_DEFAULT = {
    'help': { 'allowusers': ('@jason', ) },
}
ACCESS_CONTROLS = {
    '*': { 'denyusers': ('*') },
}
```

For starters, I would like to deny access to everyone and only allow access from BOT_ADMINS or specific users. Is something like that possible? How can I do that?

It seems that I am stuck. Any help would be appreciated. Thanks!

**Comment by GenPage** [comment]
@jbfriedrich I believe this is a race condition with the ACL plugin. It appears you cannot have both `allowusers` and `denyusers`. As even if your user is in `allowusers`, `denyusers:*` matches still in lines L80-81

https://github.com/errbotio/errbot/blob/c8b36412f5972d45c60009fb4c60414cc5bc966b/errbot/core_plugins/acls.py#L78-L81

The best way forward for now might just be using `allowusers` as a whitelist.

**Comment by jbfriedrich** [comment]
@GenPage I tried that, but if I configured

```
ACCESS_CONTROLS_DEFAULT = {
    'help': { 'allowusers': ('@jason', ) },
}
```

and did not specify ACCESS_CONTROLS at all in the config, other people were able to query the bot and use some of the commands. It seems that "deny everything" is not the default when I use allowusers as a whitelist.

**Comment by GenPage** [comment]
Have you tried this instead:

```
ACCESS_CONTROLS_DEFAULT = {
    '*:*': { 'allowusers': ('@jason', ) },
}
```

What you were using would only restrict the `help` command for every plugin. 

https://github.com/errbotio/errbot/blob/c8b36412f5972d45c60009fb4c60414cc5bc966b/errbot/core_plugins/acls.py#L69-L71

**Comment by shengis** [comment]
Hey, I wrote a little plugin for errbot to manage fine access to plugins. I'm using it on Slack.
https://github.com/shengis/err-profiles

**Comment by zoni** [comment]
@jbfriedrich you may have figured it out by now, but if you are still stuck, you have `ACCESS_CONTROLS_DEFAULT` and `ACCESS_CONTROLS` swapped. `ACCESS_CONTROLS_DEFAULT` is only applied if `ACCESS_CONTROLS` does not produce a match.

@shengis that's a very nice plugin :+1: I've added a reference to it in our user guide (https://github.com/errbotio/errbot/commit/bbd0c8e3f47ae10ebd90f972962c5ecce4973c0b).
