### ISSUE TITLE
More useful scheduler options

### ISSUE THREAD

**Issue by rcoup** [errbotio/errbot#1134]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [X] Suggesting a new feature

### I am running...

* Errbot version: 5.1.3

### Issue description

Currently you can setup a thread poller per plugin, but to do actions once a day or less (which must be reasonably common), it's actually a bit messy. Current workaround I'm using:

```python
class MyPlugin(BotPlugin):
    def activate(self):
      super(MyPlugin, self).activate()
      self.start_poller(60*60, self.check_things)  # hourly check

    def check_things(self):
        now = datetime.now(pytz.timezone(self.config['TIMEZONE']))
        if now.hour != 8:  # somewhere between 8am and 9am
            return
        elif now.weekday() >= 5:  # on weekdays
            return

        msg = self.find_out_things()
        self.send(self.build_identifier(self.config['CHANNEL']), msg)
```

Thoughts on a single global poller thread and a scheduler which takes cron-style formats? Maybe along the lines of:

```python
class MyPlugin(BotPlugin):
    def activate(self):
        super(MyPlugin, self).activate()
        # weekdays at 8am
        # TODO: pull from plugin config
        self.schedule("0 8 * * 1-5", self.check_things, timezone="Pacific/Auckland")

    def schedule(self, crontab, action, timezone=None):
         ...
```

There are several Python crontab-parsers (eg. https://github.com/kiorky/croniter) that could be used to implement underneath.

Going further, there could be any/all of:
1. an errbot config option to set the scheduler timezone
2. an errbot config option to set the time of day that `@daily @weekly @monthly` etc run at (eg. 8am rather than midnight).
3. a custom `@weekdays` 😉 

Then it simplifies even further to:

```python
class MyPlugin(BotPlugin):
    def activate(self):
        super(MyPlugin, self).activate()
        self.schedule("@weekdays", self.check_things)
```

**Comment by gbin-argo** [comment]
https://github.com/attakei/errcron would work for you?

**Comment by rcoup** [comment]
@gbin-argo nice! That will be ace. Not sure how I didn't find that. Thanks :)
