### ISSUE TITLE
Plugin test backend tries to launch graphical backend on OS X 

### ISSUE THREAD

**Issue by jharley** [errbotio/errbot#1141]
### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.1.3
* OS version: OS X 10.12.6
* Python version: 3.6.3
* Using a virtual environment: yes

### Issue description

It seems that on OS X the 'graphical' backend is trying to be started for plugin tests, which tries to start PySide (which is not supported on Python >3.4, if I understand correctly).

### Steps to reproduce

```
brew install python3
python3 -m venv venv
. venv/bin/activate
pip install errbot==5.1.3 pytest
pytest 
```

Attaching output as [errbot-pytest.log](https://github.com/errbotio/errbot/files/1519233/errbot-pytest.log)

### Additional info

The same test suite runs fine on Ubuntu 16.04 with Python 3.5.2 using the commands above (except `brew install` :))

**Comment by jharley** [comment]
Interestingly, the same test suite pushed to CircleCI caused the telegram backend to be chosen?

**Comment by gbin** [comment]
I am very confused by this, can you try to debug it it makes absolutely no
sense :)

**Comment by jharley** [comment]
@gbin I am very confused also! :\ I switched the Circle build to 3.5 and it tried to use the graphical backend similar to above.

I'll pull together a public example repo over the weekend

**Comment by gbin** [comment]
Do you see that in the log ? Can you copy paste them?

**Comment by gbin** [comment]
Sorry we have that, gonna look closer

**Comment by jharley** [comment]
I *think* I've tracked down the issue to be the fact that I was setting up the virtualenv along side the tests?  Something about the way errbot is loading things dynamically was causing it to load itself and throw a proverbial-wrench into things...  moving the virtualenv to `~/venv` above causes the tests to run cleanly.

Does this make any (more) sense?
