### ISSUE TITLE
Support Ryver Backend

### ISSUE THREAD

**Issue by Gelob** [errbotio/errbot#1146]
### I am...

* [X] Suggesting a new feature

### I am running...

* Errbot version:
* OS version:
* Python version: 
* Using a virtual environment: yes/no

### Issue description

It would be great if there was support for the chat application [Ryver](https://ryver.com/) for errbot. There is a beta Hubot plugin https://github.com/RyverApp/hubot-ryver and here is some [API documentation](http://ryverdocs.readthedocs.io/en/latest/). Their API is [OData](http://www.odata.org/) bassed

**Comment by sijis** [comment]
We provide a mechanism to create backends as plugins http://errbot.io/en/latest/user_guide/backend_development/index.html.

There are few notable examples online such as https://github.com/Vaelor/errbot-mattermost-backend, https://github.com/errbotio/errbot-backend-skype that can be used as a reference.

**Comment by andrewthetechie** [comment]
#closeit

**Comment by sijis** [comment]
There's been no traction on this. If there's progress, feel free to open a new issue and reference this one.
