### ISSUE TITLE
There should be a way to stop a plugin from activating/conditional activation

### ISSUE THREAD

**Issue by shuhaowu** [errbotio/errbot#1150]
### I am...

* [x] Suggesting a new feature

### I am running...

* Errbot version: 5.1.3
* OS version: Debian Jessie
* Python version: 3.4.3
* Using a virtual environment: yes

### Issue description

There should be a way to stop a custom plugin in the plugins directory from activating. Right now, the only way to do this is to raise an exception, which will cause the `BotPluginManager.activate_plugin_with_version_check` method to deactivate the plugin. This leaves an exception log, however.

There are times when a plugin could determine that its activating is unnecessary (perhaps forbidden via a configuration set via config.py, or something similar). Not leaving the exception would be nice.

### Suggested fix

Allow the plugin's `activate` method to raise a `PluginCancelledActivation` exception that doesn't reraise the exception to be logged would be nice.

**Comment by zoni** [comment]
This is already possible. If you override `activate()` and don't call `activate()` on the parent class (so don't `super().activate()`) then the plugin should end up not being activated.

Please let me know if that isn't working as intended.
