### ISSUE TITLE
Support pip packaging scripts, and import via pip entrypoints

### ISSUE THREAD

**Issue by elijah-roberts** [errbotio/errbot#1152]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [x] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### Issue description

Goal: I would like to make plugin management through configuration managers like puppet or ansible easier by supporting importing plugins as pip packages. errbot would be able to import any plugins installed in its local site-packages. 

I think that we could implement this by using pip packaging "entrypoints".  More info can be found [here](http://amir.rachum.com/blog/2017/07/28/python-entry-points/). Basically we could package our script repos, and use a defined entry point(i.e errbot-plugin). Then we would just need to add logic to the plugin manager to scan site-packages and import any modules that have an entry point matching "errbot-plugin". 

I think that we could implement this while retaining the current plugin import process.

**Comment by sijis** [comment]
It was officially released in 6.2.0 release.

https://github.com/errbotio/errbot/pull/1590
