### ISSUE TITLE
CI failed on master branch due to out-of-date PR being merged

### ISSUE THREAD

**Issue by tysonclugg** [errbotio/errbot#1155]
I noticed that the [most recent CI build of the master branch](https://travis-ci.org/errbotio/errbot/builds/337258699) failed, despite the [last build of the most recently merged PR](https://travis-ci.org/errbotio/errbot/builds/335808481) passed.  The ![build failing](https://camo.githubusercontent.com/60ca2aa1cc4c116e72de223623bc853d4ebb2c6a/68747470733a2f2f696d672e736869656c64732e696f2f7472617669732f657272626f74696f2f657272626f742f6d61737465722e737667) badge on the GitHub project page looks bad for the project.

I am assuming the reason for the build failure is that the PR was not up-to-date with master before being merged, and changes introduced between the branch being created and the PR being merged introduced the issue.

There are a number of branch protection features that can be enabled in GitHub repository settings, branch protection should be enabled for the master branch to prevent out-of-date branches being merged into master:
![selection_372](https://user-images.githubusercontent.com/218251/35784993-11d32aae-0a71-11e8-8280-b9117865b105.png)

**Comment by sijis** [comment]
I literally reran the failed job and it passed.
The original error state of that seemed odd and the tests had passed locally and as you mentioned, the PR passed too.

**Comment by tysonclugg** [comment]
That's odd and somewhat disconcerting, the build failure isn't showing in Travis anymore.  Surely there's something wrong with the test suite - computers are deterministic, right? :roll_eyes: 

It's still possible for out-of-date PRs can be merged into master.  I'll let others decide if that's an issue worthy of any further attention, or this issue can be closed.

**Comment by GenPage** [comment]
Definitely something to review, usually GitHub is pretty good about catching out of date PRs that conflict with master if other changes have been made.

**Comment by tysonclugg** [comment]
@GenPage wrote:
> Definitely something to review, usually GitHub is pretty good about catching out of date PRs that conflict with master if other changes have been made.

**_Merge conflicts with master_ are not the issue I'm talking about.**

Consider a change `A` adding a required parameter to `foo()`, such that the method signature becomes `foo(bar)`.  If the `A` change has correctly updated all calls to `foo()`, then the test suite will pass.

Now consider change `B` adding a new module that calls `foo()`, but `B` is based on a commit prior to `A` being merged.  Again, the test suite for `B` will pass.  Furthermore, there are no merge conflicts as the new module won't conflict with the changes introduced in `A`.

When both `A` and `B` are merged, the new module introduced in `B` has a bug - it doesn't include the required parameter on the `foo()` call.  The bug doesn't show until _after_ the merge (to master), which is too late.

The easiest way to prevent this sort of issue is to not allow _outdated_ branches to be merged to master, and hence GitHub have been wise enough to provide branch protection features doing exactly this.

**Comment by GenPage** [comment]
@tysonclugg Excuse me, I wasn't specifically referring to merge conflicts with master but I can see how it might seem like it.

I was referring to how GitHub will know that the Pull Request is out of date, even if it doesn't conflict because the master branch has newer commits than what the PR compare branch is based on. Just needs to be flipped on in the settings.

**Comment by andrewthetechie** [comment]
I think this has all been taken care of at this point. Our current failures  :( are due to another issue.

#closeit
