### ISSUE TITLE
send_stream_request() Is undefined for Hipchat Backend 

### ISSUE THREAD

**Issue by bradpayne** [errbotio/errbot#1156]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [X ] Suggesting a new feature

### I am running...

* Errbot version: 5.1.3
* OS version: Mac OS 10.12
* Python version: 3.6
* Using a virtual environment: yes

### Issue description
send)stream_request() is undefined in the Hipchat backend like it is in the Slack backend. A work around exists (https://gist.github.com/bdclark/0cbadce5816b6ab10eb2, https://www.hipchat.com/docs/apiv2/method/share_file_with_room) by it is not in the same style of using streams and should be added to Hipchat.py

**Comment by GenPage** [comment]
Can be closed due to Merged PR ^ 

In the future @bradpayne, you can help auto-close issues by including the issue in the commit msg. https://help.github.com/articles/closing-issues-using-keywords/
