### ISSUE TITLE
cant exactly quit

### ISSUE THREAD

**Issue by xzGithu** [errbotio/errbot#1159]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [X ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version:5.1.3
* OS version: CentOS6.9
* Python version: 3.4.7
* Using a virtual environment: no

### Issue description
I write a new backend. when I send "shutdown --confirm", It just stat at Process exiting, but cant quit back to the shell.
![image](https://user-images.githubusercontent.com/24711679/36057952-12b25038-0e51-11e8-9191-5f68b8876349.png)

**Comment by sijis** [comment]
I believe that has always happened (I may be wrong). Does `Ctrl + c` work? That's what I use to kill it when in Test backend.

**Comment by xzGithu** [comment]
yes,the  Ctrl + c works for it

**Comment by xzGithu** [comment]
it caused by a threading.Timer func in my backend
