### ISSUE TITLE
ACCESS_CONTROLS aren't working

### ISSUE THREAD

**Issue by Vamshi99** [errbotio/errbot#1161]
### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version:
* OS version:
* Python version: 3.2.2 
* Using a virtual environment: yes
* Backend: Gitter

### Issue description

Though I am using some rules in ACCESS_CONTROLS, they aren't working.
```
ACCESS_CONTROLS = {'render test': {
    'allowrooms': ('test')},
    'Someclass:*': {'allowprivate': False}}
```
### Steps to reproduce

In case of a bug, please describe the steps we need to take in order to reproduce your issue.
If you cannot easily reproduce the issue please let us know and provide as much information as you can which might help us pinpoint the problem.

### Additional info

If you have any more information, please specify it here.

**Comment by sijis** [comment]
Could you please describe what in the `ACCESS_CONTROLS` is not working? Were you trying to specifically allow/deny a command?

**Comment by Vamshi99** [comment]
The configurations mentioned above(allowrooms and allowprivate) aren't working.

**Comment by GenPage** [comment]
@Vamshi99 is there a reason the controls are defined within `'render test'`? That is not a valid ACL

**Comment by Vamshi99** [comment]
@GenPage I want to limit usage to test commands to test room only, so I used it. Why is that not a valid ACL?

**Comment by GenPage** [comment]
because the cmd_str is looks for needs to be in this format:

```
cmd_str = "{plugin}:{command}".format(
            plugin=f.__self__.name,
            command=cmd,
        )
```

`render test` is not valid, it would need to be `render:test`

**Comment by sijis** [comment]
If this is not in the docs, we should probably add/update to include examples on using acls.

**Comment by GenPage** [comment]
@sijis Actually, you're right. Doing a brief look through the docs, I don't see any examples.

**Comment by Vamshi99** [comment]
@GenPage, I don't we should write `Plugin: command`, if we just write like `command` it will change itself as `*: command`, see the code in the link you provided. Also see config template for reference.
https://github.com/errbotio/errbot/blob/master/errbot/config-template.py#L286

**Comment by GenPage** [comment]
If you want to put just `command`, for example `test`, then yes it will check for a test commands across each plugin if it exists.

**Comment by liangyungong** [comment]
@Vamshi99 Do you have ACL plugin enabled?

**Comment by Vamshi99** [comment]
@liangyungong We used `AUTOINSTALL_DEPS=True`, so need of that I guess.

**Comment by nvzard** [comment]
@GenPage what should the correct way be?
```
ACCESS_CONTROLS = {'Utils:render*': {
    'allowrooms': ('test')},
    'Someclass:*': {'allowprivate': False}}
```

You suggested to use `render:test` but shoudn't we use `Utils:render*` instead as `render test` is a botcomand for the core plugins `Utils`. Please correct me if I am wrong.

**Comment by gbin-argo** [comment]
The command name is render_test maybe ?

**Comment by sijis** [comment]
There were 2 things in play here:
1. the command is `render_test` [See botcmd](https://github.com/errbotio/errbot/blob/master/errbot/core_plugins/utils.py#L70)
2. the room name needs the `#` hashtag

The actual used config
```
ACCESS_CONTROLS = {
    'render_test': {
        'allowrooms': ('#test')
    },
    'Someclass:*': {
        'allowprivate': False
    }
}
```

The results
```
[#testroom/sijis ➡ #testroom] >>> !render test
You're not allowed to access this command from this room

[#testroom/sijis ➡ #testroom] >>> !room join #test
Joined the room #test.

[#test/sijis ➡ #test] >>> !render test
Normal Markdown:
image: http://errbot.io/_static/errbot.png
 link: This is a link (http://www.errbot.io).
...
```
