### ISSUE TITLE
Predifined commands in telegram are not regonised

### ISSUE THREAD

**Issue by SvenNederhoff** [errbotio/errbot#1174]
### I am...

* Reporting a bug

### I am running...

* Errbot version: latest commit
* OS version: Ubuntu 16.04 LTS
* Python version: 3.5
* Using a virtual environment: yes

### Issue description

Bot doesn't accept command's followed by its username,
like `/whoami@botusername` will return in `Command "whoami@botusername" not found.`

### Steps to reproduce

add bot to room and add predefined commands

### Additional info

created a pullrequest for it : #1173

**Comment by sijis** [comment]
PR went stale. Feel free to reopen PR when ready.
