### ISSUE TITLE
Feature Feedback: Slack Backend Additions

### ISSUE THREAD

**Issue by TheJokersThief** [errbotio/errbot#1181]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Suggesting a new feature

### I am running...

* Errbot version: 5.1.3
* OS version: Ubuntu 16.04
* Python version: 3.6
* Using a virtual environment: yes

### Issue description

I've been working on a ChatOps bot for work and we've made a couple improvements to the Slack backend that currently sit as their own little utils package. I've made this ticket to determine whether you'd be okay with me contributing them upstream via PR before I spend time working them into the core. So if you'd like me to put something together as a base to take suggestions, please let me know.

The specific features:
* Update a message/card
* Send multiple cards at once
* A side-effect of integrating both of the above is that sending messages returns a `Message` object which I've found useful for keeping track of responses (and for updating text)

If these don't fit the ethos or style of the bot, no worries, just thought I'd ask before I committed time to the PR :)

**Comment by GenPage** [comment]
@TheJokersThief Go ahead and open a PR and we can take it from there :) Sounds interesting

**Comment by TheJokersThief** [comment]
Awesome, I'll get a PR sorted and see what ye think :)
