### ISSUE TITLE
Plugin dependencies are not working while testing

### ISSUE THREAD

**Issue by aashraybhandar1** [errbotio/errbot#1185]
### I am...

  ✅  Reporting a bug

### Issue description

Errbot raises an error that a plugin dependency is not expressed as a dependency in .plug file, even though it has.This is happening when the dependent plugin is used for mocking purposes while testing.

### Additional info
Similar to  https://github.com/errbotio/errbot/issues/1086

**Comment by sijis** [comment]
I don't believe there is enough information here to address the issue noted.

I will close this but please reopen if more information or examples can be provided.
