### ISSUE TITLE
warn_admins throws exception in Slack if an admin has notifications Snoozed

### ISSUE THREAD

**Issue by oz-linden** [errbotio/errbot#1191]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [X] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.2
* OS version: Debian Jessie
* Python version: 3.5.5
* Using a virtual environment: yes

### Issue description

In one of my plugins, I attempt to alert the admin whenever the bot connects by:

    def callback_connect(self):
        self.warn_admins("Connected " + self.version)

If this happens when an admin has suppressed notifications (Slack Snooze), an exception is thrown in the Slack backend (see below).

### Steps to reproduce

1. Add a callback_connect as above.
2. Snooze notifications in Slack, but remain connected.
3. Start the bot.

### Additional info

{"error_type": "KeyError", "error_message": "'bot_id'", "msg": "message event handler raised an exception", "level": "ERROR", "time": "2018-04-25T05:23:54.682733Z", "traceback": "KeyError
Python 3.5.5: /Users/oz/_config/virtualenv/botll/bin/python3.5
Wed Apr 25 05:23:54 2018

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /Users/oz/_config/virtualenv/botll/lib/python3.5/site-packages/errbot/backends/slack.py in _dispatch_slack_message(self=<yapsy_loaded_plugin_Slack_0.SlackBackend object>, message={'channel': 'D597B3NMR', 'dnd_suppressed': True, 'event_ts': '1524648234.000340', 'is_ephemeral': True, 'subtype': 'bot_message', 'text': 'oz has snoozed notifications. Send one anyway? <...966959978/1524648234.000379|Send notification>\\u200b\\u200b\\u200b', 'ts': '1524648234.000379', 'type': 'message', 'user': 'USLACKBOT', 'username': 'slackbot'})
  418         try:
  419             log.debug(\"Processing slack event: %s\" % message)
  420             event_handler(message)
  421         except Exception:
  422             log.exception(\"%s event handler raised an exception\" % event_type)
event_handler = <bound method SlackBackend._message_event_handle...yapsy_loaded_plugin_Slack_0.SlackBackend object>>
message = {'channel': 'D597B3NMR', 'dnd_suppressed': True, 'event_ts': '1524648234.000340', 'is_ephemeral': True, 'subtype': 'bot_message', 'text': 'oz has snoozed notifications. Send one anyway? <...966959978/1524648234.000379|Send notification>\\u200b\\u200b\\u200b', 'ts': '1524648234.000379', 'type': 'message', 'user': 'USLACKBOT', 'username': 'slackbot'}

 /Users/oz/_config/virtualenv/botll/lib/python3.5/site-packages/errbot/backends/slack.py in _message_event_handler(self=<yapsy_loaded_plugin_Slack_0.SlackBackend object>, event={'channel': 'D597B3NMR', 'dnd_suppressed': True, 'event_ts': '1524648234.000340', 'is_ephemeral': True, 'subtype': 'bot_message', 'text': 'oz has snoozed notifications. Send one anyway? <...966959978/1524648234.000379|Send notification>\\u200b\\u200b\\u200b', 'ts': '1524648234.000379', 'type': 'message', 'user': 'USLACKBOT', 'username': 'slackbot'})
  499                 msg.frm = SlackBot(
  500                     self.sc,
  501                     bot_id=event['bot_id'],
  502                     bot_username=event.get('username', '')
  503                 )
bot_id undefined
event = {'channel': 'D597B3NMR', 'dnd_suppressed': True, 'event_ts': '1524648234.000340', 'is_ephemeral': True, 'subtype': 'bot_message', 'text': 'oz has snoozed notifications. Send one anyway? <...966959978/1524648234.000379|Send notification>\\u200b\\u200b\\u200b', 'ts': '1524648234.000379', 'type': 'message', 'user': 'USLACKBOT', 'username': 'slackbot'}
KeyError: 'bot_id'

**Comment by andrewthetechie** [comment]
https://github.com/errbotio/errbot/blob/master/errbot/backends/slack.py#L507 looks like the source of the problem - messages coming from "Slackbot" don't have a bot ID. 

I'll see if I can put together a fix for this.

**Comment by andrewthetechie** [comment]
@oz-linden https://github.com/errbotio/errbot/pull/1195 should fix this

**Comment by andrewthetechie** [comment]
@oz-linden https://github.com/errbotio/errbot/pull/1195#issuecomment-388589673 This was fixed during a Pycon hack-session by @gbin

**Comment by sijis** [comment]
This should be closed, right?

**Comment by GenPage** [comment]
Yup https://github.com/errbotio/errbot/commit/64a9ea59fcb18cda05dd3969b69bb7255cdf276f

**Comment by andrewthetechie** [comment]
#closeit
