### ISSUE TITLE
Socket error connecting to Cisco Jabber

### ISSUE THREAD

**Issue by derchrisuk** [errbotio/errbot#1192]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [x] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.2.0
* OS version: OSX 10.12.6
* Python version: 3.6.5
* Using a virtual environment: no

### Issue description

I'm trying to get errbot to connect to a Cisco Jabber.
Entering all the details in the config, I get this error:

```
18:03:18 DEBUG    sleekxmpp.features.featur Starting TLS
18:03:18 INFO     sleekxmpp.xmlstream.xmlst Negotiating TLS
18:03:18 INFO     sleekxmpp.xmlstream.xmlst Using SSL version: TLSv1
18:03:18 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: socket_error
18:03:18 ERROR    sleekxmpp.xmlstream.xmlst Socket Error #2: No such file or directory
18:03:18 DEBUG    sleekxmpp.xmlstream.xmlst reconnecting...
18:03:18 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: session_end
```

### Steps to reproduce

This error is with the following version settings from

https://github.com/fritzy/SleekXMPP/issues/477

```
pyasn1==0.3.6
pyasn1-modules==0.1.5
sleekxmpp==1.3.3
```

### Additional info

If I use `XMPP_CA_CERT_FILE = None` the I get the following

```
18:08:57 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: socket_error
18:08:57 ERROR    sleekxmpp.xmlstream.xmlst Socket Error #9: Bad file descriptor
```

**Comment by mattpoel** [comment]
Had the same error message when trying to get errbot running with HipChat Server. Using the `XMPP_CA_CERT_FILE = None` setting with the following package versions fixed it for me:

```
pyasn1==0.3.7
pyasn1-modules==0.1.5
sleekxmpp==1.3.2
```

**Comment by sijis** [comment]
Solution seems viable.
If issue persist open new issue with new version.
