### ISSUE TITLE
How to send chinese characters?

### ISSUE THREAD

**Issue by NMC-DAVE** [errbotio/errbot#1193]
Hi,
    I want to send chinese characters with errbot + slack. But the message is messy. For example:

```
# -*- coding: utf-8 -*-
from errbot import BotPlugin, botcmd, re_botcmd
class Example(BotPlugin):
    @botcmd  # flags a command
    def tryme(self, msg, args):  # a command callable with !tryme
        return '您好!'  # This string format is markdown.
```

And in slack, the message turn to:
```
!tryme
鎮ㄥソ!
```

So, how can I fix this? Thanks very much!

Dave

**Comment by gbin** [comment]
Does it work with the text backend?

**Comment by NMC-DAVE** [comment]
With the text backend, I got the same thing:

[31m[@kan ➡ @errbot] [36m>>> [0m!tryme
鎮ㄥソ!

**Comment by gbin** [comment]
Can you start the bot under debugger and see where utf-8 is failing us?

**Comment by sijis** [comment]
I'm not able to reproduce this issue in the latest release.

```
    @botcmd  # flags a command
    def issue1193(self, msg, args):  # a command callable with !tryme
        return '您好!'  # This string format is markdown.
```
Result
```
[@sijis ➡ @errbot] >>> !issue1193
您好!
```

If this persist, please reopen the issue.
