### ISSUE TITLE
ChatRoom join unexpected keyword argument 'username'

### ISSUE THREAD

**Issue by derchrisuk** [errbotio/errbot#1201]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.2.0
* OS version: OSX 10.12.6
* Python version: 3.6.5
* Using a virtual environment: no

### Issue description

I have setup errbot with the Cisco Spark backend.
Created a Spark bot, and trying to get it to join a room id.
Entered the bot token, it is able to join the service.
Once I enter a room id to join, I get the following:

````
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/errbot/core_plugins/chatRoom.py", line 20, in callback_connect
    self._join_room(room)
  File "/usr/local/lib/python3.6/site-packages/errbot/core_plugins/chatRoom.py", line 34, in _join_room
    self.query_room(room).join(username=self.bot_config.CHATROOM_FN, password=password)
TypeError: join() got an unexpected keyword argument 'username'
````

### Steps to reproduce

* Install Cisco Spark backend
* register bot
* config bot token
* add room id to join

### Additional info

This is using the Cisco Spark backend from here: https://github.com/panholt/err-backend-cisco-spark
I also opened an issue there as I'm not sure if this is a backend or errbot core issue.

**Comment by andrewthetechie** [comment]
Can you test that backend with https://github.com/errbotio/err-backend-tester/ ?

This is a simple plugin testing all the assumptions for a backend, if the backend doesn't pass it, it is probably breaking a contract with errbot (i.e. the issue is in the backend)

**Comment by sijis** [comment]
This seems to be an issue with that backend. I'm unable to reproduce in text backend.
