### ISSUE TITLE
Errbot should fail if git binary is not present

### ISSUE THREAD

**Issue by sijis** [errbotio/errbot#1206]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug

### I am running...

* Errbot version: Latest
* OS version: Fedora 28
* Python version:  3
* Using a virtual environment: yes

### Issue description

Installing a plugin fails silently if `git` binary is not present on the system.

### Steps to reproduce
* Install errbot
* ensure git is not installed
* run `errbot -T`, then try to install a plugin via `!repos install x`

### Additional info

This was brought up on gitter.im.

**Comment by andrewthetechie** [comment]
I'll take a look at this

**Comment by sijis** [comment]
This is no longer needed.
