### ISSUE TITLE
Hipchat backend throwing error on latest version of errbot

### ISSUE THREAD

**Issue by prasadvelidi** [errbotio/errbot#1217]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [x] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.2.0
* OS version: CentOS Linux release 7.4.1708 (Core)
* Python version: Python 3.4.8
* Using a virtual environment: yes

### Issue description
I am trying to use the Hipchat backend with a minimal configuration and when i bring up the bot, i am greeted with the following error on the log.

**LOG ENTRIES:**
..
08:25:13 DEBUG    sleekxmpp.thirdparty.stat  ==== TRANSITION disconnected -> connected
08:25:13 DEBUG    sleekxmpp.xmlstream.xmlst Starting HANDLER THREAD
08:25:13 DEBUG    sleekxmpp.xmlstream.xmlst Loading event runner
08:25:13 DEBUG    sleekxmpp.xmlstream.xmlst SEND (IMMED): <stream:stream to='chat.hipchat.com' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client' xml:lang='en' version='1.0'>
08:25:13 DEBUG    sleekxmpp.xmlstream.xmlst RECV: <stream:stream from="chat.hipchat.com" version="1.0" id="2032f7b5ec320182">
08:25:13 DEBUG    sleekxmpp.xmlstream.xmlst RECV: <stream:features xmlns="http://etherx.jabber.org/streams"><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"><required /></starttls></stream:features>
08:25:13 DEBUG    sleekxmpp.xmlstream.xmlst SEND (IMMED): <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"><required /></starttls>
08:25:13 DEBUG    sleekxmpp.xmlstream.xmlst RECV: <proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls" />
08:25:13 DEBUG    sleekxmpp.features.featur Starting TLS
08:25:13 INFO     sleekxmpp.xmlstream.xmlst Negotiating TLS
08:25:13 INFO     sleekxmpp.xmlstream.xmlst Using SSL version: TLS 1.0
**08:25:13 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: socket_error**
**08:25:13 ERROR    sleekxmpp.xmlstream.xmlst Socket Error #2: No such file or directory**
08:25:13 DEBUG    sleekxmpp.xmlstream.xmlst reconnecting...
08:25:13 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: session_end
08:25:13 DEBUG    sleekxmpp.xmlstream.xmlst SEND (IMMED): </stream:stream>
08:25:13 INFO     sleekxmpp.xmlstream.xmlst Waiting for </stream:stream> from server
08:25:16 DEBUG    errbot.backends.xmpp      Trigger disconnect callback
08:25:16 INFO     errbot.core               Disconnect callback, deactivating all the plugins.
08:25:16 DEBUG    errbot.backends.xmpp      Trigger shutdown
08:25:16 DEBUG    errbot.storage            Closed storage 'hipchat_backend'
08:25:16 INFO     errbot.plugin_manager     Shutdown.
08:25:16 DEBUG    errbot.storage            Closed storage 'core'
08:25:16 INFO     errbot.plugin_manager     Bye.
08:25:16 DEBUG    errbot.storage            Closed storage 'repomgr'
..

### Steps to reproduce

**CONFIGURATION:**
import logging
BACKEND = 'Hipchat'
BOT_DATA_DIR = r'/root/chatbot/data'
BOT_EXTRA_PLUGIN_DIR = r'/root/chatbot/plugins'
BOT_LOG_FILE = r'/root/chatbot/errbot.log'
BOT_LOG_LEVEL = logging.DEBUG
BOT_IDENTITY = {
    'username' : 'xxxxxxxxxxxxxx@chat.hipchat.com',
    'password' : 'xxxxxxxxxxx',
    'token'    : 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
    # 'verify': False
}

### Additional info

I have tried setting XMPP_CA_CERT_FILE = None and Verify = False too. Didn't work.
I have tried downgrading sleekxmpp from v1.3.3 to v.1.3.2 as some posts suggested. Didn't work.

Please suggest suitable course of action to rectify this issue.

**Comment by zoni** [comment]
Could you show me the log entries you receive when you have `XMPP_CA_CERT_FILE = None` set in the config?

**Comment by prasadvelidi** [comment]
Ref: https://github.com/errbotio/errbot/issues/1144

The version suggestion according to the update in the above issue helped. Its working post downgrading the versions of the following pip modules.

sleekxmpp==1.3.2, pyasn1==0.3.7 and pyasn1-modules==0.1.5

Initially I have not downgraded pyasn1 and pyasn1-modules, which made it not work. But now its working after downgrading all mentioned above.

At least, if the same is mentioned on the documentation, it would help lot of new users setting up Hipchat backend without spending more time figuring out.

Appreciate your prompt and immediate reply Zoni.

**Comment by prasadvelidi** [comment]
Is there any official recommendation regarding versions of these packages ? Any other recent versions of the modules working with hipchat backend ?

**Comment by zoni** [comment]
> Initially I have not downgraded pyasn1 and pyasn1-modules, which made it not work. But now its working after downgrading all mentioned above.

I had a suspicion it might be that, thanks for confirming and glad to hear you found a working combination.

Unfortunately my earlier comment in https://github.com/errbotio/errbot/issues/1144#issuecomment-353404425 still applies, these are bugs in the underlying libraries we use so not something we can directly fix.

Perhaps we could add a warning on http://www.errbot.io/en/latest/user_guide/configuration/hipchat.html linking to #1144 given the time it's taking these other projects to fix this.

**Comment by prasadvelidi** [comment]
> Unfortunately my earlier comment in #1144 (comment) still applies, these are bugs in the underlying libraries we use so not something we can directly fix.
Thank you for confirming once again.

> Perhaps we could add a warning on http://www.errbot.io/en/latest/user_guide/configuration/hipchat.html linking to #1144 given the time it's taking these other projects to fix this.
Thank you for taking initiative to add a note/warning about this on documentation. It certainly helps a lot of people like me.
