### ISSUE TITLE
errbot not starting automatically after a reboot on CentOS 7

### ISSUE THREAD

**Issue by mattpoel** [errbotio/errbot#1230]
### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.2.0
* OS version: CentOS Linux release 7.5.1804 (Core)
* Python version: 3.5.2
* Using a virtual environment: yes

### Issue description

I created the errbot.service for systemd as described in the [documentation](http://errbot.io/en/latest/user_guide/setup.html#starting-the-daemon) and activated the service with:

```
systemctl enable errbot
```

But errbot didn't start automatically after a reboot. I had to start errbot manually with ```systemctl start errbot```.

After modifying the errbot.service file based on another service, reboots are working fine for me now:

```
[Unit]
Description=Start Errbot chatbot
After=syslog.target network.target
Before=shutdown.target reboot.target halt.target

[Service]
Environment="LC_ALL=en_US.UTF-8"
ExecStart=/path/to/errbot/virtualenv/bin/errbot --config /path/to/errbot/config.py
WorkingDirectory=/path/to/errbot/
User=errbot
Restart=always
KillSignal=SIGINT

[Install]
WantedBy=multi-user.target
```

Just want to provide my systemd errbot configuration as a reference.

### Steps to reproduce

* configure errbot as a systemd-service on CentOS 7
* enable the service with ```systemctl enable errbot```
* perform a ```reboot```
* check the status of errbot ```systemctl status errbot``` => not running

**Comment by sijis** [comment]
A quick diff between the suggestion here and our docs show
```
--- <unnamed>
+++ <unnamed>
@@ -1,6 +1,7 @@
 [Unit]
 Description=Start Errbot chatbot
-After=network.service
+After=syslog.target network.target
+Before=shutdown.target reboot.target halt.target
 
 [Service]
 Environment="LC_ALL=en_US.UTF-8"
@@ -9,3 +10,6 @@
 User=errbot
 Restart=always
 KillSignal=SIGINT
+
+[Install]
+WantedBy=multi-user.target
```

My guess is that the `[Install]` is really the only necessary change.
