### ISSUE TITLE
Make a new feature to do github mundane tasks on the slack channel.

### ISSUE THREAD

**Issue by Dhiraj240** [errbotio/errbot#1234]
### I am...

* [x] Suggesting a new feature
* [x] Requesting help with running my bot

### I am running...

* Errbot version:new version
* OS version:Windows 8.1
* Python version: 3.7
* Using a virtual environment: no

### Issue description

Please describe your bug/feature/problem here.
I want to add feature where errbot can be used on slack to assign and create issue in the slack itself.There admin have the right to assign it and any contributor can add issue from slack itself.Also the invitation to the organisation on github can be send by the admin on the slack itself.

### Steps to reproduce

1.I need to setup slack in the bot itself using configure template.
2.I need some documentation or any related link to do the above tasks.

### Additional info

I just know configuring the config.py(template)

**Comment by gbin** [comment]
Hi,
You'll have to develop an Errbot plugin for that. Please follow the development guide for this.

Thanks!
