### ISSUE TITLE
Format output

### ISSUE THREAD

**Issue by Stevieag** [errbotio/errbot#1243]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ *] Here about something else

### I am running...

* Errbot version: 5.2.0
* OS version: LinuxMint 19 tara
* Python version: 3+
* Using a virtual environment: no

### Issue description

I am wishing to output a returned json to a table or prettier format

in general i have lots of bot commands running and generally have hacked the output to be pretty or code...
I am looking to output similar to those in the !render test (tables, bold, colours etc) or !help table
I am looking for how to achieve this and cant find documention to help!!!

is there a direction i could be guided to?

**Comment by sijis** [comment]
Are you looking for something like this http://errbot.io/en/latest/user_guide/plugin_development/messaging.html#templating? With a template you should be able to format the output however you wish.

Some of the core templates we use in the outputs are here: https://github.com/errbotio/errbot/tree/master/errbot/core_plugins/templates. You can use those as inspiration.

**Comment by Stevieag** [comment]
Cheers, that will help
