### ISSUE TITLE
No way to set testbot fullname

### ISSUE THREAD

**Issue by lingfish** [errbotio/errbot#1247]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [x] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.2.0
* OS version: Debian Stretch
* Python version: 3.6.4
* Using a virtual environment: yes

### Issue description

Try as I might, I cannot engineer a way to set the testbot fullname (and I guess other things that `TestPerson` seems to accept.)

`frm` seems to get set via BOT_ADMINS, which obviously doesn't carry anything other than username.

Any suggestions?

**Comment by sijis** [comment]
Does the `CHATROOM_FN` config option not do what you expect?
https://github.com/errbotio/errbot/blob/master/errbot/config-template.py#L216

**Comment by sijis** [comment]
This works:
```
a = TestPerson("foo", fullname='sijis')
assert getattr(a, 'fullname') == 'sijis'
```
