### ISSUE TITLE
Certificate of https://repos.errbot.io/ expired. Unable to install new plugins.

### ISSUE THREAD

**Issue by malt3** [errbotio/errbot#1249]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.2.0
* OS version: Arch Linux 4.17.6-1-ARCH
* Python version: 3.7.0
* Using a virtual environment: yes

### Issue description

The certificate of https://repos.errbot.io/  expired on 24th of August 2018. This server provides the plugin repo that is loaded whenever a new package is installed from https://repos.errbot.io/repos.json 

### Steps to reproduce

Install a repo using the following command:

```
!repos install [repo_name]
```
e.g.:
```
< !repos install https://github.com/drsm79/err-xkcd
> Installing https://github.com/drsm79/err-xkcd...
> Computer says nooo. See logs for details:
> b'repo_index'
```

### Additional info

Output of errbot:
```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/malte/.virtualenvs/errbot-ve/lib/python3.7/site-packages/errbot/repo_manager.py", line 120, in index_update
    with urlopen(url=source, timeout=10) as request:  # nosec
  File "/usr/lib64/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib64/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1045)>
11:15:10 ERROR    errbot.core               An error happened while processing a message ("!repos install https://github.com/drsm79/err-xkcd"): Traceback (most recent call last):
  File "/usr/lib64/python3.7/shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: 'repo_index'
```

**Comment by marksull** [comment]
I've seen the same issue today. As a workaround looks like you can override this in the config file with the following using http only. Will test tomorrow.....

BOT_PLUGIN_INDEXES = 'http://repos.errbot.io/repos.json'

**Comment by sijis** [comment]
@gbin @gbin-argo ping!

**Comment by mkj28** [comment]
cert still expired
<img width="1012" alt="2018-09-28_0037" src="https://user-images.githubusercontent.com/2279299/46194590-c6cd9b80-c2b6-11e8-981d-9e597af9d764.png">

**Comment by demonbob** [comment]
Is this going to be fixed or Is this project abandoned?

**Comment by gbin** [comment]
I gonna fix this, sorry it took me so long.

**Comment by gbin** [comment]
Fixed, bug me back before jan 2. Thanks so much for your patience!

**Comment by mkj28** [comment]
thanks @gbin !!

**Comment by komodo472** [comment]
@gbin the cert has expired again.

**Comment by muppeth** [comment]
ping @gbin Happy New SSL Year! :D

**Comment by gbin** [comment]
Gonna do it sorry guys, it is crazy at work :(

**Comment by pmoranga** [comment]
is it happenign again ?

> curl -v -k  https://repos.errbot.io/
*   Trying 172.217.17.147...
* TCP_NODELAY set
* Connected to repos.errbot.io (172.217.17.147) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=repos.errbot.io
*  start date: Jan 12 15:07:27 2019 GMT
***  expire date: Apr 12 15:07:27 2019 GMT**

**Comment by jseiser** [comment]
@gbin

**Comment by sijis** [comment]
Its fixed.

**Comment by nicholasamorim** [comment]
This seems to be happening again
