### ISSUE TITLE
Bakend abandoned or link not working.

### ISSUE THREAD

**Issue by fernand0** [errbotio/errbot#1250]
The backend link https://github.com/SShrike/err-backend-matrix does not work.
Maybe the documentation should be updated.
The other links seem to be working ok.
Thanks!

**Comment by sijis** [comment]
There is a script that updates that wiki page. I thought it was run weekly but maybe I was wrong.
@gbin Is that script still running automatically?

**Comment by gbin-argo** [comment]
It is a manual process, I'll update it asap

**Comment by sijis** [comment]
I no longer see the link on the [wiki](https://github.com/errbotio/errbot/wiki), so updates have been done.

**Comment by mandrillmaze** [comment]
http://errbot.io/en/latest/features.html
Still appears here.
