### ISSUE TITLE
No event handler available for user_typing, ignoring this event

### ISSUE THREAD

**Issue by mukulmeister** [errbotio/errbot#1252]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [X ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version:5.2.0 
* OS version:windows 10
* Python version: 3.6
* Using a virtual environment: yes/no : yes

### Issue description

i am getting below message can someone help.

"No event handler available for user_typing, ignoring this event"

Can someone also advise how to update plugin(code) without stopping errbot, as of now i have o stop make changes and then start again.

Please describe your bug/feature/problem here.
The more information you can provide, the better.

### Steps to reproduce

In case of a bug, please describe the steps we need to take in order to reproduce your issue.
If you cannot easily reproduce the issue please let us know and provide as much information as you can which might help us pinpoint the problem.

### Additional info

If you have any more information, please specify it here.

**Comment by GenPage** [comment]
@mukulmeister Can you provide more information? What you are trying to accomplish?

There is no way to change plugin code without stopping errbot with a restart.

**Comment by andrewthetechie** [comment]
#closeit

**Comment by mukulmeister** [comment]
Hey the issue is whenever we have to stop the bot we keep pressing ctrl + c
to stop, however it won't stop and then we hav to write omething on the
chat(slack) to get it stopped.

**Comment by andrewthetechie** [comment]
@mukulmeister can you please open a new issue for that. Including any error logs, your errbot version, your platform, and clear steps to reproduce have a better chance to getting it looked at.

**Comment by sijis** [comment]
If `!repos install` and `!repos update` is used, you should be able to update the plugin without requiring to stop/start the bot.
http://errbot.io/en/latest/user_guide/administration.html#installing-plugins
