### ISSUE TITLE
Links in Slack channel broken

### ISSUE THREAD

**Issue by pjz** [errbotio/errbot#1258]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.2.0
* OS version: Ubuntu 18.04.1
* Python version: 3.6
* Using a virtual environment: yes

### Issue description

Links my plugin constructs in markdown don't surface correctly in Slack channels.  They work fine in direct chat with the bot, however.

### Steps to reproduce

I have code that looks like:
```python
    @re_botcmd(pattern=r"wiki:(\S+)( |$)", prefixed=False, flags=re.IGNORECASE, matchall=True)                                                                   
    def listen_for_wiki_links(self, msg, matches):                                                                                                               
        """Provide a link to a wiki page"""                                                                                                                      
        def linkify(page):                                                                                                                                       
            return "[" + page + "](" + WIKI_BASE + page + ")"                                                                                                    
        links = [ linkify(m.group(1)) for m in matches ]                                                                                                         
        return f"{msg.frm} mentioned the wiki page(s): " + ' - '.join(links)       

```

Which I thought was fairly simple.  And indeed, in chat directly to my bot, the result is the desired:

    me> mention wiki:PageOne
    bot> @pj mentioned the wiki page(s): PageOne

(with the word 'PageOne' correctly linkified)
But in a channel, it looks like:

    me> mention wiki:PageOne
    bot> *BOTCHAT/PJ MENTIONED THE WIKI PAGE(S): WZXHZDK:20HTTPS://WIKI.EXAMPLE.COM/PAGEONE%7CPAGEONEWZXHZDK:21*

So:

  1. Why is it all caps?
  2. how do I make it an actual link?

**Comment by sijis** [comment]
Is this still an issue? If so, could you try the following:
* Run `!render test`
* Use a [template](http://errbot.io/en/latest/user_guide/plugin_development/messaging.html#templating) for the botcmd

**Comment by pjz** [comment]
We gave up on this, and eventually, Slack, so, unknown.
