### ISSUE TITLE
Broken links in wiki

### ISSUE THREAD

**Issue by l13t** [errbotio/errbot#1278]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [x] Here about something else

### I am running...

* Errbot version:
* OS version:
* Python version: 
* Using a virtual environment: yes/no

### Issue description

There're 2 broken links in wiki:
* https://github.com/btotharye/err-mycroft
* https://github.com/btotharye/err-homeassistant

Those 2 repos are not accessible at the moment and pages with them return 404.

**Comment by l13t** [comment]
Small update. Actually all plugins from this person are removed atm from github.
Those are:
* https://github.com/errbotio/errbot/wiki#76---rasa
* https://github.com/errbotio/errbot/wiki#119---mycroft
* https://github.com/errbotio/errbot/wiki#120---homeassistant
* https://github.com/errbotio/errbot/wiki#220---example
* https://github.com/errbotio/errbot/wiki#245---example
* https://github.com/errbotio/errbot/wiki#269---psirt
* https://github.com/errbotio/errbot/wiki#270---sparkbot

**Comment by sijis** [comment]
Closing, as wiki page is no longer loading, https://github.com/errbotio/errbot/issues/1407.

**Comment by pintman** [comment]
All links in the wiki page point to the same repo
