### ISSUE TITLE
Add support for command aliases

### ISSUE THREAD

**Issue by alpinweis** [errbotio/errbot#1279]
It'd be nice to have support for command aliases that would allow use of shortcuts for long commands (e.g. `!ls`, `!list`, or `!metrics`, `'!performance_metrics`) or use synonyms for commands with the same meaning (e.g. `!stop`, `!cancel`)

**Comment by andrewthetechie** [comment]
#feature

**Comment by sijis** [comment]
This can be accomplished using the plugin https://github.com/rroemhild/err-alias.
