### ISSUE TITLE
Investigate moving to Python git implementation to remove requirement of system python

### ISSUE THREAD

**Issue by andrewthetechie** [errbotio/errbot#1281]
### I am...

* [ ] Suggesting a new feature

### I am running...

n/a 
### Issue description

Currently, Errbot uses system git for its cloning of plugins. This lead to #1206. 

There are python implementations of git that could be used without requiring system git. https://github.com/FriendCode/gittle is a possible candidate. It is based on https://www.dulwich.io/

**Comment by sijis** [comment]
Removing that binary dependency, I think, would be a great actually.

In quickly looking, dulwitch appears more active than little.

On a separate note, I've always thought having plugins available via pypi would be awesome and avoid the whole git thing altogether. It's obvious a separate conversation.

**Comment by andrewthetechie** [comment]
There's another issue about trying to come up with a solution for packaging plugins via pypi I'm looking into.

**Comment by andrewthetechie** [comment]
I opened up #1296 to move us over to using dulwich rather than system git.

**Comment by andrewthetechie** [comment]
Closed now that #1296 is merged
