### ISSUE TITLE
Possible plugin name conflicts

### ISSUE THREAD

**Issue by alpinweis** [errbotio/errbot#1288]
### I am...

* [x] Reporting a _possible_ bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [x] Here about something else: 
   => Suggesting adding a Plugin name validation and/or a naming schema for Core Plugins

### I am running...

* Errbot version: 5.2.0
* OS version: macOS 10.13 High Sierra
* Python version: 3.7
* Using a virtual environment: yes

### Issue description

I had to issue a `!restart` from the Errbot channel in Slack. After it restarted I started getting this error:
```
Computer says nooo. See logs for details:
type object 'Utils' has no attribute 'my_method'
```
This was happening when I was  issuing a command that calls `my_method`.
Here `my_method` is a static method of my own `Utils(BotPlugin)` in my own module `utils.py` that I import in another plugin as `import utils` and use as `utils.Utils.my_method()`
I had to do a proper stop & start from the terminal to get Errbot back to normal.

It looked like there could be some race condition happening, as after doing a `!restart` it would only **sometimes** put Errbot in a bad state.

Upon further investigation, I discovered I might have a naming conflict.

This is my errbot folder structure:
```
errbot
  plugins
    myorg
      - utils.py
      - utils.plug
      - other.py
      - other.plug
```
where in `utils.plug` I have:
```
[Core]
Name = MyUtils
Module = utils
```
and in `utils.py` I have:
```
class Utils(BotPlugin):
  ...
```
It appears Errbot Core also has a plugin named `Utils`, a class `Utils(BotPlugin)` and a `utils.py` module. The only difference is that mine has `MyUtils` name in the plug file, but the same module name and class name.
When I was starting Errbot via the terminal `utils.Utils.my_method()` would **always** (or so it seemed) work fine. When I was doing a `!restart` from a channel though, it would **not always** work fine.
Could it be that it depends on the order the plugins (core and my own) are being loaded upon a `!restart` command - which I suspect is a random order - with one plugin overwriting the other one with the same name?

I had to completely rename my own `utils` module and class to something else, e.g. `tools.py`, `tools.plug`, `Tools(BotPlugin)`. After that I stopped seeing errors after doing a `!restart`.

Given these observations, I have a few suggestions:

1. It'd be nice if Errbot had some kind of a Plugin name validation to prevent name conflicts with the Core plugins. It's not immediately obvious to new users what names they should avoid when creating their own plugins, e.g. `Utils` is a pretty popular choice with many developers, which can potentially cause problems.

2. Alternatively, Errbot should use some unique names for its own Core plugins, like `ErrbotUtils`, `ErrbotHealth`, `ErrbotPlugins` etc., and Core modules, like `errbot_utils`, `errbot_health` etc., so that one could only do `import errbot_utils` or `import errbot.utils` and not `import utils`

**Comment by andrewthetechie** [comment]
https://github.com/errbotio/errbot/pull/1282 will help with this

**Comment by sijis** [comment]
I'm not saying its not possible but I cannot seem to reproduce this.
Could either of you attach a plugin or share a git that is able to reproduce this?

**Comment by sijis** [comment]
Fix already available in later in newer versions.
