### ISSUE TITLE
Issue printing a Code block and Quote block to Slack

### ISSUE THREAD

**Issue by alpinweis** [errbotio/errbot#1289]
### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.2.0
* OS version: macOS High Sierra
* Python version: 3.7
* Using a virtual environment: yes

### Issue description

I was trying to print out a piece of text as a tripple-backtick "```" wrapped `code block` to a Slack channel.
Given a **mydata** dict:
```
  return f"```{mydata}```"
```
Slack prints it out as if that was a bunch of strings each wrapped in a single-backtick, instead of a code block wrapped in triple-backticks.
The solution suggested in gitter was to escape each backtick:
```
  return f"\`\`\`{mydata}\`\`\`"
```
That worked.
I had the same issue when I tried to print out a `quote block` to a Slack channel.
```
  return f">>>{mydata}"
```
would ignore the right-arrows and print it out as a plain unquoted text.
The solution was to escape the arrows:
```
  return f"\>\>\>{mydata}"
```

It'd be nice if Errbot could handle the escaping if it's needed to support Slack message formatting rules.

**Comment by sijis** [comment]
Have you tried using a [template](http://errbot.io/en/latest/user_guide/plugin_development/messaging.html#templating) and see if that makes it simpler to do this?

**Comment by alpinweis** [comment]
In a template you'd also have to escape the backticks and right-arrows. Though this does not solve the main issue - having to escape those characters yourself. And it's not even obvious that those characters *should* be escaped. Everyone's initial expectation is that those combinations should work out of the box when printing to Slack, unescaped.

**Comment by drahamim** [comment]
This is still open and I am running into similar issues. Was there any resolution to this?

**Comment by nzlosh** [comment]
As it stands right now, the code splitting logic is quite simple and works for many cases but isn't really able to handle formatted message like Slack.  A message parser that is capable of implementing the same text processing as Slack would need to be implement for intelligent splitting of large blocks of text.  Such a task is non-trivial and I haven't seen/heard of any who's stepping up to take it on.

By default, errbot will spilt on 4096 characters.  The slack api claims to allow messages of 40k characters.  As a possible work around you could try to increase the maximum characters to send in a single message to avoid splitting for large text posts.

**Comment by sijis** [comment]
Increasing the message limit seems like the right workaround
https://github.com/errbotio/errbot/blob/41e80cb02610788bf506f84fd58216e55a495806/errbot/config-template.py#L335
