### ISSUE TITLE
Plugin stays deactivated

### ISSUE THREAD

**Issue by Jiehong** [errbotio/errbot#1294]
### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [X] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.2.0
* OS version: Alpine 3.8
* Python version: 3.7.2
* Using a virtual environment: no (docker)

### Issue description

I'm trying to have my Hello World plugin working, but it never gets activated, and DEBUG logging doesn't report any error.

### Steps to reproduce

Following the doc, I created a file named `hello_world.py`, with the following content:

```python
from errbot import BotPlugin, botcmd

class HelloWorld(BotPlugin):
    """Example 'Hello, world!' plugin for Errbot."""

    @botcmd
    def hello(self, msg, args):
        """Say hello to the world."""
        return "Hello, world!"
```

Alongside a plug file named `hello_world.plug`:

```
[Core]
Name = HelloWorld
Module = hello_world

[Python]
Version = 3+

[Documentation]
Description = Example "Hello, world!" plugin
```

When running errbot, I can see the following log line:

```
(...)
DEBUG    errbot.plugins.HelloWorld Logger for plugin initialized...
(...)
```

And a `!status plugin` shows this:

```
Yes I am alive...


    Plugins

┏━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Status ┃ Name                  ┃
┡━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━┩
│ A │ ACLs                  │
├────────┼───────────────────────┤
│ A │ Backup                │
├────────┼───────────────────────┤
│ A │ ChatRoom              │
├────────┼───────────────────────┤
│ A │ CommandNotFoundFilter │
├────────┼───────────────────────┤
│ A │ Flows                 │
├────────┼───────────────────────┤
│ A │ Health                │
├────────┼───────────────────────┤
│ D │ HelloWorld            │
├────────┼───────────────────────┤
│ A │ Help                  │
├────────┼───────────────────────┤
│ A │ Plugins               │
├────────┼───────────────────────┤
│ A │ TextCmds              │
├────────┼───────────────────────┤
│ A │ Utils                 │
├────────┼───────────────────────┤
│ D │ VersionChecker        │
├────────┼───────────────────────┤
│ C │ Webserver             │
└────────┴───────────────────────┘
 A = Activated, D = Deactivated, B = Blacklisted, C = Needs to be configured
 Load 0.11328125, 0.03955078125, 0.068359375
GC 0->590 1->5 2->2
```
(side node: the ascii table seems to have alignment issues with the Text backend, see?)

So, I run `!plugin activate HelloWorld`, and it says:

```
Plugin HelloWorld activated.
```

But if I re-run the status command, it stays in status `D`, and `!hello` is never a found command.

### Additional info

I run errbot in a docker, and the dockerfile contains the following:

```
FROM python:3.7-alpine

# Needed to compile python cryptography package, dependency of errbot
RUN apk add --no-cache --virtual .build-deps gcc build-base libffi-dev openssl-dev tzdata

COPY requirements.txt /err/

RUN pip install --upgrade pip &&\
    pip install -r /err/requirements.txt

COPY config.py /err/
COPY extra_plugins /err/extra_plugins/

RUN mkdir /var/lib/err

EXPOSE 3141 3142

WORKDIR /err

ENTRYPOINT ["errbot", "-c", "/err/config.py"]
```

**Comment by sijis** [comment]
It took me a bit to track it down.

The issue is with this line in `hello_world.plug`
```
Version = 3+
```
I set the logging to debug and then looked at the file. Within the output i noticed this
```
2019-02-02 07:30:54,284 WARNING  errbot.plugin_manager     Plugin HelloWorld has an invalid Version specified in section [Python]. The Version can only be 2, 2+ and 3
2019-02-02 07:30:54,284 ERROR    errbot.plugin_manager     HelloWorld failed python version check.
```

Setting that option to `Version = 3` fixed the problem.

**Comment by sijis** [comment]
Also, new plugin typically does not need to be activated. If it loads properly it would automatically be activated.

**Comment by Jiehong** [comment]
Indeed, this seems to be working now!

Thanks!
