### ISSUE TITLE
Plugin Failed to Start when Using __init__ 

### ISSUE THREAD

**Issue by dimasmamot** [errbotio/errbot#1326]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [x] Requesting help with running my bot
* [x] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.2
* OS version: ubuntu
* Python version: 3.6
* Using a virtual environment: yes

### Issue description

I Manage to activate my plugins with this config file and standard setup for plugins development, it's all running smooth and great, all command is working fine

yet, when I do a refactor to my code, I'm using `__init__` method to define variable & attribute to the bot class and the bot suddenly throwing this exception

> 2019-04-15 11:06:28,754 DEBUG    errbot.backends.slack     Escaped IDs event text: Some plugins failed to start during bot startup:
 File "/var/www/alison/fish-pill-bot/venv/lib/python3.6/site-packages/yapsy/PluginManager.py", line 538, in loadPlugins
    plugin_info.plugin_object = self.instanciateElementWithImportInfo(element, element_name, plugin_module_name, candidate_filepath)
  File "/var/www/alison/fish-pill-bot/venv/lib/python3.6/site-packages/yapsy/PluginManager.py", line 587, in instanciateElementWithImportInfo
    return self.instanciateElement(element)
  File "/var/www/alison/fish-pill-bot/venv/lib/python3.6/site-packages/errbot/plugin_manager.py", line 265, in instanciateElement
    return element(self.bot, name=self._current_pluginfo.name)

Do I missing a step to initialize the required attribut or initialization of configuration ?

### Steps to reproduce

implement` __init__` method to main BotPlugin class

### Additional info

with my config.py

> import logging
import os
BACKEND = 'Slack'
BOT_DATA_DIR = r'data'
BOT_EXTRA_PLUGIN_DIR = r'plugins_enabled'
BOT_LOG_FILE = r'errbot.log'
BOT_LOG_LEVEL = logging.DEBUG
BOT_ADMINS = ('@meadmin', )
BOT_IDENTITY = {
    'token' : 'mytoken',
}
BOT_ALT_PREFIXES = ('@alison',)
CHATROOM_PRESENCE = ()
BOT_ASYNC = True
BOT_ASYNC_POOLSIZE = 40

my normal `__init__` method
 
> def `__init__`(self):
        self.admin = 'root'
        self.channelID = ''
        self.debug_channel = "debug channel"
        self.dirname = os.path.dirname(`__file__`)
        self.hostip = ''
        self.jinja_environment = Environment(loader=FileSystemLoader('{}/templates/slack_messages'.format(self.dirname)), trim_blocks=True)    
        self.log = logging.getLogger("plugins.skye")
        self.tools = Tools(self)

Thanks!

**Comment by gbin** [comment]
Try to override self.activate() instead of init and don't forget to call
super().activate() at the end of its execution.

**Comment by dimasmamot** [comment]
works like a charm, thanks @gbin I'll close this issue as it is already solved, thanks
