### ISSUE TITLE
Discussion: Moving repos registry to Github

### ISSUE THREAD

**Issue by sijis** [errbotio/errbot#1329]
We occasionally get certificate errors with our plugin registry site (https://repos.errbot.io).

I'm wonder if it would be simpler for us to migrate it from appengine (i believe its hosted) to a Github subdomain (https://help.github.com/en/articles/setting-up-a-custom-subdomain). 
The domain currently only hosts a single file and we the script that generates that Json file is in the `tools/` directory.

I believe it can simplify our workflow, get more folks involved and relieve us of the burden of maintaining a cert and application.

What do you @errbotio/core think?

**Comment by jseiser** [comment]
The cert is currently expired, https://github.com/errbotio/errbot/issues/1249 so this would be a great idea.

**Comment by andrewthetechie** [comment]
I think this is a great idea.

**Comment by sijis** [comment]
This got moved in #1403.
