### ISSUE TITLE
No module named xmpp

### ISSUE THREAD

**Issue by kseistrup** [errbotio/errbot#133]
I just installed err-2.0-beta from pip, copied the config template to /tmp/config.py, and started err:

``` pytb
$ err.py -c /tmp
INFO:root:Config check passed...
Traceback (most recent call last):
  File "/usr/local/bin/err.py", line 150, in <module>
    bot_class = locals()[mode]()
  File "/usr/local/bin/err.py", line 142, in xmpp
    from errbot.backends.xmpp import XMPPBackend
ImportError: No module named xmpp
```

Indeed, while the …/errbot/backends directory contains several files, there is no xmpp.py file to be found there.

Python 2.7 on Linux 3.2.

**Comment by drops123456** [comment]
how do you this?
