### ISSUE TITLE
Discussion: Moving version check url to Github

### ISSUE THREAD

**Issue by sijis** [errbotio/errbot#1330]
Currently the http://version.errbot.io domain, which our versionChecker plugin uses, is referencing to an older version of errbot.

Similarly to #1329, I think we can move this to a Github subdomain.
We'll have to make some code changes, as the current plugin use GET which includes the detected python version and the app returns the best version to match the python version (https://github.com/errbotio/errbot/blob/master/errbot/core_plugins/vcheck.py#L39).

I think we can use a GET and pass the python version, then update the plugin to do the version comparison code. Using a `curl http://version.errbot.io/$python_major_version`. It'd be pretty static but potentially easier to manage than a whole app https://github.com/errbotio/errbot-version-server.

@errbotio/core thoughts?

**Comment by andrewthetechie** [comment]
I think this is a great idea. Even slightly more static, it seems it would be easy to update with a PR. It also prevents us from getting into a situation where the cert expires again and we run into trouble.

**Comment by sijis** [comment]
This got moved in #1400.
