### ISSUE TITLE
Slackclient published breaking changes

### ISSUE THREAD

**Issue by roylarsen** [errbotio/errbot#1334]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [* ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.2.0
* OS version: Windows Server 2016
* Python version: 3.6
* Using a virtual environment: yes

### Issue description

Slack published breaking changes to the slackclient yesterday. 

https://github.com/slackapi/python-slackclient/wiki/Migrating-to-2.x

### Steps to reproduce

pip install slackclient without a version pinned to get 2.0.0

### Additional info

You can currently work around this by installing 1.3.1

**Comment by maxim-nazarenko** [comment]
#1335 should make it work by default.
It is only a workaround and a proper fix to the Errbot code should be introduced.

**Comment by sijis** [comment]
This should be fixed in 6.1.0, as the slackclient version is pinned.
