### ISSUE TITLE
Don't know how to debug in Pycharm

### ISSUE THREAD

**Issue by epicGeek** [errbotio/errbot#1338]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [x] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.0.
* OS version: Windows 10
* Python version: 3.7
* Using a virtual environment: no

### Issue description

I wonder how to debug the code with pycharm. Because I'd like to view variable, constant and objects.

### Steps to reproduce

I run my bot in git bash 'errbot'

**Comment by sijis** [comment]
I personally do not use pycharm so I cannot answer this definitively.

Jetbrains help does offer this as a guide: https://www.jetbrains.com/help/pycharm/manage-projects-hosted-on-github.html.

I suspect once you are able to open the project you'll be able to navigate and the IDE should be able to highlight and track method/functions of the source code.

**Comment by Nov1kov** [comment]
It's easy. 
I use Windows 

1. go to "Edit configurations"
![image](https://user-images.githubusercontent.com/8822182/94147132-9147f280-fe7d-11ea-810b-fba15de01825.png)
2. Add new **python** configuration
![image](https://user-images.githubusercontent.com/8822182/94147034-6cec1600-fe7d-11ea-9862-5109b06cc678.png)
3. Set **Script path:** `YOUR_PY_DIRECTORY\Lib\site-packages\errbot\cli.py`
4. Set **Working directory:** `YOUR_PROJECT_DIRECTORY` which contain config.py
5. Enjoy to debug!
![image](https://user-images.githubusercontent.com/8822182/94147667-45497d80-fe7e-11ea-959d-29497cc38478.png)
