### ISSUE TITLE
Discussion: slackclient breaking changes

### ISSUE THREAD

**Issue by maxim-nazarenko** [errbotio/errbot#1339]
Currently, Errbot integration with the slackclient >= 2.0 is broken.
#1335 is a simple workaround until the integration is fixed.

The question: is it reasonable to support 1.x branch of the slackclient library or just rewrite Errbot's slack backend to be compatible with 2.x branch only?

Any thoughts on this?

**Comment by sijis** [comment]
I'd just fix the backend to support 2.x. I haven't looked into it so I have no idea what sort of effort is involved in doing so.

They do offer a guide on migrating: https://github.com/slackapi/python-slackclient/wiki/Migrating-to-2.x. I do know we use the rtm api so that section is probably where the bulk of the changes will occur.

**Comment by maxim-nazarenko** [comment]
> I'd just fix the backend to support 2.x. I haven't looked into it so I have no idea what sort of effort is involved in doing so.
> 
> They do offer a guide on migrating: https://github.com/slackapi/python-slackclient/wiki/Migrating-to-2.x. I do know we use the rtm api so that section is probably where the bulk of the changes will occur.

In the migration guide, they notice changes in method signatures so we will have to create kind of base class and 2 different implementations for Slack (if we want to have 1.x and 2.x slackclient branches at the same time).
I just wanted to know if it worth to maintain both versions or stick to slackclient 1.x in Errbot 5.2 and update 6.x to be compatible with slackclient 2.x

**Comment by sijis** [comment]
I do not think it's worth maintaining 5.2. I'd move forward with 6.x using 2.x slackclient.

**Comment by nzlosh** [comment]
Should we at least patch the exception string suggesting to pin slackclient to 1.3.1 rather than leaving the generic message?
```
15:55:00 CRITICAL errbot.backends.slack     You need to install the slackclient support in order to use the Slack backend.
You can do `pip install errbot[slack]` to install it
```
This would make is clear for v5.20 users to use the 1.3.1 library. v6.0 users could benefit from the same message until the backend is updated to support v2.0 slackclient.

**Comment by maxim-nazarenko** [comment]
added #1341 to not confuse the users

**Comment by sijis** [comment]
Referenced PR has been resolved. Closing this as there boot other action required.
