### ISSUE TITLE
Get "display name" of a Slack person

### ISSUE THREAD

**Issue by komodin** [errbotio/errbot#1344]
### I am...

* [X] Requesting help writing plugins

### I am running...

* Errbot version: 6.0.0
* OS version: macOS 10.14.4
* Python version: 3.7.3
* Using a virtual environment: yes

### Issue description

Hi,
I'm trying to get the "display name" of a person in Slack to use it in a plugin, but I can't find any attribute with that value. I can't figure out if I'm missing something or if it isn't implemented on the Slack backend module.

Thanks in advance for any help.

**Comment by jamiegwatkin** [comment]
You can do something like this:

```python
@botcmd
def hello(self, msg, args):
  user = str(msg.frm).split("/")[1]
  user_identifier = self.build_identifier(f"@{user}")
  return f"Hello {user_identifier}"
```

**Comment by VerosK** [comment]
You can also check the internals of `!whoami` command.

https://github.com/errbotio/errbot/blob/6.1/errbot/core_plugins/utils.py#L20

**Comment by sijis** [comment]
Solutions provided.
