### ISSUE TITLE
plugin reloading is not working

### ISSUE THREAD

**Issue by attakei** [errbotio/errbot#1346]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1
* OS version: ArchLinux
* Python version: 3.7.3
* Using a virtual environment: yes

### Issue description

core-plugin command `!plugin reload` is not working.
If edit running plugin and call reload, it had been not reflected.

### Steps to reproduce

1. Create errbot work directory by `errbot --init`
1. Run errbot by `errbot -T`
1. Call `!tryme` <- check output before reload
1. Edit `./plugins/err-example/example.py`
1. Call `!plugin reload Example`
1. Call `!tryme` <- check output after reload

On version 5.2.0

```
[@CHANGE_ME ➡ @errbot] >>> !tryme
It works !

[@CHANGE_ME ➡ @errbot] >>> !plugin reload Example
Plugin Example reloaded.

[@CHANGE_ME ➡ @errbot] >>> !tryme
It works !!
```

On version 6.1.0

```
[@CHANGE_ME ➡ @errbot] >>> !tryme
It works !

[@CHANGE_ME ➡ @errbot] >>> !plugin reload Example
Plugin Example reloaded.

[@CHANGE_ME ➡ @errbot] >>> !tryme
It works !
```

### Additional info
I am trying fix for this issue, and I will post PR soon.

**Comment by sijis** [comment]
Out of curiosity, does the following work?
* `!plugin deactivate`, then `!plugin activate`
* `!repos update`

**Comment by attakei** [comment]
I've tried your commands same of reproduce flow.

> - `!plugin deactivate`, then `!plugin activate`
> - `!repos update`

In either cases, There were output same of before edit (I seem not to work commands correctly?)
