### ISSUE TITLE
Documentation wrong or unintended dependency on Python 3.6

### ISSUE THREAD

**Issue by bf-ckiendl** [errbotio/errbot#1354]
### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1.1 (according to pip, I cannot check in errbot since it is nonfunctional)
* OS version:  Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux
* Python version: Python 3.5.3
* Using a virtual environment: yes

### Issue description

According to [the documentation](http://errbot.io/en/latest/user_guide/setup.html),

> Errbot runs under Python 3.3+ on Linux, Windows and Mac.

However, part of the changes for 6.0.0-alpha was

> ported formats and % str ops to f-strings

PEP 498, formatted literal strings, was [implemented in Python 3.**6**](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498).

By using f-strings, errbot is inevitably dependent on 3.6. This dependency is neither disclosed in the documentation nor programmatically enforced through pip.  
Yes, the changelog for 6.0.0-alpha _does_ state

> removed Python 3.5 support

but why would I, as a new user, start my interaction with errbot by reading the changes of three months ago?  
I only even ended up seeing that changelog _after_ I had inexplicable syntax errors, _after_ I figured out f-strings were to blame, and _after_ I saw there were no issues related to this.

Basically, _after_ I had figured out the issue entirely on my own and knew what to search for, I _then_ discovered that this _might_ be intentional.

### Steps to reproduce

- install Python from [Debian 9 stable repositories](https://packages.debian.org/search?keywords=python3)
- read official errbot setup documentation
- compare prerequisite Python version with installed Python version
- be happy
- continue setup
- try to run `errbot --init`
- fail with a syntax error

### Additional info

Independent of the fundamental issue of the **documentation being wrong**, the fact that the **[package on PyPi](https://pypi.org/project/errbot/) erroneously declares 3.4 and 3.5 as valid** Python versions for errbot leads to seemingly smooth but actually nonfunctional installations.
The package metadata should be adjusted to prevent this.

In addition, the dependency on 3.6 has strategic implications insofar as that the **current stable Debian does not ship Python 3.6** and has all its dependencies built around Python 3.5.
By requiring Python 3.6, you are implicitly requiring a lot of extra effort of Debian users to provide a separately managed Python version independent of the official repos.

Depending on how important you consider Debian, that might be unwise.

**Comment by sijis** [comment]
I completely forgot that changes were made to use f-strings. :disappointed: 

We'll have update the docs and address the packaging restrictions too to match the codebase.

I understand the dependency concerns around stable Debian using 3.5 as a base instead of 3.6 and how that affect an errbot installation. The quickest workaround I can suggest is using the `python:3.7` docker image from docker hub, as a starting point.

We've mainly been considering the python version and not necessarily how that relates to the shipped python version of an OS / distro. It is unfortunate that In some cases, as you've noted, the pairing does not match.

Thank you for bringing this up.
