### ISSUE TITLE
documentation website is broken

### ISSUE THREAD

**Issue by rparsonsbb** [errbotio/errbot#1372]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: n/a
* OS version:
* Python version: 
* Using a virtual environment: yes/no

### Issue description

The documentation website [errbot.io](http://errbot.io/) is currently down.

### Steps to reproduce

Go to  [errbot.io](http://errbot.io/) 

Error 1014 Ray ID: 5018a421cc92c16b • 2019-08-05 12:05:45 UTC
CNAME Cross-User Banned

### Additional info

If you have any more information, please specify it here.

**Comment by sijis** [comment]
Thank you for sending this. We've been aware of the problem and it will be addressed.

**Comment by sijis** [comment]
It's been back a few days now. Thanks for taking the time to submit an issue about it.
