### ISSUE TITLE
Replace SleekXMPP with more modern slixmpp

### ISSUE THREAD

**Issue by derek-austin** [errbotio/errbot#1380]
### I am...

* [x] Here about something else

### I am running...

* Errbot version: errbot==6.1.1
* OS version: Fedora 30 (MATE-Compiz)
* Python version:  Python 3.7.4
* Using a virtual environment: yes

### Issue description

SleekXMPP don't connect to ejabberd

### Steps to reproduce

~~~ bash
wget https://raw.githubusercontent.com/rroemhild/docker-ejabberd/master/examples/docker-compose/docker-compose.yml
docker-compose up
~~~

Configure errbot

~~~ py
import logging


BACKEND = 'XMPP'  # defaults to XMPP
BOT_DATA_DIR = '/home/user/git/errbot/data_dir'
BOT_EXTRA_PLUGIN_DIR = None
PLUGINS_CALLBACK_ORDER = (None, )
BOT_LOG_FILE = BOT_DATA_DIR + '/err.log'
BOT_LOG_LEVEL = logging.DEBUG
BOT_LOG_SENTRY = False
SENTRY_DSN = ''
SENTRY_LOGLEVEL = BOT_LOG_LEVEL
BOT_IDENTITY = {
    'username': 'admin@example.com',  # The JID of the user you have created for the bot
    'password': 'password4321',       # The corresponding password for this user
    'server': ('127.0.0.1',5222), # server override
}

BOT_ADMINS = ('admin@example.com',)
BOT_ADMINS_NOTIFICATIONS = ('admin@example.com')

DIVERT_TO_PRIVATE = ()
DIVERT_TO_THREAD = ()
CHATROOM_RELAY = {}
REVERSE_CHATROOM_RELAY = {}
~~~

~~~ bash
pipenv install errbot
pipenv run errbot
mkdir data_dir
errbot
~~~

**Comment by derek-austin** [comment]
Not working for me.
If you want to replicate see https://github.com/errbotio/errbot/pull/1377#issuecomment-524784309

**Comment by derek-austin** [comment]
Slixmpp is the recomended for Python in xmpp.org. See https://xmpp.org/software/libraries.html
Slixmpp is a fork of SleekXMPP.

**Comment by Daniel-at-github** [comment]
@sijis, SleekXMPP is oficially deprecated, and recommends Slixmpp. See 
https://github.com/fritzy/SleekXMPP

**Comment by raspbeguy** [comment]
I approve switching to Slixmpp. I have a TLS issue with SleekXMPP that nobody could help me solve, probably because it's deprecated.

**Comment by raspbeguy** [comment]
Thanks for solving this issue. How can we expect the next release that includes it?
