### ISSUE TITLE
Could not update from source https://repos.errbot.io/repos.json, keep the index as it is

### ISSUE THREAD

**Issue by maxleonca** [errbotio/errbot#1382]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1.1
* OS version: Arch Linux
* Python version: 3.7.4
* Using a virtual environment: yes

### Issue description

Installing any repo from a Github repo I get, Could not update from source https://repos.errbot.io/repos.json, keep the index as it is

### Steps to reproduce
Try with any repo from Github

### Additional info
Accessing the repos.errbot.io via the browser, dosent respond.
Also no DNS answer when querying for an A record for repos.errbot.io

**Comment by RO-29** [comment]
Same issue for me!

**Comment by RO-29** [comment]
@maxleonca well it turns out, you can generate your own, just look at this issue :) 

https://github.com/errbotio/errbot/issues/623

**Comment by sijis** [comment]
We are aware of the DNS issue regarding that subdomain.

**Comment by maxleonca** [comment]
> We are aware of the DNS issue regarding that subdomain.

Not sure if you are aware of this one, but seems that version.errbot.io is also unavailable now, same symptom no DNS record.

**Comment by sijis** [comment]
Yup

**Comment by lordn-n** [comment]
A quick and dirty fix, could be setting `BOT_PLUGIN_INDEXES = ()` in your config, this will skip updating the repos index and just install from source any github repo

**Comment by sijis** [comment]
This PR will try and address this https://github.com/errbotio/errbot/pull/1400

**Comment by sijis** [comment]
PR #1403 and #1406 have been merged into `master` which should address this issue.
