### ISSUE TITLE
`/proc/1/cgroup`: errbot is mandatorily checking for this file for non-docker builds too

### ISSUE THREAD

**Issue by RO-29** [errbotio/errbot#1383]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ✅  ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.1.3
* OS version: macOS Sierra: 10.12.6
* Python version: 3.6.0
* Using a virtual environment: no

### Issue description

errbot text mode is throwing up trying to find `/proc/1/cgroup` even for non docker builds
```
in is_docker
    with open('/proc/1/cgroup') as d:
FileNotFoundError: [Errno 2] No such file or directory: '/proc/1/cgroup'
```
### Steps to reproduce

jut run errbot -T

**Comment by RO-29** [comment]
I would like to submit a PR for this to fix this issue

**Comment by sijis** [comment]
Could you try with the latest version of errbot or master branch?

**Comment by RO-29** [comment]
The bug still exists in the master 

```
Some plugins failed to start during bot startup:
 <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/proc/1/cgroup'
  File "/Users/rohit/.pyenv/versions/3.6.0/lib/python3.6/site-packages/errbot/plugin_manager.py", line 82, in install_packages
    elif is_docker():
  File "/Users/rohit/.pyenv/versions/3.6.0/lib/python3.6/site-packages/errbot/plugin_manager.py", line 67, in is_docker
    with open('/proc/1/cgroup') as d:
 <class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/proc/1/cgroup'
  File "/Users/rohit/.pyenv/versions/3.6.0/lib/python3.6/site-packages/errbot/plugin_manager.py", line 82, in install_packages
    elif is_docker():
  File "/Users/rohit/.pyenv/versions/3.6.0/lib/python3.6/site-packages/errbot/plugin_manager.py", line 67, in is_docker
    with open('/proc/1/cgroup') as d:
```

The faulty code is here:

https://github.com/errbotio/errbot/blob/master/errbot/plugin_manager.py#L66-L68
```
def is_docker():
        with open('/proc/1/cgroup') as d:
            return 'docker' in d.read()
```
Can be modified as 
```
def is_docker():
        if not os.path.exists('/proc/1/cgroup):
            return false
        with open('/proc/1/cgroup') as d:
            return 'docker' in d.read()
```

Can I submit a PR to fix this?

**Comment by sijis** [comment]
Sure.

**Comment by sijis** [comment]
@RO-29 you can absolutely submit a PR to address this issue. It would be welcomed.

**Comment by RO-29** [comment]
Hey @sijis 

the fix is up here https://github.com/errbotio/errbot/pull/1385

**Comment by RO-29** [comment]
Hey, 
@sijis any news about the proposed fix?

Can I Close and re-open a new PR to be able to make it count for #Hacktoberfest? 
Thx!

**Comment by sijis** [comment]
Sure. It seems I've missed the notices.

**Comment by RO-29** [comment]
@sijis the fix is here again

https://github.com/errbotio/errbot/pull/1389/
