### ISSUE TITLE
Clarify License of prompt.svg

### ISSUE THREAD

**Issue by bschacht** [errbotio/errbot#1384]
### I am...

* [ ] Here about something else

### Issue description

Hi, the file errbot/backends/images/prompt.svg mentions as copyright holder `Copyright © 2013 Apple Inc. All rights reserved.` without a specific license. This makes it hard for distributions to package and errbot. It would be great if the file could be replaced with a file with a public domain license.

If you want, you can use this https://gist.github.com/bschacht/0ee1c035a78c129e67950a1c7b0dca3c which is not as pretty, but its under public domain

**Comment by gbin** [comment]
oh wow, I had no clue. Let me fix that right away.

**Comment by gbin** [comment]
Fixed directly in master. Thanks a lot for spotting that, it totally went under the radar.
