### ISSUE TITLE
Errbot --init shouldn't crash if plugins/ exists

### ISSUE THREAD

**Issue by torgeirl** [errbotio/errbot#1388]
### I am...

* [ ] Reporting a bug
* [X] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1.1
* OS version: Ubuntu 18.04 LTS
* Python version: 3.7.3
* Using a virtual environment: yes

### Issue description

`errbot --init` crashes if the plugin or data sub directories already exists. This prevents the command from being idempotent (once you correct an error the caused failure, you can't just rerun the script).

It can be useful to initiate with plugins in the `plugins/` directory.

**Comment by sijis** [comment]
Some changes landed on master (and likely 6.1.2), which should address this.

**Comment by torgeirl** [comment]
@sijis: thank you! :pray:
