### ISSUE TITLE
code

### ISSUE THREAD

**Issue by smkelly** [errbotio/errbot#1393]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version:
* OS version:
* Python version: 
* Using a virtual environment: yes/no

### Issue description

Please describe your bug/feature/problem here.
The more information you can provide, the better.

### Steps to reproduce

In case of a bug, please describe the steps we need to take in order to reproduce your issue.
If you cannot easily reproduce the issue please let us know and provide as much information as you can which might help us pinpoint the problem.

### Additional info

If you have any more information, please specify it here.

**Comment by sijis** [comment]
No content. Closing.
