### ISSUE TITLE
Circular Dependencies when there are none

### ISSUE THREAD

**Issue by jakubclark** [errbotio/errbot#1397]
### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [x] Here about something else

### I am running...

* Errbot version: 6.1.1
* OS version: Tried on Windows and MacOS
* Python version: 3.6.8
* Using a virtual environment: N/A

### Issue description

I have a situation where I have a total of 3 plugins:

- PluginA
- PluginB
- PluginC

Below are their plugin dependencies:

- PluginA depends on PluginB and PluginC
- PluginB depends on PluginC

I've roughly visualized the dependencies here:

![deps](https://user-images.githubusercontent.com/19486495/70267592-0a674380-179f-11ea-8989-300d935c43b1.png)

Trying to run with this configuration results in an error:

```
2019-12-05 20:21:59,078 INFO     errbot.core               Error: PluginA failed to activate: Circular dependency in the set of plugins (PluginC, PluginA, PluginB).
```

PluginA fails to load, due to "circular dependencies". However, I do not see circular dependencies from what I described above.

So is this intentional; not allowing PluginA to depend on PluginC, since PluginB already depends on PluginC, and PluginA does depend on PluginB?

There aren't circular dependencies, since `self` depends on the same plugins as a child plugin depends on.

A workaround is to do something like this:

PluginA does not depend on PluginC

Then, from within `PluginA` do teh following:
```python
self.get_plugin('PluginB').get_plugin('PluginC')
```

### Steps to reproduce

I've created a repo with the necessary code to reproduce this error [here](https://github.com/jakubclark/errbot-dependencies).
Simply run the [test](https://github.com/jakubclark/errbot-dependencies/blob/master/plugins_test.py): `pytest plugins_test.py`.
Or run `errbot` itself, it is configured for text mode.

**Comment by sijis** [comment]
I have not run this but my guess is to remove PluginA to depend on PluginC.

You should be able to load up pluginC from pluginA, as `self.get_plugin('PluginC')`.

**Comment by jakubclark** [comment]
Thanks @sijis. Removing the `PluginC` depedency from `PluginA` seems to work, I'll try this against my actual chatbot tomorrow. If all goes well, I'll close this issue.

**Comment by jakubclark** [comment]
By making `PluginA` not explicitly depend on `PluginC` the "circular dependencies" have been resolved, as `PluginB` already depends on `PluginC`.

**Comment by HandsomeWins** [comment]
Hi, I have the exact same sort of setup as @jakubclark and the suggested mitigations don't work for me. Agree with @jakubclark that this shouldn't be a circular dependency issue. 

I've also run into another issue while trying to set up a simple PluginA -> PluginB -> PluginC relationship: for some reason, despite PluginB's Core section listing PluginC as a dependency, self.dependencies for PluginB doesn't list PluginC as a dependency so when I try self.get_plugin('PluginC') in PluginB I get an exception about how
`Plugin dependency PluginC needs to be listed in section [Core] key "DependsOn" to be used in get_plugin.`

It doesn't sound like this issue is closed. The circular dependency logic seems faulty and there's some sort of bug that results in self.dependencies not being populated properly.

**Comment by jakubclark** [comment]
Reopening this, as the issue has occurred once again:

`PluginA` depends on `PluginB`
`PluginB` depends on `PluginC`

```python
class PluginA(BotPlugin)
    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.plugin_c = self.get_plugin('PluginC')
```

Error message: "Plugin dependency PluginC needs to be listed in section [Core] key "DependsOn" to be used in get_plugin."

I had to restart my bot 3 times, before `self.get_plugin('PluginC')` did not fail.


It seems that it is random, if `self.get_plugin('PluginC')` results in an error. If it does result in an error, the bot must be restarted a few times, and eventually it will work.

**Comment by sijis** [comment]
Could you validate if this behavior happens using the master branch?

**Comment by sir-klyx** [comment]
I can confirm this happens with Errbot version 6.1.4. Inconsistently giving me the same error.
