### ISSUE TITLE
Question: How can i add more than one backend/adapter?

### ISSUE THREAD

**Issue by MothGirlMusic** [errbotio/errbot#1399]
### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [x] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: rroemhild/errbot:latest from docker
* OS version: whatever the docker image has.
* Python version: whatever the docker image has.
* Using a virtual environment: yes

### Issue description

How can i configure my bot to work on both Telegram and Discord at the same time? I use both platforms and i'd like to write a plugin that transfers messages across one platform's channel to another selected channel. However, for that i just need to get the bot to recognize two platforms at once. how can i do that?

**Comment by sijis** [comment]
You can only run one backend at a time. So it is not possible to connect to both Telegram and Discord.

You will have run two errbot instances.

**Comment by MothGirlMusic** [comment]
oh, that’s disappointing.. thank you for your answer though! hopefully something like that becomes possible in the future.
