### ISSUE TITLE
Errbot unable to authorize "new style" Slack apps/bots via OAuth2

### ISSUE THREAD

**Issue by Andenthal** [errbotio/errbot#1402]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1.1
* OS version: Amazon Linux / Mac OS 10.14.6 (Mojave)
* Python version: 3.6.7 / 3.7.5
* Using a virtual environment: no / no

### Issue description

New style Slack bots use OAuth 2 (with a new response format). The Errbot backend does not appear to support this. Classic style Slack bots do not appear to be able to be created from Slack's site at this time. 

### Steps to reproduce

Via the Slack web ui (https://api.slack.com/apps) create a new bot for your Slack space. Follow the prompts, paying attention to the "OAuth & Permissions" section (giving your bot permission scopes). Give your bots as many or as few permissions as you desire - it seems irrelevant with regards to Errbot. 

Pay special attention to Step4;
```
In order for your app to issue tokens with your chosen scopes, you’ll need to make some changes in your OAuth code to reflect these scopes and handle the new response format.

Your app should request these scopes
Bot token scopes
chat:write
chat:read
Change your app’s authentication URL to look like this:
https://slack.com/oauth/v2/authorize?client_id=123456789012.123456789012&scope=chat:write chat:read
```

Complete the configuration of your app/bot, all the way through installing it to your workspace. Once installed, you will be presented with an OAuth token in the form of `xoxb-123456....` Place this token in `config.py` per Errbot documentation. Start Errbot, you will receive an error similar to the following;

```
<truncated>
19:12:04 DEBUG    errbot.bootstrap          Start serving commands from the slack backend.
19:12:04 INFO     errbot.backends.slack     Verifying authentication token
19:12:04 DEBUG    urllib3.connectionpool    Starting new HTTPS connection (1): slack.com:443
19:12:04 DEBUG    urllib3.connectionpool    https://slack.com:443 "POST /api/auth.test HTTP/1.1" 200 132
19:12:04 DEBUG    errbot.backends.slack     Token accepted
19:12:04 INFO     errbot.backends.slack     Connecting to Slack real-time-messaging API
19:12:04 DEBUG    urllib3.connectionpool    Starting new HTTPS connection (1): slack.com:443
19:12:04 DEBUG    urllib3.connectionpool    https://slack.com:443 "POST /api/rtm.start HTTP/1.1" 200 92
19:12:04 WARNING  slackclient.client        Failed RTM connect
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/slackclient/client.py", line 140, in rtm_connect
    self.server.rtm_connect(use_rtm_start=with_team_state, **kwargs)
  File "/usr/lib/python3.6/site-packages/slackclient/server.py", line 163, in rtm_connect
    raise SlackLoginError(reply=reply)
slackclient.server.SlackLoginError
19:12:04 ERROR    errbot.backends.base      Exception occurred in serve_once:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/errbot/backends/base.py", line 699, in serve_forever
    if self.serve_once():
  File "/usr/lib/python3.6/site-packages/errbot/backends/slack.py", line 392, in serve_once
    raise Exception('Connection failed, invalid token ?')
Exception: Connection failed, invalid token ?
19:12:04 INFO     errbot.backends.base      Reconnecting in 1 seconds (0 attempted reconnections so far).
```

### Additional info

This can also happen if you try to modify a 'classic style' bot's permission scheme. When you do this, you are essentially migrating your bot from a 'classic style' bot to a 'new style' one. 

Workaround appears to be; ~~do not modify any existing apps/bots in Slack. New bot creation appears to be broken.~~ when creating a new bot via the web UI, in the "Bot Users" area, give your bot a name - DO NOT add additional permissions via the "OAuth & Permissions" area. This will allow you to create a classic style bot

**Comment by Andenthal** [comment]
This is an issue with Slack, not errbot.
https://api.slack.com/authentication/basics
>New Slack apps may not access RTM.

**Comment by davisliu11** [comment]
I had the same problem. It'd be great if errbot can support the new app as well. My company has policy to restrict apps to new styles thus my app sadly cannot be deployed.

**Comment by josdoaitran** [comment]
Hi all,
I got the same issues, And I got the solution to create a classic app for Errbot.

- Go to https://api.slack.com/apps?new_classic_app=1 and create a classic app
- Go to OAuth & Permissions in the left pane
- Add bot scope in the Scopes section
- You'll see a warning saying "This scope is deprecated. Please update scopes to use granular permissions." but don't upgrade to the newer permission model
- Go to App Home in the left pane
- Click Add Legacy Bot User and set its name
- Go to Install App in the left pane
- Run the OAuth flow with your development workspace
- Use Bot User OAuth Access Token for your RTM app

**Comment by dhanupreeth** [comment]
> Hi all, I got the same issues, And I got the solution to create a classic app for Errbot.
> 
> * Go to https://api.slack.com/apps?new_classic_app=1 and create a classic app
> * Go to OAuth & Permissions in the left pane
> * Add bot scope in the Scopes section
> * You'll see a warning saying "This scope is deprecated. Please update scopes to use granular permissions." but don't upgrade to the newer permission model
> * Go to App Home in the left pane
> * Click Add Legacy Bot User and set its name
> * Go to Install App in the left pane
> * Run the OAuth flow with your development workspace
> * Use Bot User OAuth Access Token for your RTM app

legacy bot working fine, but when trying to use @botname the response is not coming I'm using Errbot and use Bot Prefix as @botname nothing working, any help much appreciated.
