### ISSUE TITLE
I'm Unable to use Errbot with Slack as a Botuser

### ISSUE THREAD

**Issue by a0149659** [errbotio/errbot#1417]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [x] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1.2
* OS version: Linux, any.
* Python version: 3.7
* Using a virtual environment: yes

### Issue description

Errbot no longer works with Slack.com API.

### Steps to reproduce
Any Slack Enterprise Workspace or create a new standard workspace and request a Bot User Token.

### Additional info

Will Errbot be upgraded / changed to meet slack.com's new connection method policies ?

**Comment by sijis** [comment]
There is an experimental backend using the new slack api. Try it out and see if it works for you.

See #1416.

**Comment by ppinzon** [comment]
@sijis do you know if there's work to support the event's API instead? The RTM is being phased out and newly created apps can't use errbot unless you go out of the way and create an old V1 app.

**Comment by sijis** [comment]
> @sijis do you know if there's work to support the event's API instead? The RTM is being phased out and newly created apps can't use errbot unless you go out of the way and create an old V1 app.

I saw a message about a week after the release, that the RTM was being deprecated :(.

There is no work going on the events API.

**Comment by nzlosh** [comment]
Just a small update, work is underway to support the events API using the new fine grain Slack tokens.  https://github.com/errbotio/errbot/pull/1451

**Comment by nzlosh** [comment]
Work on a slack backend that supports RTM and Events is available here https://github.com/nzlosh/err-backend-slackv3

**Comment by sijis** [comment]
Strongly suggest using the slack-v3 backend.
