### ISSUE TITLE
6.1.2 not released

### ISSUE THREAD

**Issue by flokli** [errbotio/errbot#1419]
### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version:
* OS version:
* Python version: 
* Using a virtual environment: yes/no

### Issue description

It seems errbot 6.1.2 isn't released as a tag or release on the github page, even though there's release notes on the website.

**Comment by sijis** [comment]
There is a released version: https://pypi.org/project/errbot/#history

If you are trying to find that within the repo, look at the 6.1 branch. It just doesn't look like it was tagged.

**Comment by torgeirl** [comment]
@sijis: any progress on make a Github release for `6.1.2`?

I completely missed it myself when it didn't show up here, and would assume others are in the same situation. External tools like [GitPunch](https://gitpunch.com/) monitor releases on Github, not PyPI.

**Comment by sijis** [comment]
I apologize for it taking so long to create a simple tag. I do see the release in releases now.

Are you seeing in tools like GitPunch?

**Comment by torgeirl** [comment]
No worries. It showed up in GitPunch today :+1:

**Comment by sijis** [comment]
That's great!
