### ISSUE TITLE
How to customize help message for each command

### ISSUE THREAD

**Issue by hanks** [errbotio/errbot#1420]
Now when type `!help` in slack, the command help message will be built with `command name` and `comment` of cmd method, how to dynamically set this help message, just something like below:

```python
@botcmd(split_args_with=None, name='foo', help='a help message')
def foo(self, message, params):
    pass
```

And it will be rendered in the slack like:

```
* a help message
```

**Comment by sijis** [comment]
I'm pretty sure that's not possible, as you have it.

You'd have to add the help text to the method.

**Comment by hanks** [comment]
yeah, right now seems it is hard coded with `__doc__` in `help plugin`

**Comment by nzlosh** [comment]
You can create dynamic help messages by creating a dynamic plugin.  https://errbot.readthedocs.io/en/latest/user_guide/plugin_development/dynaplugs.html

**Comment by hanks** [comment]
@nzlosh thanks, will try it :smile:

**Comment by nzlosh** [comment]
@hanks If it helps, here's how I implemented a dynamic plugin.
https://github.com/nzlosh/err-stackstorm/blob/master/st2.py#L421
