### ISSUE TITLE
Override original backend with custom one

### ISSUE THREAD

**Issue by duhow** [errbotio/errbot#1422]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [x] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1.2
* OS version: Debian / Linux (Docker)
* Python version: 3.8.2
* Using a virtual environment: yes

### Issue description

I'm writing a copy of Slack backend + plugin with webhook to not listen to RTM, as Slack new applications won't work with RTM. New backend is just a copy-paste of the original one, with same name. The problem is that sometimes when I start bot, it runs with original backend, and when I close / open multiple times, then ErrBot opens with my own Backend.

Is there any config or code to use to override my custom Backend with original one?

### Steps to reproduce

In case of a bug, please describe the steps we need to take in order to reproduce your issue.
If you cannot easily reproduce the issue please let us know and provide as much information as you can which might help us pinpoint the problem.

### Additional info

If you have any more information, please specify it here.

**Comment by nzlosh** [comment]
If you're developing a new backend the correct way would be to give the backend a new name and reference it in errbot's configuration.  Alternatively, modify the origin backend code directly.  Once a copy/paste is performed there is no relationship between the 2 backends so controlling which backend loads first is indeterminate.
