### ISSUE TITLE
Fix Slack backend's use of deprecated method IM.OPEN

### ISSUE THREAD

**Issue by gkspranger** [errbotio/errbot#1431]
* [x ] Reporting a bug

* Errbot version: 6.1.4
* OS version: CentOS7
* Python version: 3.7.7
* Using a virtual environment: yes
* Backend: Slack

I am installing the Slack backend via `errbot[slack]` .. I am getting DEBUGs in my logs and sometimes outright errors about the used of a deprecated method `IM.OPEN`

https://github.com/errbotio/errbot/blob/master/errbot/backends/slack.py#L592-L603

https://api.slack.com/methods/im.open

```2020-06-18T13:27:31.66-0400 [APP/PROC/WEB/0] ERR 2020-06-18 17:27:31,662 DEBUG    errbot.backends.slack     Tried to build an identifier from '<@abc123>' but got exception: Slack API call to im.open failed: method_deprecated```

It appears we need to use this method, but not sure how to implement/test :: https://api.slack.com/methods/conversations.open

thanks,
greg

**Comment by jcastro-sfdc** [comment]
#1432 Have a look at this

![image](https://user-images.githubusercontent.com/48135245/86162330-9abefa00-badc-11ea-9f44-520c17d4550f.png)

**Comment by gkspranger** [comment]
thanks @jcastro-sfdc for looking into this -- i appreciate the work and the PR

**Comment by cappetta** [comment]
Just hit this.  Thanks for fixing @jcastro-sfdc

**Comment by olanystrom** [comment]
Works great, when is this release coming? 6.1.4 was a long time ago

**Comment by sijis** [comment]
6.1.5 was release.
