### ISSUE TITLE
Errbot Cannot Find User ID in Slack

### ISSUE THREAD

**Issue by geeitsjo** [errbotio/errbot#1434]
### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [x] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1.2
* OS version: Mac 10.15.3
* Python version: 3.7.7
* Using a virtual environment: **yes**/no

### Issue description

We have a plugin that is built and uses the errbot framework. Our error started happening two days ago. We have not found any pattern as to time, users, region, or cause to why the error occur. After not having changed any code in our plugin for a month. We have recently received in our logs "ERROR errbot.backends.slack Cannot find user with ID" Most of the time restarting errbot or spinning up a new instance does solves the issue and it works then 16 hours or so later the error would happen again despite it being operational for the last 16 hours. We're really confused as we've version locked our requirements file and haven't changed anything in our production code, the only thing that isn't version locked is: errbot[slack]. No exception was raised during investigation of the event. 

Once the error is raise "ERROR errbot.backends.slack Cannot find user with ID" no one can interact with the plugin anymore. 

### Steps to reproduce

I cannot replicate the issue. We don't know what causes it as it mostly works but 3 times we've seen it crash because of this reason. I also want to update to the latest version of the modules we're using but currently the team isn't so keen to updating because of the current dependencies we have in our environment.

**Comment by gbin** [comment]
Do you have a large installation by any chance?

**Comment by geeitsjo** [comment]
> Do you have a large installation by any chance?

Relatively small, we're only running small plugins for errbot

**Comment by geeitsjo** [comment]
This was a Slack issue with their RTM endpoint. Fix was deployed after issue was raised. 
Thank you!
