### ISSUE TITLE
SlackRTM documentation and example

### ISSUE THREAD

**Issue by torgeirl** [errbotio/errbot#1435]
### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [x] Requesting help with running my bot
* [x] Requesting help writing plugins
* [x] Here about something else

### I am running...

* Errbot version: 6.1.4
* OS version: Debian
* Python version: 3.7
* Using a virtual environment: no (using Docker instead)

### Issue description
The new SlackRTM backend added in #1416 doesn't seems to covered at the ReadTheDocs pages. I seems it's intended to be a 1-to-1 replacement of the old backend (more or less the same functionality, but a different version of the `slackclient` dependency).

Trying to update my bot I can't get it to work the same way however. For instance, it replies to bot commands DMs but not in channels. Are there any quirks with the new backend I should know about when updating? Do you have any working examples of using it that could be added to the documentation?

And perhaps [the old documentation](https://errbot.readthedocs.io/en/latest/user_guide/configuration/slack.html) should be marked as deprecated or replaced as of `slackclient` 2.0?

**Comment by sijis** [comment]
The SlackRTM backend is in [beta state](https://github.com/errbotio/errbot/blob/master/CHANGES.rst#v613-2020-04-19). We expect they will be issues and thing will probably not behave as expected. Filing bugs will help us address the problems.

The goal is that changing the bot backend should not affect the plugin, unless the plugin is using backend internals for some functionality.

**Comment by torgeirl** [comment]
@sijis: my bad.

> Filing bugs will help us address the problems.
Will do! 😉
