### ISSUE TITLE
`--storage-merge` doesn't merge

### ISSUE THREAD

**Issue by rcoup** [errbotio/errbot#1444]
### I am...

* [x] Reporting a bug

### I am running...

* Errbot version: 6.1.4
* OS version: Debian Linux
* Python version: 3.8
* Using a virtual environment: yes

### Issue description

As a workaround for #964 preventing plugin configuration in Slack, the [provisioning docs](https://github.com/errbotio/errbot/blob/master/docs/user_guide/provisioning.rst) have:

> To add or change specific values without touching others you can merge a dictionary like that:
> 
>     echo "{'configs': {'Webserver': {'PORT': 9999}}}" | errbot --storage-merge core

Except that doesn't seem to work

### Steps to reproduce

```console
$ errbot --storage-get core
{'configs': {'Weather': {'APPID': 'a-key', 'DEFAULT_CITY_IDS': [2193733, 2179537, 2650225]}}}
$ echo "{'configs': {'Webserver': {'PORT': 9999}}}" | errbot --storage-merge core
$ errbot --storage-get core
{'configs': {'Webserver': {'PORT': 9999}}}
```

### Additional info

Reproduced with both the Shelf and SQL storage backends.

**Comment by sijis** [comment]
@rcoup I've created https://github.com/errbotio/errbot/pull/1450.
Would you be able to try that patch and validate if it works for you?

**Comment by rcoup** [comment]
@sijis LGTM 👍 

Thanks!
