### ISSUE TITLE
Errbot experiencing constant slack backends error - cannot find user with ID

### ISSUE THREAD

**Issue by jeremymec** [errbotio/errbot#1447]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [X] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1.4
* Slack-client version: 1.3.2
* OS version: Docker running on Linux, Windows 10
* Python version: 3.6.8
* Using a virtual environment: yes

### Issue description

When running and listening in a slack channel with a slack backend, the bot spits out constant errors relating to finding users. The error looks like this
ERROR    errbot.backends.slack     Cannot find user with ID XXXXXX
This impairs functionality like replying to a specific users message. To the best of my knowledge, this problem did not occur last week despite no code changes. 

### Steps to reproduce

Start an instance of errbot listening in a slack channel, and send a message to the channel. The error should appear.

**Comment by sijis** [comment]
Specifically which backend are you using? What do you have defined in your `config.py`?

**Comment by jeremymec** [comment]
I'm using slack, so my config.py says
BACKEND = 'Slack'
and as I said in the post the version of my slack-client is 1.3.2

**Comment by sijis** [comment]
Would you be able to see if running the master branch gives the same behavior?

pip install git+git://github.com/errbotio/errbot

**Comment by jeremymec** [comment]
Hi,
I did a clean install with the master branch and an empty errbot project and I can confirm I still have this behavior.

**Comment by sijis** [comment]
@jeremymec Thanks for confirming.

**Comment by sijis** [comment]
@jeremymec I cannot seem to reproduce this locally. Running a basic config (using `errbot --init`) does not generate this message, nor does executing a simple reply plugin.

Would you be able to provide a plugin or some other information that is able to generate this error consistently?

**Comment by medecau** [comment]
I'm having similar problems.

`TypeError: username_to_userid() missing 1 required positional argument: 'name'`

Note the following static method signature for username_to_userid:
https://github.com/errbotio/errbot/blob/2338284ea8542a5b764e28ade998ac7bee56c42e/errbot/backends/slack_rtm.py#L530

and how it is used later:
https://github.com/errbotio/errbot/blob/2338284ea8542a5b764e28ade998ac7bee56c42e/errbot/backends/slack_rtm.py#L358
https://github.com/errbotio/errbot/blob/2338284ea8542a5b764e28ade998ac7bee56c42e/errbot/backends/slack_rtm.py#L608
https://github.com/errbotio/errbot/blob/2338284ea8542a5b764e28ade998ac7bee56c42e/errbot/backends/slack_rtm.py#L632
https://github.com/errbotio/errbot/blob/2338284ea8542a5b764e28ade998ac7bee56c42e/errbot/backends/slack_rtm.py#L860

**Comment by sijis** [comment]
@medecau I thought I updated all that in another PR. Anyhow, I'll fix that up. Thanks.

**Comment by sijis** [comment]
@medecau @jeremymec would you folks be able to validate this PR resolves the issue https://github.com/errbotio/errbot/pull/1458?
