### ISSUE TITLE
AttributeError in new callback_reaction() feature.

### ISSUE THREAD

**Issue by tpgilmore** [errbotio/errbot#1466]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1.5
* OS version: MacOS 10.14.6
* Python version: 3.7.4
* Using a virtual environment: yes

### Issue description

I've been waiting a long time for an official reaction handler so with it being there now I was doing some testing. My simple initial test was:

```
    def callback_reaction(self, event):
        """Testing reaction callbacks."""

        self.log.info(event)
        slack_api_call back to channel
```

Which was in fact sending my api_call back to the channel so it was technically working, however it was also recording the error `AttributeError: 'Reaction' object has no attribute '_reaction'` (error source: `base.py`) when calling the event object (in the logging call, trying to return it as the text of my api_call message, etc). If I called to a known-good attribute it would be fine, such as using `event.reacted_to` or `event.reactor`, for example.

Looking further into it I noticed in the init the attribute in question (I believe) is set as `self._reaction_name`:

https://github.com/errbotio/errbot/blob/807cbe51ae6e898fe8833f3a643792abd00ff7fe/errbot/backends/base.py#L540-L558

But when creating the response in the `__str__()` method further down the code is using `self._reaction`:

https://github.com/errbotio/errbot/blob/807cbe51ae6e898fe8833f3a643792abd00ff7fe/errbot/backends/base.py#L606-L620

This may be completely intentional for reasons beyond my understanding and/or skill, maybe something to do with other backends, however I tested renaming `self._reaction` to `self._reaction_name` on line 610 and found that my calls to the event object stopped triggering the AttributeError entirely.

### Steps to reproduce

Call/use the returned object from the `Reaction()` class in its entirety.

**Comment by sijis** [comment]
@tpgilmore Thank you for providing the information in filing the issue, very much appreciated. 

I just created a PR https://github.com/errbotio/errbot/pull/1467, that should address it.

Would you be able to verify it works for you?

**Comment by tpgilmore** [comment]
> @tpgilmore Thank you for providing the information in filing the issue, very much appreciated.
> 
> I just created a PR #1467, that should address it.
> 
> Would you be able to verify it works for you?

My pleasure. I would have done a PR myself but I really wasn't sure if there was some deeper reasoning behind it :).

Your fix does in fact work. Thanks!
