### ISSUE TITLE
Proposal : Slack backend deprecation plan

### ISSUE THREAD

**Issue by nzlosh** [errbotio/errbot#1480]
# Description

The current situation for Slack is causing confusion for users and developers.  For example

- Multiple PRs for the same features are being created.
- Features are applied to one slack backend but not the other.
- Inconsistent behaviour between backends makes debugging confusing.
- Users must be given special instruction to create legacy tokens for use with the current slack backend.
- Both `slack` and `slack_rtm` use deprecated upstream modules.

# Proposal

I recommend a deprecation plan be put in place to correct the situation in 4 phases (each phase spanning a 2 month period)

## phase 1 (start date: 1 Dec 2020)

- Merge PR #1451 once both RTM and Event API are completely integrated as `slacksdk` backend.
- `slacksdk` start to test and stablise the backend for both RTM and Events API.
- Add warnings in log to indicate `slack` backend as deprecated for removal in 6 months.
- Add warnings in logs to indicate `slack-rtm` backend as deprecated for removal in 2 months.

## phase 2 (start date: 1 Feb 2021)
- `slacksdk` continue to test and stablise the backend for both RTM and Events API.
- `slack` remains in deprecated warning state.
- `slack_rtm` removed from errbot. (It's less tested than the `slack` backend and is the functional equivalent to `slacksdk`)

## phase 3 (start date: 3 April 2021)*
- `slacksdk` continue to test and stablise the backend for both RTM and Events API.
- rename `slacksdk` backend to `slack`.
- rename `slack` backend to `slack_legacy`. (backend remains for any users that still can't use `slacksdk`)

## phase 4 (start date: 1 June 2021)
- removal of `slack_legacy` from errbot.
- `slack` (aka `slacksdk`) remains as the only backend supporting both RTM and Events API.

*Avoid April fools day release - so people know the change isn't a joke.

**Comment by sijis** [comment]
I appreciate you taking the time and putting this together. I think the plan is a good one.

My only real concern is renaming `slacksdk` to `slack`. The main issue stems around use behavior. If users aren't aware that it changed, when an update happens things will break for them. I would be OK with just leaving the backend as `slacksdk`.

**Comment by nzlosh** [comment]
I see what you mean, keeping the backend name as `slacksdk` would be fine.  My thoughts around the name change were to have a more intuitive backend name that didn't reflect the underlying module being used would be cleaner going forward.  Keeping a distinct name will help when users report issues.

Removal of the `slack` backend will still catch unaware users off guard.  Documentation, deprecation warnings, major version bump and reasonable lead time should help to raise user awareness of the upcoming breaking change.

**Comment by nzlosh** [comment]
@agarfu @duhow You've both provided PRs for the slack events backend recently, do you have any comments on this proposal?

**Comment by duhow** [comment]
There may be people that can be still using the old Slack v1 API (RTM), but nowadays new Slack applications are enforced to use v2 Events, so probably sooner or later RTM will be deprecated.
So as long as the updated documentation clarifies this, should be good. - Just put :warning: warning and rainbow colors to catch user attention. :joy: 

Also if this matches a "major" Errbot version, it will be expected to have breaking changes like this, so they really should care about this and change if needed, for example users may be affected by their custom plugins calling to some functions in Backend that may no longer work.

Just embrace the change! :D

**Comment by nzlosh** [comment]
For anyone who may be interested, work on the slack backend has been moved here: https://github.com/nzlosh/err-backend-slackv3/ to allow iteration cycles on the backend to occur independently of the core errbot project.

**Comment by sijis** [comment]
We are not close to the suggested timelines however i'm starting with deprecation message
https://github.com/errbotio/errbot/pull/1526

All effort forward for Slack will be https://github.com/errbotio/err-backend-slackv3
