### ISSUE TITLE
PySide6 to replace PySide

### ISSUE THREAD

**Issue by kennedy** [errbotio/errbot#1491]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 616
* OS version: win10 20H2
* Python version: 3.8.6
* Using a virtual environment: yes

### Issue description

`pip install errbot[graphic]` installs `pyside` which only supports python versions `[(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]` which are no longer supported. PySide has been replaced by [PySide6](https://wiki.qt.io/Qt_for_Python).

```
pip install errbot[graphic]
...
Collecting pyside
  Using cached PySide-1.2.4.tar.gz (9.3 MB)
    ERROR: Command errored out with exit status 1:
     ...
     ...\Local\Temp\pip-install-71o4zagg\pyside_7f35ddbf4ad44cd29cad481df2aee599\
    Complete output (1 lines):
    only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]
```

```
2020-12-18 16:30:28,869 INFO     errbot.bootstrap          Found Storage plugin: Shelf.
2020-12-18 16:30:28,874 INFO     errbot.bootstrap          Found Backend plugin: Graphic
Bot-Kennedy
2020-12-18 16:30:28,946 ERROR    errbot.backends.graphic   Could not start the graphical backend
Traceback (most recent call last):
  File "...\venv\lib\site-packages\errbot\backends\graphic.py", line 18, in <module>
    from PySide import QtCore, QtGui, QtWebKit
ModuleNotFoundError: No module named 'PySide'
2020-12-18 16:30:28,946 CRITICAL errbot.backends.graphic    To install graphic support use:
    pip install errbot[graphic]
```

### Steps to reproduce

1. Run python 3.8.x interpreter
2. create virtualenv
3. install `errbot[slack,graphic]` via pip

### Additional info

None

**Comment by e4r7hbug** [comment]
I saw this Issue and started looking at how to upgrade to Qt6 Quick or Widgets. Turns out, it's a little harder than I thought it would be. Then I started thinking, Qt is designed to be similar to web development. Then I remembered Errbot is built with Flask.

It might be worth investing time into building a Web UI that would have some benefits like:

- Remove a dependency that has OS specific installations
- Utilize any web browser installed on a machine that can access the Flask HTTP port
- Reuse the core application server to serve a UI
- Provide a way for more web developers to contribute
- Web application could be easier to maintain
- There are some ways to automatically launch a browser if desired

Would a Web UI be a sufficient solution for this Issue?

**Comment by sijis** [comment]
Thanks for looking into it.

I tried a few months ago to try and migrate to pyside2 and it was tough. 

The maintenance of this backend has been minimal.

I'd be OK with a try as a webui instead.

**Comment by sijis** [comment]
Quick thought, I wonder if we could leverage something else (like pygame) Instead to get this to work.

Just spit-balling.

**Comment by nzlosh** [comment]
The graphic backend has remained largely unmaintained for over 2 years and as everyone is pointing out, there's a lack of QT development knowledge required to migrate to the latest version.  My recommendation would be to deprecate it for removal as a core plugin and isolate it as a 3rd party plugin.  It'll be there should someone want to pick it up in the future.

A WebUI is an interesting idea, but for the same reasoning that QT development should be removed, I think the WebUI should be implemented as a 3rd party plugin.  This will avoid adding complexity, another language, additional tooling and development knowledge to Errbot's core.

**Comment by e4r7hbug** [comment]
Extracting the GUI back end into a plugin makes sense to me. That would allow for independent development and Issues could be more easily targeted to that component. And in the future, if it's recognized as a defacto and well supported plugin, it could be added back in as an `extras_require` for convenience like `errbot[graphic]` is today.

Using something like Pygame would be pretty hilarious. That could help bring in some younger people and get them thinking about the internet in a whole new dimension. Who knows, it could become a competing chat platform, kind of the opposite direction of Slack going from games to chat. I would like a tiny figure that sends messages using a baseball bat to hit them out of the park, or a tiny card dealer dealing message cards. Animations and graphics would bring some fun interactivity.

**Comment by sijis** [comment]
I've created a PR to remove the backend from core https://github.com/errbotio/errbot/pull/1495.

**Comment by sijis** [comment]
Closing, as backend was removed in https://github.com/errbotio/errbot/pull/1495.
