### ISSUE TITLE
docs: Update backend homepage screenshots

### ISSUE THREAD

**Issue by sijis** [errbotio/errbot#1492]
### I am...

* [x] Here about something else

### Issue description
We should update the screenshots on the backends used on the homepage.

possible candidates

* Slack
* IRC
* Telegram

**Comment by ppinzon** [comment]
Made a PR for this, hope you like it. Also took the liberty to update the contributing documentation as it was outdated.

 https://github.com/errbotio/errbot/pull/1499

**Comment by ppinzon** [comment]
forgot to add, this is how it looks with the new screenshots. 

![image](https://user-images.githubusercontent.com/7866209/104474832-68fb1580-558c-11eb-9e0f-2703c0acfae9.png)

**Comment by sijis** [comment]
Closed via #1499.
