### ISSUE TITLE
SlackRTM channel members endpoint

### ISSUE THREAD

**Issue by gdelaney** [errbotio/errbot#1501]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1.7
* OS version: Mac 10.15.7 
* Python version: 3.8.6
* Using a virtual environment: yes

### Issue description

when trying to get the list of users in a slack channel, its throwing the following error message:
errbot.backends.base.RoomDoesNotExistError: #XXXX does not exist (or is a private group you don't have access to)

I know the room exists and the bot is a member of it. I think the issue is that the conversations.info slack endpoint used in the slackrtm backend does not contain the list of members. The slack backend uses conversations.members to return the list of members.

### Steps to reproduce

Use the SlackRTM backend and try return the list of users in a public channel

### Additional info
errbot==6.1.7
slackclient==2.9.3

Using slack on an enterprise grid/workspace.

**Comment by nzlosh** [comment]
Would you like to try the slackv3 backend https://github.com/nzlosh/err-backend-slackv3 to see if it handles your use case?

**Comment by sijis** [comment]
I strongly suggest using the slack-v3 mentioned.
