### ISSUE TITLE
[Plugins] Get data about slack user, who trigger bot

### ISSUE THREAD

**Issue by ingtarius** [errbotio/errbot#1508]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1.7
* OS version: docker python 3.8-buster
* Python version: Python 3.8.7
* Using a virtual environment: no

### Issue description

I try to write simple python plugin for errbot to collect data about user from internal sources (ldap etc)
Simple flow: user write to slack-bot command !myinfo -> plugin connect to resources and get data about user, parse it, return to user
It is secure to protect other users info from this queue (for example, i need to collect data only about myself), so i need to get information about user, who trigger bot. 
I see this information in errbot.backends.slack Processing slack event user field in debug log, how i can get this data in plugin?

**Comment by nzlosh** [comment]
I think you're looking for the command `!whoami`. It will report the Slack attributes of the user that triggered the command.

**Comment by ingtarius** [comment]
Wow! You are right
I need this info in custom plugin, so i can access in via "msg.frm.fullname" for example.
Thanks for help
