### ISSUE TITLE
`errbot --init` is failure failed when passed relative path as bot directory 

### ISSUE THREAD

**Issue by attakei** [errbotio/errbot#1510]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1.7
* OS version: Arch
* Python version: 3.9
* Using a virtual environment: no

### Issue description

If I pass sub directory when run `errbot --init`, command does not complete correctly and example plugin is not created.

### Steps to reproduce

1. Create sub directory in current working directory(anywhere).
1. Run `errbot --init` passing sub directory as relative path.

Example:

```shell-session
$ mkdir errbot-env
$ errbot --init errbot-env 
The initialization of your errbot directory failed: [Errno 2] No such file or directory: 'errbot-env/errbot-env/plugins/err-example'.
```

Patterns of reproduce: 

- Reproduce:
  - Pass relative path of children directory (any hierarchy)
  - Pass relative path of 2-step upper hierarchy (example: `../../errbot-env`)
- No reproduce:
  - Pass relative path of parent directory (example: `../errbot-env`)
  - Pass absolute path

### Additional info

I will create PR to fix it.

**Comment by sijis** [comment]
PR merged.

**Comment by sijis** [comment]
Thank you for your contribution.
