### ISSUE TITLE
command with two equals

### ISSUE THREAD

**Issue by minifygb** [errbotio/errbot#1517]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [+] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1.7
* OS version:
* Python version: Python 3.7.3
* Using a virtual environment: yes

### Issue description

Please describe your bug/feature/problem here.
The more information you can provide, the better.

I'm sending command "!st2 licensing request json data 111==" and got an error
  | 2021-05-27 09:35:33,183 DEBUG    urllib3.connectionpool    Starting new HTTP connection (1): 172.17.0.1:80
errbot_1  | 2021-05-27 09:35:33,210 DEBUG    urllib3.connectionpool    http://172.17.0.1:80 "POST /api/v1/actionalias/match HTTP/1.1" 200 1403
errbot_1  | 2021-05-27 09:35:33,212 DEBUG    urllib3.connectionpool    Starting new HTTP connection (1): 172.17.0.1:80
errbot_1  | 2021-05-27 09:35:33,261 DEBUG    urllib3.connectionpool    http://172.17.0.1:80 "POST /api/v1/aliasexecution/match_and_execute HTTP/1.1" 400 4792
errbot_1  | 2021-05-27 09:35:33,261 DEBUG    errbot.plugin.st2         action alias execution result: type=<class 'str'> Error getting execution and match:  'Response' object has no attribute 'body'
errbot_1  | 2021-05-27 09:35:33,262 ERROR    errbot.core               An error happened while processing a message ("licensing request json data 111=="): Traceback (most recent call last):
errbot_1  |   File "/app/venv/lib/python3.7/site-packages/errbot/core.py", line 552, in _execute_and_send
errbot_1  |     reply = method(msg, match) if match else method(msg, args)
errbot_1  |   File "/srv/plugins/err-stackstorm/st2.py", line 501, in <lambda>
errbot_1  |     lambda plugin, msg, args: self.st2_execute_actionalias(msg, args),
errbot_1  |   File "/srv/plugins/err-stackstorm/st2.py", line 290, in st2_execute_actionalias
errbot_1  |     result = res.get("results", [{}])[0].get("message", "")
errbot_1  | AttributeError: 'str' object has no attribute 'get'
errbot_1  | "

if I'm sending command with one "=", there is no error.

"!st2 licensing request json data 111==" and got an error
"!st2 licensing request json data 111=" no error

### Steps to reproduce

In case of a bug, please describe the steps we need to take in order to reproduce your issue.
If you cannot easily reproduce the issue please let us know and provide as much information as you can which might help us pinpoint the problem.

### Additional info

If you have any more information, please specify it here.

**Comment by nzlosh** [comment]
This is not an errbot issue, but either an err-stackstorm or StackStorm issue.  I'll create an issue in the err-stackstorm repository https://github.com/nzlosh/err-stackstorm/issues/37.  We can continue discussions there.

**Comment by sijis** [comment]
Thanks!
