### ISSUE TITLE
Officially support Python 3.10

### ISSUE THREAD

**Issue by nzlosh** [errbotio/errbot#1538]
In order to let us help you better, please fill out the following fields as best you can:

### I am...
* [X] Suggesting a new feature

### Issue description

Python3.10 was officially released 04 Oct 2021.  People are starting to report compatibility issue between errbot's code base and Python 3.10, so work should be prioritised to add support for the latest version of Python.

**Comment by sijis** [comment]
Merged in PR #1539. That's the first step to support 3.10.
