### ISSUE TITLE
Support for Serverless based deployment (AWS: Lambda + APIGateway)

### ISSUE THREAD

**Issue by rams3sh** [errbotio/errbot#1547]
### I am...

* [ ] Reporting a bug
*  [x] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 6.1.8
* OS version: Ubuntu (20.04.2 (x86_64)
* Python version: 3.8.10
* Using a virtual environment: yes

### Issue description

I have been searching for a bot framework to be used for our internal chatops operations and hit upon errbot. We were planning to host the bot framework as part of AWS lambda and API Gateway since serverless deployment would be cheaper for us , scalable and would  have less management overhead. 

I just wanted to know if this can be supported by errbot or are there any plans in the roadmap. We are in AWS and we thought of APIGateway for listening to external events and the lambda as a processing entity. 

### Additional info

I checked on this ticket https://github.com/errbotio/errbot/issues/833 and found that a similar conversation has taken place earlier. However, I wanted to bring this to attention and hence raised a new issue.

**Comment by sijis** [comment]
I think some of the questions raised are still valid in that prior discussion.

Errbot isn't designed with a serverless architecture. Errbot is actively getting and parsing through all the messages for the configured backend. I'm not sure how running errbot via lambda would work.

An approach I could think of is configuring your chat system to publish all messages to SQS and then have lambda process those messages.

The other approach that comes to mind is to configure a "slash command" (Slack for example) and have that go to an API gateway. That in turn could run errbot within lambda and process that message.

Both of these approaches are untested and theoretical.

**Comment by rams3sh** [comment]
Hey @sijis 

I understand. I was thinking on if there could be a custom  mode supported (in case there exists any plan for a  serverless roadmap) where errbot need not continously run for listening onto incoming events / messages and instead outsource this part alone to external serverless listeners supported through some sort of pluggable listeners module  (api gateway being one example in case of AWS cloud).

With the above idea , Errbot would get invoked and do computation / processing only when an external listener invokes it based on an event received by it, which would probably suit for lambda based deployment.  I understand this would probably require good amount of core changes as you had mentioned that errbot wasnt designed with serverless architecture mindset.

Sure, in that case I will close this issue. 

Thanks for providing detailed response. Really appreciate it !!
