### ISSUE TITLE
errbot connects to slack and prompts a token error!!! Help!!!!

### ISSUE THREAD

**Issue by hyithack** [errbotio/errbot#1548]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [                ] Requesting help with running my bot
* [ ] Requesting help writing plugins 
* [ ] Here about something else

### I am running...

* Errbot version:
* OS version:
* Python version: 
* Using a virtual environment: yes/no

### Issue description

Please describe your bug/feature/problem here.
The more information you can provide, the better.

### Steps to reproduce

In case of a bug, please describe the steps we need to take in order to reproduce your issue.
If you cannot easily reproduce the issue please let us know and provide as much information as you can which might help us pinpoint the problem.

### Additional info

If you have any more information, please specify it here.
![93f42f62da44f0b2a1cfc2cdbf0f3d7](https://user-images.githubusercontent.com/69373733/146669168-cabe424d-5b0f-4696-a3aa-9ca6c0102926.png)

**Comment by nzlosh** [comment]
Use the slackv3 backend for new tokens. https://github.com/errbotio/err-backend-slackv3

**Comment by nzlosh** [comment]
@hyithack can we close this issue now that you're using the slackv3 backend?

**Comment by nzlosh** [comment]
@sijis I think we can close this issue.
