### ISSUE TITLE
StoreAlreadyOpenError("Storage appears to be opened already")

### ISSUE THREAD

**Issue by mmclane** [errbotio/errbot#1586]
**Need help with**

- [ ] Running the bot
- [x] Writing plugin
- [ ] Other

**Issue description**
I am writing my first real errbot plugin.  This plugin looks up the name of the person currently oncall in pagerduty.  I want to set it up so that this runs repeatedly and the plugin remembers who it last saw.  Then if that person changes it will send a message letting us know the new person is onall.  

I have the code largely written but am having issues with this fuction:
```
    @botcmd    
    def pagerduty_activate(self, msg, args):
        super().activate()
        self.start_poller(5, self.pagerduty_repeating)
```
If I don't include the **super().activate()**, the poller doesn't seem to run.   
When I include the **super().activate()** line and run the function I get the following error.

```
An error happened while processing a message ("!pagerduty activate"): Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/errbot/core.py", line 574, in _execute_and_send
    reply = method(msg, match) if match else method(msg, args)
  File "/errbot/plugins/pagerduty/pagerduty.py", line 72, in pagerduty_activate
    super().activate()
  File "/usr/local/lib/python3.10/site-packages/errbot/botplugin.py", line 454, in activate
    super().activate()
  File "/usr/local/lib/python3.10/site-packages/errbot/botplugin.py", line 212, in activate
    self.init_storage()
  File "/usr/local/lib/python3.10/site-packages/errbot/botplugin.py", line 205, in init_storage
    self.open_storage(self._bot.storage_plugin, self.name)
  File "/usr/local/lib/python3.10/site-packages/errbot/storage/__init__.py", line 32, in open_storage
    raise StoreAlreadyOpenError("Storage appears to be opened already")
errbot.storage.StoreAlreadyOpenError: Storage appears to be opened already
```

I get the same error when I run this locally or in a container on my k8s cluster.

**Steps to reproduce**
You can see my entire bot and setup here: https://github.com/mmclane/gir  The plugin in question is: https://github.com/mmclane/gir/tree/main/plugins/pagerduty

**Environment (please complete the following information):**
- Errbot version: Errbot version 6.1.9
- OS version: "Debian GNU/Linux 11 (bullseye)"
- Python version:Python 3.10.4
- Using a virtual environment: no
- Using Docker: yes - python:3.10.4-slim

**Additional info**
If you have any more information, please specify it here.

**Comment by nzlosh** [comment]
For anyone who may come across this issue in the future, the answer was provided by @marksull via gitter.

> @mmclane you shouldn't be doing the `super().activate` in your `pagerduty_activate()` method because `activate()` would have already been called when the plugin loaded. The only time you would want to do the `super().activate()` is if you were overriding activate with your own implementation, for example, if you wanted to call your_method every 60 seconds and wanted to start this as soon as the plugin was started.
```python
def activate(self):
         super().activate()
         self.start_poller(60, self.your_method, 1)
```

**Comment by nzlosh** [comment]
Mark's spot.  Small side note, the `@botcmd` shouldn't decorate `activate` since it's not intended to be a bot command. The example already points out the use of `self.send` for bot initiated messages and you can see other examples of messaging here  https://errbot.readthedocs.io/en/latest/user_guide/plugin_development/messaging.html

**Comment by marksull** [comment]
Thanks for catching my type @nzlosh

**Comment by mmclane** [comment]
So you put super().activate() in your activate function.. but I just removed that.

**Comment by mmclane** [comment]
Ah.. but its not decorated either..

**Comment by marksull** [comment]
> So you put super().activate() in your activate function.. but I just removed that.

Read up on Python inheritance/supers. That is a Python thing not an Errbot thing.

**Comment by mmclane** [comment]
Thank you all for your help.  I believe I have this all sorted out.  If your interested you can follow the link to my git repo to see my solution.
