### ISSUE TITLE
core plugins error

### ISSUE THREAD

**Issue by futex** [errbotio/errbot#1591]
I got these errors since the update to version 6.1.9

`2022-07-07 08:56:42,658 ERROR    errbot.plugin_manager     Error loading TextCmds.
AttributeError: 'NoneType' object has no attribute 'is_activated'
2022-07-07 08:56:42,659 ERROR    errbot.plugin_manager     Error loading Utils.
AttributeError: 'NoneType' object has no attribute 'is_activated'
2022-07-07 08:56:42,660 ERROR    errbot.plugin_manager     Error loading CommandNotFoundFilter.
AttributeError: 'NoneType' object has no attribute 'is_activated'
2022-07-07 08:56:42,669 ERROR    errbot.plugin_manager     Error loading Backup.
AttributeError: 'NoneType' object has no attribute 'is_activated'
2022-07-07 08:56:42,669 ERROR    errbot.plugin_manager     Error loading Plugins.
AttributeError: 'NoneType' object has no attribute 'is_activated'
2022-07-07 08:56:42,673 ERROR    errbot.plugin_manager     Error loading Flows.
AttributeError: 'NoneType' object has no attribute 'is_activated'
2022-07-07 08:56:42,673 ERROR    errbot.plugin_manager     Error loading ChatRoom.
AttributeError: 'NoneType' object has no attribute 'is_activated'
2022-07-07 08:56:42,677 ERROR    errbot.plugin_manager     Error loading Webserver.
AttributeError: 'NoneType' object has no attribute 'is_activated'
2022-07-07 08:56:42,814 WARNING  errbot.core               Error: TextCmds failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: Utils failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: CommandNotFoundFilter failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: Backup failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: Plugins failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: Flows failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: ChatRoom failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: Webserver failed to activate: 'NoneType' object has no attribute 'is_activated'.
2022-07-07 08:56:42,814 INFO     errbot.core               Error: TextCmds failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: Utils failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: CommandNotFoundFilter failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: Backup failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: Plugins failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: Flows failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: ChatRoom failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: Webserver failed to activate: 'NoneType' object has no attribute 'is_activated'.`

I can't figured out, in config.py i have this line : CORE_PLUGINS = ('Health', 'Help', 'ACLs', 'VersionChecker') other core plugins should be disabled.

Thanks

**Comment by sijis** [comment]
If you disable the `CORE_PLUGINS` line does it work normally?

**Comment by futex** [comment]
By removed the line it works! I used python 3.8.10 on linux mint 20.3 in a venv.
Thanks you

**Comment by Janiczek** [comment]
@sijis Is there no way to let errbot initialize without trying to enable the core plugins that aren't mentioned in `CORE_PLUGINS`? So far both solutions (remove the line altogether, or add the plugins to that line) result in using the plugins. I feel like we're still missing a way to both disable these plugins _and_ not have them throw errors.
