### ISSUE TITLE
latest release of errbot depends on vulnerable dependencies

### ISSUE THREAD

**Issue by lvthillo** [errbotio/errbot#1640]
**Describe the bug**
Errbot depends on vulnerable dependencies which makes itself vulnerable.

**To Reproduce**
E.g. Snyk test

```
Testing /Users/xxx/repos/yyy...

Tested 66 dependencies for known issues, found 2 issues, 3 vulnerable paths.


Issues to fix by upgrading dependencies:

  Pin flask@2.0.2 to flask@2.2.5 to fix
  ✗ Information Exposure (new) [High Severity][https://security.snyk.io/vuln/SNYK-PYTHON-FLASK-5490129] in flask@2.0.2
    introduced by errbot@6.1.9 > flask@2.0.2 and 1 other path(s)

  Pin setuptools@60.5.0 to setuptools@65.5.1 to fix
  ✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://security.snyk.io/vuln/SNYK-PYTHON-SETUPTOOLS-3180412] in setuptools@60.5.0
    introduced by errbot@6.1.9 > setuptools@60.5.0
```

--> setuptools is already upgraded here but there is no new release.

**Expected behavior**
No vulnerabilities

**Screenshots**

**Environment (please complete the following information):**
- Errbot version: 6.1.9
- OS version: macos Ventura 13.1 (22C65)
- Python version: 3.11
- Using a virtual environment: yes
- Using Docker: yes

**Additional context**

**Comment by keenborder786** [comment]
I am looking into this issue

**Comment by sijis** [comment]
updated in latest release.
