### ISSUE TITLE
Create a new release


### ISSUE THREAD

**Issue by kayman-mk** [errbotio/errbot#1646]
Thanks for this project! It works almost out of the box.

When I installed the Bot, I ran into #1624 which has been fixed long time ago. But the release is still missing. Any chance to get one?

In case the problem is the missing GitHub workflow: Just ping me and I will submit a PR to automize it. This way a release can be created for every PR.

**Comment by kayman-mk** [comment]
I start with cloning this project into the [HapagLloyd](https://github.com/Hapag-Lloyd) space and setup an infrastructure to publish the package to [PyPi ](https://pypi.org/)to have a new release available.

**Comment by nzlosh** [comment]
@sijis is the leader maintainer for the project and has said he should have some free time to publish a new release in a few weeks time.

**Comment by kayman-mk** [comment]
That would be really cool.

**Comment by sijis** [comment]
Yes. Targeting before labor day.

**Comment by pamelin** [comment]
Hey @sijis any update on the latest release? With versions 6.1.9 we encounter issue with `werkzeug` v3.x
By the look at the latest in the repo flask is locked into 2.3.3 which locks version of `werkzeugz` to 2.3.7 which will resolve the above issue I've mentioned. 🙏

**Comment by kayman-mk** [comment]
I started some trials here: https://github.com/Hapag-Lloyd/errbot/pull/1 and have already seen the package in PyPi. Unfortunately they do not approve the organization request so I used my personal account. Have to introduce an automatic release process and then I am good to go.

This project is really cool and very helpful for us. So if any help needed let me know. I guess things would be simpler if there were some workflows for release automatization. Just let me know.

**Comment by nzlosh** [comment]
This work looks like a step in the right direction and would be a great addition to the errbot project, have you opened a PR for it?  I'd recommend removing the unofficial errbot package from pypi as it could lead to confusion for the larger community.

**Comment by kayman-mk** [comment]
@nzlosh For the time being I removed the dummy release from PyPi.

**Comment by kayman-mk** [comment]
5 month gone now without any progress. I will now go forward and publish a fork on pypi including the most urgent fixes.

https://github.com/Hapag-Lloyd/errbot/

**Comment by kayman-mk** [comment]
Got everything up an running and released version 7.0.0 including everything up to commit 0080eff1324930207f021f55674d5240abae172d (2023-10-30).

Docker image: https://github.com/Hapag-Lloyd/errbot/pkgs/container/errbot-hl/149130296?tag=7.0.0
PyPi package: https://pypi.org/manage/project/errbot-hl/release/7.0.0/

GitHub project: https://github.com/Hapag-Lloyd/errbot

Release process is 100% automatic now.

**Comment by sijis** [comment]
6.2.0 just released.
