### ISSUE TITLE
Problem with errbot and Werkzeug in raspbian bookworm and python 3.12.0

### ISSUE THREAD

**Issue by fernand0** [errbotio/errbot#1670]
**Describe the issue**

This problem is similar to #1662 since my errbot won't start with a recent version of Werkzeug.

**To Reproduce**

Just running:
    
     ~/.errbot-ve/bin/errbot --init^

**Expected behavior**

errbot should start correctly.

**Environment (please complete the following information):**
- Errbot version: 6.1.9
- OS version: raspbian bookworm
- Python version:  3.12.0
- Using a virtual environment: yes
- Using Docker: no

**Additional context**

The problem can be solved installing an older version of Werkzeug

     pip install Werkzeug==2.0

It seems to be related also with https://github.com/pallets/flask/issues/5285

**Comment by sijis** [comment]
I'm unable to reproduce on python 3.12.1 using errbot 6.2.0


```
# docker run --rm -it python:3.12 /bin/sh
# python -V
Python 3.12.1
# pip install errbot
....
# errbot --init
Your Errbot directory has been correctly initialized!
Just do "errbot" and it should start in text/development mode.
# errbot
06:40:08 INFO     errbot.bootstrap          Found Storage plugin: Shelf.
06:40:08 INFO     errbot.bootstrap          Found Backend plugin: Text
06:40:08 INFO     errbot                    webhooks: Flag to bind /echo to echo
────────────────────────────────────────────────────────────────────────────────
 You start as a bot admin in a one-on-one conversation with the bot.

    Context of the chat

• Use !inroom to switch to a room conversation.
• Use !inperson to switch back to a one-on-one conversation.
• Use !asuser to talk as a normal user.
• Use !asadmin to switch back as a bot admin.

    Preferences

• Use !ml to flip on/off the multiline mode (Enter twice at the end to send).
────────────────────────────────────────────────────────────────────────────────

[@CHANGE_ME ➡ @errbot] >>> !uptime
I've been up for 7 seconds (since Saturday, Jan 27 at 06:40).

[@CHANGE_ME ➡ @errbot] >>>
```

The version of Werkzeug has been updated, as it now `3.0.1`. We also updated the core dependencies in https://github.com/errbotio/errbot/pull/1651 which would have likely fixed this too.
