### ISSUE TITLE
Is errbot project still actively maintained?

### ISSUE THREAD

**Issue by dtserekhman** [errbotio/errbot#1672]
Hi,

Is errbot project still actively maintained? I see the last release (v6.1.9) dated Jun 11, 2022. There're some pull requests opened within a year which are still pending to merge.

So, just curious if the project will keep on-going?

Thanks.

**Comment by dtserekhman** [comment]
Thanks for the response. Should it not be a good cadence to tag master whenever a merge done into it, at least with the patch version release?

**Comment by sijis** [comment]
Release 6.2.0 was just released.

**Comment by dtserekhman** [comment]
Thank you! Just fyi, this release is not yet marked as "Latest" and does not show in the "Release Notes" yet.

**Comment by sijis** [comment]
@dtserekhman thanks for the reminder. updated.

**Comment by dtserekhman** [comment]
Great, thank you!
