### ISSUE TITLE
errbot 6.2.0 image is arm64 only?

### ISSUE THREAD

**Issue by barrygear** [errbotio/errbot#1677]
**Describe the bug**
The published container seems to be arm64 only even though its listed as linux/amd64

**To Reproduce**
Pull the image and check it using docker inspect

**Expected behavior**
A multi-arch build is created and pushed

**Environment (please complete the following information):**
- Errbot version: 6.2.0
- OS version: linux, macos
- Python version: n/a
- Using a virtual environment: n/a
- Using Docker: yes

**Additional context**
```
$ docker run --platform linux/amd64 errbotio/errbot:6.2.0
Unable to find image 'errbotio/errbot:6.2.0' locally
6.2.0: Pulling from errbotio/errbot
Digest: sha256:73a4e5a4d13c2e88757c4bca4860b25f60ca6feb25c2e5201126339364819f0d
Status: Image is up to date for errbotio/errbot:6.2.0
docker: Error response from daemon: image with reference errbotio/errbot:6.2.0 was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64/v8.
```

**Comment by sijis** [comment]
@barrygear whoops. missed that! Uploaded a multi-platform build that includes an arm64 and amd64 builds.
