### ISSUE TITLE
 No dependency version for python-telegram-bot is specified in the Documentation

### ISSUE THREAD

**Issue by kindejak** [errbotio/errbot#1682]
**Description:**
The current [documentation ](https://errbot.readthedocs.io/en/latest/user_guide/configuration/telegram.html) for installing the python-telegram-bot dependency lacks specification for the required version. This leads to unintended behavior where version 20.8 is installed by default when installing via pip, causing compatibility issues with errbot, specifically resulting in the error "AttributeError: 'coroutine' object has no attribute 'id'".

Suggested Solution:
Update the documentation to specify that the python-telegram-bot dependency, either:
`pip install python-telegram-bot==13.15`
or
`pip install errbot[telegram]`

**Comment by nzlosh** [comment]
This sounds reasonable, would you mind opening a pull request with the suggested changes? https://github.com/errbotio/errbot/blob/master/docs/user_guide/configuration/telegram.rst

**Comment by sijis** [comment]
@kindejak thanks for noting it. I created a PR for it. Thank you.
