### ISSUE TITLE
File transfer API

### ISSUE THREAD

**Issue by gbin** [errbotio/errbot#280]
tox and irc have support now, we miss XMPP

**Comment by gbin** [comment]
Ping on this one ? Any started work we can contribute on ?

**Comment by lukmdo** [comment]
sorry I suck - unless Its holding then yep I would love to het that going
done. will make work in progress branch

**Comment by gbin** [comment]
A partial support has landed for IRC, I rename this bug.

**Comment by gbin** [comment]
If it is missed on a specific backend open a specific bug.
