### ISSUE TITLE
How to disable IPv6 in sleekxmpp?

### ISSUE THREAD

**Issue by vkuusk** [errbotio/errbot#327]
What is the correct way to disable the use of IPv6 in sleekxmpp?

I'm installing ERR on Ubuntu 14.04 using pip and connecting it to HipChat.
After the default install of sleekxmpp Err tries to use IPv6, and the only way which I could find how to disable usage of IPv6 was to modify the sleekxmpp source directly:

> sudo  pip install sleekxmpp
> sudo  sed -i s/"self.use_ipv6 = True"/"self.use_ipv6 = False"/g /usr/local/lib/python2.7/dist-packages/sleekxmpp/xmlstream/xmlstream.py

Is there a setting in Err config.py to do it?

Thx

**Comment by gbin** [comment]
I see that the resolver from SleekXmpp has this parameter : https://github.com/fritzy/SleekXMPP/blob/develop/sleekxmpp/xmlstream/resolver.py#L56

We use it already for the SRV records, maybe we could use it across the board and forward this parameter for the XMPP backend.

@zoni, what do you think ?

**Comment by zoni** [comment]
I don't see any problem in passing it on to the XMPP backend. I would suggest making it a configuration option [like these](https://github.com/gbin/err/blob/master/errbot/config-template.py#L208-L255) here. Something like `XMPP_DISABLE_IPV6=False` or `DISABLE_IPV6=False` with a clear warning that it only works for the xmpp-based (xmpp itself and hipchat) backends right now.

**Comment by zoni** [comment]
This was implemented in #867.
