### ISSUE TITLE
mattermost.org backend

### ISSUE THREAD

**Issue by gbin** [errbotio/errbot#390]

**Comment by zoni** [comment]
Mattermost is still very much in its infancy, I think we should wait and see how it matures first, or let a member of the community write a back-end for it now that we have a pluggable back-end architecture.

If anyone wants mattermost support and wishes to implement a back-end for it, I'm obviously willing to help him or her get started.

**Comment by gbin** [comment]
agreed

**Comment by vmillet** [comment]
Hi,
We use both mattermost and errbot (with jabber) at my work. So I am  interesting to give a try on writing a mattermost backend, if it is not already done.
Let me know if anyone is working on it...

**Comment by gbin** [comment]
@vmillet sure ! Feel free to join us on the chatroom if you have questions about designing a backend.

**Comment by gbin** [comment]
Any progress on this @vmillet ?

**Comment by vmillet** [comment]
Not much...
For the moment, I took a look at the api documentation of mattermost, here
: https://github.com/mattermost/platform/blob/master/doc/developer/API.md,
and here :
https://github.com/mattermost/platform/blob/master/doc/developer/API-Web-Service.md
I read in the documentation that Mattermost provides an API with a Slack
compatibility. So I try to  connect the slack backend on it.
The authentification part is different so I change it. But now, it seems
that there is no Real Time Messaging api in Mattermost for the moment. This
part was used for the slack backend.
So, I don't know if I need to go as far as the slack backend did :Maybe I
can only use Mattermost Outgoing webhook to get errbot triggered on demand
(and it will answer through Incoming webhook)
What do you think?

2015-12-30 1:06 GMT+01:00 Guillaume Binet <notifications@github.com>:

**Comment by gbin** [comment]
Like the discord backend, I am willing to give it a shot if somebody that uses the backend daily takes over the maintenance. Any volunteer?

**Comment by Ewurama** [comment]
@vmillet <https://github.com/vmillet>

I read you are using mattermost. I have installed mattermost server and implemented the incoming webhooks successfully. 
My next step is to use hubot-mattermost to customise bots for my mattermost server. When I run **"bin/hubot   -a   mattermost"**  I get the response below 

**v3nd1tt@v3nd1tt:~/nursbot$ bin/hubot -a mattermost
[Mon Jun 27 2016 09:46:05 GMT+0000 (GMT)] ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web-url | cut -d= -f2)`
[Mon Jun 27 2016 09:46:05 GMT+0000 (GMT)] INFO hubot-redis-brain: Using default redis on localhost:6379
**

Also this is my environment variable settings (which i placed inside my /bin/hubot file for them to be executed on start):
export MATTERMOST_ENDPOINT='/enterprise-nurs/channels/town-square'
export MATTERMOST_INCOME_URL='http://192.168.1.11:8065/hooks/jntzd8ub6inieurntsfp5mxbww'
export MATTERMOST_TOKEN='rds3m7jtrtrtjrk45ou9jc'
export MATTERMOST_ICON_URL='https://s3-eu-west-1.amazonaws.com/renanvicente/toy13.png'
export MATTERMOST_HUBOT_USERNAME='matterbot'

But im not able to access the bot in mattermost server. Kindly help me figure what i may be doing wrong

I used the tutorials here :  https://github.com/renanvicente/hubot-mattermost

**Comment by gbin** [comment]
Hi @Ewurama,

We would gladly help but this is the issue tracker for Errbot (http://errbot.io) and not hubot (https://hubot.github.com/). You can file a bug at https://github.com/renanvicente/hubot-mattermost/issues
Also, just to be sure, be really careful if the TOKEN and info are real because you posted them in a public forum.

Good luck !

**Comment by zoni** [comment]
@Vaelor has started work on a backend implementation for mattermost, available at [Vaelor/errbot-mattermost-backend](https://github.com/Vaelor/errbot-mattermost-backend). :heart:  Please try it out and report your successes and failures there.
