### ISSUE TITLE
Manage ACLs by chat

### ISSUE THREAD

**Issue by gbin** [errbotio/errbot#450]
from an admin_only messages an admin should be able check and add access for a user.

**Comment by boidolr** [comment]
Should this be to only add admins? Or to modify all ACLs?
Should these changes be persisted in plugin store or be lost on restart? Having them persist might lead to strange issues, as they can't easily be seen in the configuration itself.

**Comment by gbin** [comment]
I was thinking to move this config to the config to the storage. It could be set at install time with the CLI provisioning if needed.

**Comment by zoni** [comment]
For ACLs, I'm not so sure that would be suitable. At least, we'd need to have a way in which the order of entries can be set/preserved (you can currently use an `OrderedDict` directly in the config for that).

**Comment by sijis** [comment]
This plugin may be useful for something like this
https://github.com/arouene/err-profiles
