### ISSUE TITLE
Disconnects constantly then dies

### ISSUE THREAD

**Issue by xsrender** [errbotio/errbot#457]
I'm having an issue where the bot will disconnect and reconnect multiple times a day, then at some point it will disconnect and never reconnect.  This has been running fine for a few months now with no issues until the last week or so.  I ran it for a day not in daemon mode and this was the output.

Any advice?

18:20:58 INFO     errbot.errBot             Plugin activation done.
18:20:58 WARNING  sleekxmpp.plugins.xep_000 Form.getXML() is deprecated API compatibility with plugins/old_0004.py
18:20:58 WARNING  sleekxmpp.plugins.xep_000 Form.getXML() is deprecated API compatibility with plugins/old_0004.py
Exception in thread event_thread_0:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sleekxmpp/xmlstream/xmlstream.py", line 1671, in _event_runner
    orig = copy.copy(args[0])
  File "/usr/lib/python2.7/copy.py", line 80, in copy
    return copier(x)
  File "/usr/local/lib/python2.7/dist-packages/sleekxmpp/xmlstream/stanzabase.py", line 1589, in __copy__
    return self.__class__(xml=copy.deepcopy(self.xml),
  File "/usr/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/usr/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/usr/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/usr/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 256, in _deepcopy_dict
    for key, value in x.iteritems():
RuntimeError: dictionary changed size during iteration

18:21:58 INFO     sleekxmpp.xmlstream.xmlst Waiting for </stream:stream> from server
18:21:58 INFO     errbot.errBot             Disconnect callback, deactivating all the plugins.
18:23:06 INFO     sleekxmpp.xmlstream.xmlst Waiting for </stream:stream> from server
18:23:06 INFO     errbot.errBot             Disconnect callback, deactivating all the plugins.
18:24:33 INFO     sleekxmpp.xmlstream.xmlst Waiting for </stream:stream> from server
18:24:33 INFO     errbot.errBot             Disconnect callback, deactivating all the plugins.
18:25:45 INFO     sleekxmpp.xmlstream.xmlst Waiting for </stream:stream> from server
18:25:45 INFO     errbot.errBot             Disconnect callback, deactivating all the plugins.
18:26:46 ERROR    sleekxmpp.xmlstream.xmlst Socket Error #104: Connection reset by peer
18:26:46 WARNING  sleekxmpp.xmlstream.xmlst Failed to send </stream:stream>
18:26:46 INFO     errbot.errBot             Disconnect callback, deactivating all the plugins.

**Comment by benhoff** [comment]
This is an issue with sleekxmpp, not errbot. Might try upgrading you sleekxmpp?

`pip install sleekxmpp --upgrade` if I remember correctly.

**Comment by gbin** [comment]
any update on this ? can we close it ?

**Comment by xsrender** [comment]
Requirement already up-to-date: sleekxmpp in
/usr/local/lib/python2.7/dist-packages

I reinstalled Err and it made these issue less frequent so I can deal with
it now, go ahead and close it.

**Comment by gbin** [comment]
If it is still an issue, please open a bug on sleekxmpp, maybe we do something on it too, they might have more info about that.
