### ISSUE TITLE
Add an option for xhtml-im support

### ISSUE THREAD

**Issue by gbin** [errbotio/errbot#467]
xhtml-im support has been disabled on errbot (way too rocky between clients etc...).

This request is to readd it behind an option.

Please +1 it if you think you need it.

**Comment by zoni** [comment]
Personally I'm +1 on this.

**Comment by gbin** [comment]
I think the only possible implementation would be by detecting client compatibility and have one grammar per client.

It is defined by http://www.xmpp.org/extensions/xep-0071.html and tables, li etc... are all there.

But here is an example of how it is rendered in Adium:

![image](https://cloud.githubusercontent.com/assets/975564/9688168/6aba394e-52e2-11e5-8388-aeeb0658ec18.png)

basically only `<strong>` is supported from the entire spec.

**Comment by Eagllus** [comment]
+1

**Comment by brycied00d** [comment]
:+1:  I really appreciated this functionality and was saddened to see it removed with 3.0.0. I never experienced any sort of rendering issue with Errbot 2.2.1 and clients Pidgin (2.8.x, 2.10-devel), irssi-xmpp, Profanity, Conversations, or Gajim (sorry I don't have version numbers readily available for them) in both direct and MUC chats; the client always seemed to pick whichever format it was capable of displaying (eg: Pidgin and xhtml-im). Personally I was using it to announce internal development events and the ability to embed hyperlinks in the hash, links to the project, links to the diff range etc was really useful in expanding the amount of information a single message could convey.

**Comment by vancheese** [comment]
+1

**Comment by gbin** [comment]
Please give it a shot, if there are any markdown to xhtml than is suboptimal, we can always customize the renderer.
