### ISSUE TITLE
Ability to change status/away message

### ISSUE THREAD

**Issue by Kromey** [errbotio/errbot#512]
While a bot being always online/"Available" of course makes sense, it would be really neat to have the ability to change the bot's status e.g. as a means of giving it more "character" -- would be fun to watch a "bored" bot that nobody's interacted with in a while wander off to make flapjacks!

Currently the other way 'round (receiving status updates from users) is implemented via the [Presence](https://github.com/gbin/err/blob/master/errbot/backends/base.py#L209) object; perhaps some of that could be reused to enable changing the bot's own presence via plugin commands, pollers, etc.

**Comment by gbin** [comment]
done in v3.2 see change_presence
