### ISSUE TITLE
Hangouts with XMPP backend or there's other way? 

### ISSUE THREAD

**Issue by L3K0V** [errbotio/errbot#549]
Hello, I'm new here with Err bot and I'm trying to configure Err bot backend to connect to Hangouts using XMPP. There are news that Hangouts doesn't support XMPP anymore. 

Is there any chance or some sample how to configure Err bot to use Hangouts?

Some log:
```
12:40:36 INFO     errbot.storage            Opened shelf of XMPPBackend at /Users/lekov/Workspace/elsys/errbot/core.db
12:40:36 INFO     errbot.storage            Init shelf of ACLS
12:40:36 INFO     errbot.storage            Init shelf of Backup
12:40:36 INFO     errbot.storage            Init shelf of ChatRoom
12:40:36 INFO     errbot.storage            Init shelf of Health
12:40:36 INFO     errbot.storage            Init shelf of Help
12:40:36 INFO     errbot.storage            Init shelf of Plugins
12:40:36 INFO     errbot.storage            Init shelf of Utils
12:40:36 INFO     errbot.storage            Init shelf of VersionChecker
12:40:36 INFO     errbot                    webhooks:  Flag to bind /echo to echo
12:40:36 INFO     errbot.storage            Init shelf of Webserver
12:40:36 ERROR    sleekxmpp.xmlstream.xmlst Could not connect to [2a00:1450:400c:c09::7d]:5222. Socket Error #65: No route to host
12:40:36 INFO     sleekxmpp.xmlstream.xmlst Negotiating TLS
12:40:36 INFO     sleekxmpp.xmlstream.xmlst Using SSL version: TLS 1.0
12:40:36 ERROR    sleekxmpp.xmlstream.xmlst Socket Error #2: No such file or directory
12:40:36 INFO     sleekxmpp.xmlstream.xmlst Waiting for </stream:stream> from server
12:40:40 INFO     errbot.errBot             Disconnect callback, deactivating all the plugins.
```

For XMPP configuration server I use: 
`xmpp.l.google.com,5222`

Also I found:
https://github.com/tdryer/hangups

and a hangouts bot:
https://github.com/xmikos/hangupsbot

Can I use them somehow with Err?

Thanks.

**Comment by benhoff** [comment]
Pretty sure you'd have to make your own backend. Look into subclassing `Backend` from https://github.com/errbotio/errbot/blob/master/errbot/backends/base.py

**Comment by L3K0V** [comment]
For now I will give up on Err on Hangouts, but thanks again!

**Comment by benhoff** [comment]
For posterity as I wasn't clear enough, You'd have to subclass `Backend` using https://github.com/tdryer/hangups, as Google hangout has migrated from xmpp.

**Comment by gbin** [comment]
Message from the googler me: I cannot condone the usage of an unsupported API.
Message from the errbot maintainer: please have a blast and do it :)
