### ISSUE TITLE
XMPP backend does not ignore its own messages.

### ISSUE THREAD

**Issue by brycied00d** [errbotio/errbot#558]
This appears to be a regression of #99 and #247. Debug output below shows SEND followed by RECV back from the server and subsequent processing and matching of the RECV message.

```
00:23:45 DEBUG    MyTest     Bryce Chidester has just updated issue \#3043 "Test Issue"
00:23:45 DEBUG    errbot.errBot             Trigger callback_message on Webserver
00:23:45 DEBUG    errbot.errBot             Trigger callback_message on Plugins
00:23:45 DEBUG    errbot.backends.xmpp      This is a groupchat message, strip the resource.
00:23:45 DEBUG    errbot.backends.xmpp      send_message to firehose@conference.company.local
00:23:45 DEBUG    errbot.backends.xmpp      build reply ...
00:23:45 DEBUG    sleekxmpp.xmlstream.xmlst SEND: <message type="groupchat" to="firehose@conference.company.local" xml:lang="en"><body>Bryce Chidester has just updated issue #3043 &quot;Test Issue&quot;</body></message>
00:23:45 DEBUG    errbot.backends.xmpp      send_message to bryce.chidester@company.local/Pidgin_two
00:23:45 DEBUG    sleekxmpp.xmlstream.xmlst RECV: <message from="firehose@conference.company.local/ErrBot" type="groupchat" to="errbot@company.local/Bot" xml:lang="en"><body>Bryce Chidester has just updated issue #3043 &quot;Test Issue&quot;</body></message>
00:23:45 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: message
00:23:45 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: groupchat_message
00:23:45 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: muc::firehose@conference.company.local::message
00:23:45 DEBUG    errbot.backends.xmpp      incoming_message frm : firehose@conference.company.local/ErrBot
00:23:45 DEBUG    errbot.backends.xmpp      incoming_message frm node: firehose
00:23:45 DEBUG    errbot.backends.xmpp      incoming_message frm domain: conference.company.local
00:23:45 DEBUG    errbot.backends.xmpp      incoming_message frm resource: ErrBot
00:23:45 DEBUG    errbot.errBot             *** frm = firehose@conference.company.local/ErrBot
00:23:45 DEBUG    errbot.errBot             *** username = firehose@conference.company.local/ErrBot
00:23:45 DEBUG    errbot.errBot             *** type = groupchat
00:23:45 DEBUG    errbot.errBot             *** text = Bryce Chidester has just updated issue #3043 "Test Issue"
00:23:45 DEBUG    errbot.errBot             Matching 'Bryce Chidester has just updated issue #3043 "Test Issue"' against '(^|\s)#(\d+)' produced a match
```
(and so on)

**Comment by brycied00d** [comment]
Line 219 of `errBot.py` looks like it's supposed to try and avoid this, but clearly something isn't working right.
```
        if (frm.person == self.bot_identifier.person or
            type_ == "groupchat" and mess.frm.nick == self.bot_config.CHATROOM_FN):  # noqa
                log.debug("Ignoring message from self")
                return False
```
I added a bit of good old fashioned printf debugging (prefixed with XXX) and these are the values:
```
03:17:03 DEBUG    errbot.errBot             XXX bot_identifier = ErrBot@company.local/Bot
03:17:03 DEBUG    errbot.errBot             XXX type_ = groupchat
03:17:03 DEBUG    errbot.errBot             XXX mess.frm.nick = firehose
03:17:03 DEBUG    errbot.errBot             XXX self.bot_config.CHATROOM_FN = ErrBot
03:17:03 DEBUG    errbot.errBot             *** frm = firehose@conference.company.local/ErrBot
03:17:03 DEBUG    errbot.errBot             *** username = firehose@conference.company.local/ErrBot
03:17:03 DEBUG    errbot.errBot             *** type = groupchat
03:17:03 DEBUG    errbot.errBot             *** text = Test Bug #3043 (Fixed)
```
As we can see, the XMPP backend is saying the message is "from" the MUC JID, both in `mess.frm.nick` and `frm`.

Maybe `errBot.py` isn't the right place to be checking whether a message is from itself, maybe the fault and fix lie in `xmpp.py`. Maybe you have some thoughts or insight on this?

**Comment by gbin** [comment]
In the case of a groupchat message we should receive a XMPPMUCOccupant and there XMPPMUCOccupant.nick should be the resource, but nothing is redefined there so it gets the node.

Can you check this fix ?

**Comment by brycied00d** [comment]
I can confirm that both `mess.frm` and `frm` are of class `XMPPMUCOccupant`

Digging into `xmpp.py` I see that `.frm` and `.to` are set to `XMPPMUCOccupant`s but there's no special handling of resource/nick in those objects.
```
        if msg.type == 'groupchat':
            # those are not simple identifiers, they are muc occupants.
            msg.frm = XMPPMUCOccupant(msg.frm.node, msg.frm.domain, msg.frm.resource)
            msg.to = XMPPMUCOccupant(msg.to.node, msg.to.domain, msg.to.resource)
        msg.nick = xmppmsg['mucnick']
```

 **However** I see that `.nick` gets set to the MUC nick and confirmed that it contains the proper value
```
14:11:25 DEBUG    errbot.errBot             XXX mess.frm.nick = firehose
14:11:25 DEBUG    errbot.errBot             XXX mess.frm.resource = ErrBot
14:11:25 DEBUG    errbot.errBot             XXX self.bot_config.CHATROOM_FN = ErrBot
14:11:25 DEBUG    errbot.errBot             XXX mess.frm(class) = XMPPMUCOccupant
14:11:25 DEBUG    errbot.errBot             XXX frm(class) = XMPPMUCOccupant
14:11:25 DEBUG    errbot.errBot             XXX mess.nick = ErrBot
```

So it appears that `errBot.py` should be checking `mess.nick` instead of `mess.frm.nick`.

**Comment by gbin** [comment]
I was thinking about something like that: https://github.com/errbotio/errbot/commit/112fa9189b64f585823f8ed188a11e0c22763ee2

**Comment by gbin** [comment]
It works for me:
2015-12-04 10:13:21,361 DEBUG    sleekxmpp.xmlstream.xmlstream RECV: <message type="groupchat" from="errbot@rooms.blah.im/err" to="err@blah.im/fbdd4aa2-ce8b-461c-820a-7be887c779ed" xml:lang="en"><body>!test self</body></message>
2015-12-04 10:13:21,362 DEBUG    sleekxmpp.xmlstream.xmlstream Event triggered: message
2015-12-04 10:13:21,362 DEBUG    sleekxmpp.xmlstream.xmlstream Event triggered: groupchat_message
2015-12-04 10:13:21,362 DEBUG    sleekxmpp.xmlstream.xmlstream Event triggered: muc::errbot@rooms.blah.im::message
2015-12-04 10:13:21,362 DEBUG    errbot.backends.xmpp      incoming_message frm : errbot@rooms.blah.im/err
2015-12-04 10:13:21,362 DEBUG    errbot.backends.xmpp      incoming_message frm node: errbot
2015-12-04 10:13:21,362 DEBUG    errbot.backends.xmpp      incoming_message frm domain: rooms.blah.im
2015-12-04 10:13:21,362 DEBUG    errbot.backends.xmpp      incoming_message frm resource: err
2015-12-04 10:13:21,363 DEBUG    errbot.errBot             Ignoring message from self

**Comment by gbin** [comment]
should be fixed, please reopen if it is not
