### ISSUE TITLE
BotPluginManager doesn't shut down properly on exit

### ISSUE THREAD

**Issue by ng-aaron** [errbotio/errbot#559]
I noticed this because I was trying to get plugin configurations to persist across errbot restarts. Since the configs are stored in core.db, I suppose it would require BotPluginManager to shut down properly using the shutdown function at:

https://github.com/errbotio/errbot/blob/master/errbot/plugin_manager.py#L487

But that function never gets called. I don't see it's log messages showing up in a clean shutdown (SIGINT).

I would try to submit a PR, but I'm not sure where that function should get called.

**Comment by gbin** [comment]
I gonna take this one, the shutdown method is called from the backends but somewhat it doesn't work. Thx !

**Comment by gbin** [comment]
So by adding shutdown in the contract for the backends in base.py I masked the real shutdown from the bot. That's why it never got called.
