### ISSUE TITLE
Mention callback for bundled backends tracking bug

### ISSUE THREAD

**Issue by gbin** [errbotio/errbot#572]
Implement the callback_mention on the following backends:

- [x] Text
- [x] Graphic
- [x] Slack
- [x] Hipchat
- [x] IRC
- [x] Telegram
- [ ] XMPP

**Comment by mrshu** [comment]
@gbin I'll take IRC.

**Comment by qlixed** [comment]
mrshu, please use the on_* events from the irc module. I'm fixing some of the current callbacks code and use them for better reliability.

**Comment by mrshu** [comment]
@qlixed well, i added the mention callback for IRC already in the PR mentioned above. Does the IRC lib support some sort of `on_` callback for mention?

**Comment by qlixed** [comment]
Oh, gosh, sorry, for Mention there is no on_* event. My bad! (long day)

**Comment by mrshu** [comment]
No problem @qlixed, please keep the questions coming!

**Comment by zoni** [comment]
Going to mark Telegram as "done" because it's not currently possible to implement with the limited API available to bots.

**Comment by qlixed** [comment]
Callback mention on IRC don't work properly please see #681

**Comment by qlixed** [comment]
The mention Callback Is fixed for IRC

**Comment by gbin** [comment]
Hipchat is done, XMPP seems to have something for mentions in an obscure XEP probably nobody implements, I'll skip it for now. If somebody really needs this please open another bug.
