### ISSUE TITLE
The setting AUTOINSTALL_DEPS should be documented

### ISSUE THREAD

**Issue by asfaltboy** [errbotio/errbot#576]
It is currently mentioned only briefly in [the changelog for 2.2.0](http://errbot.io/changes.html?highlight=autoinstall_deps#v2-2-0-2015-05-16). I believe it should be made easier to find (if not default to True), so I'd put it in the [_Interacting with the bot_ section](http://errbot.io/user_guide/interaction.html).

**Comment by zoni** [comment]
It's also quite [well documented](https://github.com/errbotio/errbot/blob/master/errbot/config-template.py#L64-L72) in the `config.py` template, but it's certainly a good thing to add to the documentation as well to improve visibility.

**Comment by asfaltboy** [comment]
:+1: Missed that, thanks for pointing it out
