### ISSUE TITLE
Sending to rooms from self.rooms() is neither user friendly nor generic across backends

### ISSUE THREAD

**Issue by zoni** [errbotio/errbot#581]
Consider a plugin which wishes to send a message to all the rooms the bot is in. Ideally one would be able to do:

```python
for room in self.rooms():
    self.send(room, "Example message", message_type="groupchat")
```

Unfortunately, this doesn't work.

What you can do on XMPP/HipChat:

```python
for room in self.rooms():
    self.send(room.jid, "Example message", message_type="groupchat")
```

Or on IRC:

```python
for room in self.rooms():
    self.send(room.room, "Example message", message_type="groupchat")
```

Note that on XMPP it's `room.jid` while on IRC it is `room.room`. This means that in order to send a message to joined rooms, you need different logic depending on the backend, which is not acceptable. We need to make this more user friendly so that just using the identifiers returned by `self.rooms()` works as described in the first example.

**Comment by zoni** [comment]
Background context: https://plus.google.com/u/0/107842018321255863598/posts/Md9ibmgT4pF?cfem=1

**Comment by gbin** [comment]
This is terrible, MUCRoom needs to be also an Identifier indeed.
build_identifier might need to accept room identifiers too and return a MUCRoom if we can distinguish them.

**Comment by gbin** [comment]
message_type is kinda redundant too, if we distinguish room identifiers from individuals, we already have this info.

**Comment by zoni** [comment]
> message_type is kinda redundant too, if we distinguish room identifiers from individuals, we already have this info.

Yep, that's very true. It would simplify a bunch of things for plugin authors.

**Comment by gbin** [comment]
This is basically done +/- the stabilization work.
