### ISSUE TITLE
Gitter backend is missing change_presence, and prefix_groupchat_reply

### ISSUE THREAD

**Issue by ifigotin** [errbotio/errbot#582]
The exception is as follows:

3:06:47 ERROR    errbot.main               Unable to configure the backend, please check if your config.py is correct.

err/errbot/backend_manager.py", line 87, in get_backend_by_name
    raise Exception("Could not find the backend '%s'." % name)
Exception: Could not find the backend 'Gitter'.

**Comment by gbin** [comment]
should be on the gitter backend, move it to https://github.com/errbotio/err-backend-gitter/issues/3
