### ISSUE TITLE
Restore from backup broken

### ISSUE THREAD

**Issue by ethan-eb** [errbotio/errbot#586]
root@3a896e06ae95:/srv/opsbot# pip freeze | grep errbot
    errbot==3.2.2
    root@3a896e06ae95:/srv/opsbot# cat /var/lib/err/backup.py 
    ## This file is not executable on its own. use err.py -r FILE to restore your bot.

    log.info("Restoring webserver config")
    bot["configs"] = {u'Webserver': {'SSL': None, 'HOST': 'localhost', 'PORT': 3141}}
    log.info("Installing plugins.")
    if "repos" in bot:
      for repo in bot["repos"]:
      errors = bot.install_repo(repo)
      for error in errors:
        log.error(error)
    log.info("Restoring plugins data.")

    root@3a896e06ae95:/srv/opsbot# /usr/local/bin/errbot -c /srv/opsbot/settings/dev-config.py -r

A this point I see a series of INFO messages from backend_manger, including `INFO:errbot.main:Found Backend plugin: 'Null'` ... then a series of yapsy WARNING's for each backend saying `rejected by strategy 'SpecificBackendLocator'` and finally two ERROR messages as seen below. When I then start up errbot without `-r` the webserver is not set up...

    ERROR:yapsy:Unable to create plugin object: /usr/local/lib/python2.7/dist-packages/errbot/backends/null
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/yapsy/PluginManager.py", line 512, in loadPlugins
        plugin_info.plugin_object = self.instanciateElement(element)
      File "/usr/local/lib/python2.7/dist-packages/errbot/backend_manager.py", line 65, in instanciateElement
        return element(self._config)
    TypeError: Can't instantiate abstract class NullBackend with abstract methods build_reply, prefix_groupchat_reply, query_room, rooms
    19:09:06 ERROR    yapsy                     Unable to create plugin object: /usr/local/lib/python2.7/dist-packages/errbot/backends/null
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/yapsy/PluginManager.py", line 512, in loadPlugins
        plugin_info.plugin_object = self.instanciateElement(element)
      File "/usr/local/lib/python2.7/dist-packages/errbot/backend_manager.py", line 65, in instanciateElement
        return element(self._config)
    TypeError: Can't instantiate abstract class NullBackend with abstract methods build_reply, prefix_groupchat_reply, query_room, rooms
    ERROR:errbot.main:Unable to configure the backend, please check if your config.py is correct.
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/errbot/main.py", line 56, in setup_bot
        bot = bpm.get_backend_by_name(backend_name)
      File "/usr/local/lib/python2.7/dist-packages/errbot/backend_manager.py", line 88, in get_backend_by_name
        raise Exception(u"Could not find the backend '%s'." % name)
    Exception: Could not find the backend 'Null'.
    19:09:06 ERROR    errbot.main               Unable to configure the backend, please check if your config.py is correct.
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/errbot/main.py", line 56, in setup_bot
        bot = bpm.get_backend_by_name(backend_name)
      File "/usr/local/lib/python2.7/dist-packages/errbot/backend_manager.py", line 88, in get_backend_by_name
        raise Exception(u"Could not find the backend '%s'." % name)
    Exception: Could not find the backend 'Null'.

**Comment by gbin** [comment]
Ok it is quite easy, the null backend misses a few useless methods for it :  build_reply, prefix_groupchat_reply, query_room, rooms, can you try to just add those doing nothing ? (pass) it shoudl fix it

**Comment by ethan-eb** [comment]
Ok, that seems to work, I can send a PR

However, I also had another problem along the way: main.py checks `if 'repos' in bot:` (... I am running on 2.7 and in the pip installed errbot it became `u'repos'` (due to 3to2?)). The shelve db will not accept a unicode key.

I fixed this with:

    def __contains__(self, x):
        return str(x) in self.shelf

in storage.py. 

Let me know if there is a better way, or if I should send PR request with that str(), thanks!

**Comment by gbin** [comment]
Yes please in 2 different PRs if possible.
It looks like our backup test is a false positive it should have caught both of those errors !

**Comment by ethan-eb** [comment]
Ok - PR for this issue linked above... for the storage key issues the PR is https://github.com/errbotio/errbot/pull/588 sorry I didn't have time to look at tests this morning, just going to send these PRs for now!

**Comment by gbin** [comment]
What is the status on that ? Do we need to patch the backup generation of py2 specifically maybe ?

**Comment by 1stvamp** [comment]
Is there any plan to do a new release of errbot with the Null backend fix in? I'm working on a juju charm for deploying errbot, with the ability to instantiate a fresh deploy with plugin config using the backup functionality, and this is breaking that.

**Comment by ethan-eb** [comment]
Ah sorry to have gotten distracted ... it looks like the null backend is merged ...

On the other issue, the unicode key - I'll comment on #588

**Comment by gbin** [comment]
looks like everything is merged here, please reopen a separate clear issue if something else shows up.
