### ISSUE TITLE
IRC Events are not synchronous.

### ISSUE THREAD

**Issue by qlixed** [errbotio/errbot#595]
Trying to get info from the joined channels I found out on python3 that the code that fires up the event callbacks is not synchronous, so the event fires weirdly like we can see here in this log:

> [qlixed@dhcp-0-118 report-errbot]$ vi plugins-extra/test_irc_sync.py 
> [qlixed@dhcp-0-118 report-errbot]$ err.py --config config.py
> 15:45:38 INFO     errbot.err                Config check passed...
> 15:45:38 INFO     errbot.err                Selected backend 'IRC'.
> 15:45:38 INFO     errbot.err                Checking for './data'...
> 15:45:38 INFO     errbot.backend_manager    Backends search paths ['/usr/lib/python3.4/site-packages/errbot/backends']
> 15:45:38 INFO     errbot.backend_manager    Found those backends available:
> 15:45:38 INFO     errbot.backend_manager    	     Slack  (/usr/lib/python3.4/site-packages/errbot/backends/slack.py)
> 15:45:38 INFO     errbot.backend_manager    	  Telegram  (/usr/lib/python3.4/site-packages/errbot/backends/telegram.py)
> 15:45:38 INFO     errbot.backend_manager    	   Graphic  (/usr/lib/python3.4/site-packages/errbot/backends/graphic.py)
> 15:45:38 INFO     errbot.backend_manager    	      Text  (/usr/lib/python3.4/site-packages/errbot/backends/text.py)
> 15:45:38 INFO     errbot.backend_manager    	   Hipchat  (/usr/lib/python3.4/site-packages/errbot/backends/hipchat.py)
> 15:45:38 INFO     errbot.backend_manager    	      Null  (/usr/lib/python3.4/site-packages/errbot/backends/null.py)
> 15:45:38 INFO     errbot.backend_manager    	       IRC  (/usr/lib/python3.4/site-packages/errbot/backends/irc.py)
> 15:45:38 INFO     errbot.backend_manager    	      XMPP  (/usr/lib/python3.4/site-packages/errbot/backends/xmpp.py)
> 15:45:38 INFO     errbot.backend_manager    	      Test  (/usr/lib/python3.4/site-packages/errbot/backends/test.py)
> 15:45:38 INFO     errbot.main               Found Backend plugin: 'IRC'
> 						Description: This is the IRC backend for Err.
> 15:45:38 WARNING  yapsy                     Plugin candidate '/usr/lib/python3.4/site-packages/errbot/backends/slack.plug'  rejected by strategy 'SpecificBackendLocator'
> 15:45:38 WARNING  yapsy                     Plugin candidate '/usr/lib/python3.4/site-packages/errbot/backends/telegram.plug'  rejected by strategy 'SpecificBackendLocator'
> 15:45:38 WARNING  yapsy                     Plugin candidate '/usr/lib/python3.4/site-packages/errbot/backends/graphic.plug'  rejected by strategy 'SpecificBackendLocator'
> 15:45:38 WARNING  yapsy                     Plugin candidate '/usr/lib/python3.4/site-packages/errbot/backends/text.plug'  rejected by strategy 'SpecificBackendLocator'
> 15:45:38 WARNING  yapsy                     Plugin candidate '/usr/lib/python3.4/site-packages/errbot/backends/hipchat.plug'  rejected by strategy 'SpecificBackendLocator'
> 15:45:38 WARNING  yapsy                     Plugin candidate '/usr/lib/python3.4/site-packages/errbot/backends/null.plug'  rejected by strategy 'SpecificBackendLocator'
> 15:45:38 WARNING  yapsy                     Plugin candidate '/usr/lib/python3.4/site-packages/errbot/backends/xmpp.plug'  rejected by strategy 'SpecificBackendLocator'
> 15:45:38 WARNING  yapsy                     Plugin candidate '/usr/lib/python3.4/site-packages/errbot/backends/test.plug'  rejected by strategy 'SpecificBackendLocator'
> 15:45:38 INFO     errbot.storage            Opened shelf of IRCBackend at ./data/core.db
> 15:45:38 INFO     errbot.storage            Init shelf of ChatRoom
> 15:45:38 INFO     errbot.storage            Init shelf of Health
> 15:45:38 INFO     errbot.storage            Init shelf of Backup
> 15:45:38 INFO     errbot.storage            Init shelf of Plugins
> 15:45:38 INFO     errbot.storage            Init shelf of Help
> 15:45:38 INFO     errbot.storage            Init shelf of ACLS
> 15:45:38 INFO     errbot                    webhooks:  Flag to bind /echo to echo
> 15:45:38 INFO     errbot.storage            Init shelf of Webserver
> 15:45:38 INFO     errbot.storage            Init shelf of VersionChecker
> 15:45:38 INFO     errbot.storage            Init shelf of Utils
> 15:45:38 INFO     errbot.storage            Init shelf of TestIRCSync
> 15:45:44 INFO     errbot.backends.irc       IRC welcome <irc.client.Event object at 0x7ff06cf80eb8>
> 15:45:44 INFO     errbot.errBot             Activate internal commands
> 15:45:44 INFO     errbot.plugin_manager     Activating all the plugins...
> 15:45:44 INFO     errbot.plugin_manager     Activate plugin: Utils
> 15:45:44 INFO     errbot.plugin_manager     Activating Utils with min_err_version = 3.2.2 and max_version = 3.2.2
> 15:45:44 INFO     errbot.storage            Opened shelf of Utils at ./data/plugins/Utils.db
> 15:45:44 INFO     errbot.core_plugins.wsvie Checking Utils for webhooks
> 15:45:44 INFO     errbot.plugin_manager     Activate plugin: ACLs
> 15:45:44 INFO     errbot.plugin_manager     Activating ACLs with min_err_version = None and max_version = None
> 15:45:44 INFO     errbot.storage            Opened shelf of ACLS at ./data/plugins/ACLS.db
> 15:45:44 INFO     errbot.core_plugins.wsvie Checking ACLS for webhooks
> 15:45:44 INFO     errbot.plugin_manager     Activate plugin: Help
> 15:45:44 INFO     errbot.plugin_manager     Activating Help with min_err_version = 3.2.2 and max_version = 3.2.2
> 15:45:44 INFO     errbot.storage            Opened shelf of Help at ./data/plugins/Help.db
> 15:45:44 INFO     errbot.core_plugins.wsvie Checking Help for webhooks
> 15:45:44 INFO     errbot.plugin_manager     Activate plugin: ChatRoom
> 15:45:44 INFO     errbot.plugin_manager     Activating ChatRoom with min_err_version = 3.2.2 and max_version = 3.2.2
> 15:45:44 INFO     errbot.storage            Opened shelf of ChatRoom at ./data/plugins/ChatRoom.db
> 15:45:44 INFO     errbot.core_plugins.wsvie Checking ChatRoom for webhooks
> 15:45:44 INFO     errbot.plugin_manager     Activate plugin: Test_IRC_Sync
> 15:45:44 INFO     errbot.plugin_manager     Activating Test_IRC_Sync with min_err_version = None and max_version = None
> 15:45:44 INFO     errbot.storage            Opened shelf of TestIRCSync at ./data/plugins/TestIRCSync.db
> 15:45:44 INFO     errbot.core_plugins.wsvie Checking TestIRCSync for webhooks
> 15:45:44 INFO     errbot.plugin_manager     Activate plugin: VersionChecker
> 15:45:44 INFO     errbot.plugin_manager     Activating VersionChecker with min_err_version = 3.2.2 and max_version = 3.2.2
> 15:45:44 INFO     errbot.storage            Opened shelf of VersionChecker at ./data/plugins/VersionChecker.db
> 15:45:44 INFO     errbot.core_plugins.wsvie Checking VersionChecker for webhooks
> 15:45:44 INFO     errbot.plugin_manager     Activate plugin: Backup
> 15:45:44 INFO     errbot.plugin_manager     Activating Backup with min_err_version = None and max_version = None
> 15:45:44 INFO     errbot.storage            Opened shelf of Backup at ./data/plugins/Backup.db
> 15:45:44 INFO     errbot.core_plugins.wsvie Checking Backup for webhooks
> 15:45:44 INFO     errbot.plugin_manager     Activate plugin: Health
> 15:45:44 INFO     errbot.plugin_manager     Activating Health with min_err_version = 3.2.2 and max_version = 3.2.2
> 15:45:44 INFO     errbot.storage            Opened shelf of Health at ./data/plugins/Health.db
> 15:45:44 INFO     errbot.core_plugins.wsvie Checking Health for webhooks
> 15:45:44 INFO     errbot.plugin_manager     Activate plugin: Plugins
> 15:45:44 INFO     errbot.plugin_manager     Activating Plugins with min_err_version = 3.2.2 and max_version = 3.2.2
> 15:45:44 INFO     errbot.storage            Opened shelf of Plugins at ./data/plugins/Plugins.db
> 15:45:44 INFO     errbot.core_plugins.wsvie Checking Plugins for webhooks
> 15:45:44 INFO     errbot.plugin_manager     Activate plugin: Webserver
> 15:45:44 INFO     errbot.plugin_manager     Activating Webserver with min_err_version = 3.2.2 and max_version = 3.2.2
> 15:45:44 INFO     errbot.plugins.Webserver  Webserver is not configured. Forbid activation
> 15:45:44 INFO     errbot.core_plugins.wsvie Checking Webserver for webhooks
> 15:45:44 INFO     errbot.core_plugins.wsvie Webhook routing echo
> 15:45:44 INFO     errbot.errBot             
> 15:45:44 INFO     errbot.errBot             Notifying connection to all the plugins...
> 15:45:44 INFO     errbot.plugins.ChatRoom   Callback_connect
> 15:45:44 INFO     errbot.plugins.ChatRoom   Joining room #gtbtestchannel with username Err
> ################################
> At Callback room joined
> Not Joined yet!
> <class 'yapsy_loaded_plugin_IRC_0.IRCMUCRoom'>
> ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_bot', 'connection', 'create', 'destroy', 'exists', 'invite', 'join', 'joined', 'leave', 'occupants', 'room', 'topic']
> <yapsy_loaded_plugin_IRC_0.IRCMUCRoom object at 0x7ff05f33c8d0>
> ################################
> 15:45:44 INFO     errbot.backends.irc       Joined room #gtbtestchannel
> ################################
> At Callback connect
> ################################
> 15:45:44 INFO     errbot.errBot             Plugin activation done.
> 15:46:07 INFO     errbot.plugins.ACLS       Check if hello is admin only command.
> 15:46:07 INFO     errbot.errBot             Processing command 'hello' with parameters '' from qlixed!None #gtbtestchannel
> ################################
> ################################
> At Callback message
> <class 'errbot.backends.base.Message'>
> At Callback botmessage
> ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_body', '_delayed', '_extras', '_from', '_to', '_type', 'body', 'clone', 'delayed', 'extras', 'frm', 'nick', 'to', 'type']
> !hello
> <class 'errbot.backends.base.Message'>
> ################################
> ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_body', '_delayed', '_extras', '_from', '_to', '_type', 'body', 'clone', 'delayed', 'extras', 'frm', 'to', 'type']
> Hello!
> ################################
> ^C15:51:02 INFO     errbot.errBot             Disconnect callback, deactivating all the plugins.
> 15:51:02 INFO     errbot.plugin_manager     Shutdown.
> 15:51:02 INFO     errbot.plugin_manager     Bye.

You can see that the callback room joined fires up but the bot is not joined yet, and then never is fired again.
Also the connect callback calls BEFORE the room joined.
Additionally if i left and rejoin the channel, the bot never fire the callback presence.
The code that I use for the test is attached to the Issue.
To avoid any troubles I manually remove the __pycache__ paths and the db files under data.
here is the list of files in the file:

[report-errbot]$ ls -lR 
.:
total 72
-rw-rw-r--. 1 qlixed qlixed 13529 feb 10 15:12 config.py
-rw-rw-r--. 1 qlixed qlixed 13557 feb 10 15:12 config.py.orig
drwxrwxr-x. 2 qlixed qlixed  4096 feb 11 16:11 data
-rw-rw-r--. 1 qlixed qlixed 28896 feb 11 15:51 err.log
drwxrwxr-x. 2 qlixed qlixed  4096 feb 11 16:11 plugins-extra

./data:
total 0

./plugins-extra:
total 8
-rw-rw-r--. 1 qlixed qlixed  160 feb 11 13:59 test_irc_sync.plug
-rw-rw-r--. 1 qlixed qlixed 2220 feb 11 15:47 test_irc_sync.py

[report-errbot]$ file *
config.py:      ASCII text
config.py.orig: ASCII text
data:           directory
err.log:        ASCII text
plugins-extra:  directory

[report-errbot.zip](https://github.com/errbotio/errbot/files/126995/report-errbot.zip)

[report-errbot]$ file plugins-extra/*
plugins-extra/test_irc_sync.plug: ASCII text
plugins-extra/test_irc_sync.py:   Python script, ASCII text executable

$ zip -X -r -9 report-errbot.zip report-errbot
updating: report-errbot/ (stored 0%)
  adding: report-errbot/plugins-extra/ (stored 0%)
  adding: report-errbot/plugins-extra/test_irc_sync.plug (deflated 19%)
  adding: report-errbot/plugins-extra/test_irc_sync.py (deflated 81%)
  adding: report-errbot/data/ (stored 0%)
  adding: report-errbot/config.py.orig (deflated 63%)
  adding: report-errbot/config.py (deflated 62%)
  adding: report-errbot/err.log (deflated 91%)

**Comment by gbin** [comment]
I made a very crude and untested fix, can you give it a shot ?

The better fix would be to override the callback on join from the irc client class but it ids way more involved.
