### ISSUE TITLE
[slack] [documentation] Making @botname work as a prefix

### ISSUE THREAD

**Issue by ytjohn** [errbotio/errbot#600]
If I want to let people (on slack) to address err by `@botname`, you can't just put `@botname` in `BOT_ALT_PREFIXES`, it won't work. I did a lot of searching, but couldn't find anyone else mentioning this prior. 

I enabled debugging and found that slack replaces `@username` with `<@UNIQID>`.  So I put that as an alternate prefix, and that started working.

I don't know enough about slack to know if that id is persistent. If it is persistent, than this can just be a documentation addition. Maybe there is an better way to get this id other than just watching err's debug log.

If it's not persistent, or if others think it's worthwhile, a better approach would be to have an option to append `<@UNIQID>` to the `BOT_ALT_PREFIXES` upon connection to slack. 

Thoughts?

**Comment by sijis** [comment]
@ytjohn That ID from slack, i believe, is persistent.

What if you just add '<botname>' to `BOT_ALT_PREFIXES`?

I will double-check later, but I have a config that (i think) allows the bot to respond with messages where referenced as <@sijis> or <sijis>.

**Comment by ytjohn** [comment]
@sijis 

Indeed, I originally had `BOT_ALT_PREFIXES = ('botname', '@botname'). `botname` works, `@botname` does not. That's because slack rewrites the message text to show the uid of the referenced user.  

```
2016-02-15 02:59:05,234 DEBUG    errbot.backends.slack     Saw an event: {u'channel': 
 u'C0chand',
 u'team': u'T0teamid',
 u'text': u'<@U0botid>: help',
 u'ts': u'1455505144.000063',
 u'type': u'message',
 u'user': u'U0myid'}
```

**Comment by zoni** [comment]
Slack ***may*** change those IDs in the future, but I think it's pretty safe to assume that they won't change.

From an end-user perspective, I think the ideal situation is that `@mentioning` the box just works out of the box on both Slack and HipChat (as they both use the very same semantics here), without a user even having to bother with setting up a special `BOT_ALT_PREFIXES` setting for it.

This should be easyish to do. If the Slack API (and same goes for HipChat) exposes some way to get our unique identifier, then we could just insert that into the `BOT_ALT_PREFIXES` property as we're starting up (so somewhere in `__init__()` of the `SlackBackend` and `HipChatBackend`.)

**Comment by sijis** [comment]
@zoni I'm taking a stab at this and I put the following `serve_once` (which works!)
```
@@ -252,6 +261,16 @@ class SlackBackend(ErrBot):
         log.debug("Token accepted")
         self.bot_identifier = SlackPerson(self.sc, self.auth["user_id"])
 
+        log.debug('===================================================================')
+        log.debug(self.bot_config.BOT_ALT_PREFIXES)
+        alt_prefixes = list(self.bot_config.BOT_ALT_PREFIXES)
+        alt_prefixes.append('<@{0}>'.format(self.bot_identifier.userid))
+        self.bot_config.BOT_ALT_PREFIXES = tuple(alt_prefixes)
+        self.bot_alt_prefixes = tuple(x.lower() for x in self.bot_config.BOT_ALT_PREFIXES)
+        log.debug(alt_prefixes)
+        log.debug(self.bot_config.BOT_ALT_PREFIXES)
+        log.debug('===================================================================')
+
         log.info("Connecting to Slack real-time-messaging API")
         if self.sc.rtm_connect():
             log.info("Connected")
```

There are some hidden nuances with `self.bot_alt_prefixes` and `self.bot_config.BOT_ALT_PREFIXES`. Do you know what the purpose of these two variables are?
I see its all defined in `errbot/errBot.py`.

/cc @gbin

**Comment by sijis** [comment]
My WIP PR removed all the `log.debug` lines.

**Comment by sijis** [comment]
I think this could be closed because of https://github.com/errbotio/errbot/pull/768.
