### ISSUE TITLE
RFC: Configure plugins outside of chat

### ISSUE THREAD

**Issue by zoni** [errbotio/errbot#608]
Some people have expressed an interest in being able to configure all aspects of the bot programmatically (mainly by using configuration management systems such as ansible, chef, puppet, etc) without actually having to chat with the bot.

Errbot configuration is currently split between two major areas:

1. Stuff in `config.py`. This is almost entirely backend configuration which deals with the chat network to connect to, account credentials, storage selection, etc, and thus not suitable as dynamic runtime configuration. Changes require a full restart.

2. Plugin specific configuration. This is currently kept in a database (shelve-based by default, other options available on master) and can only be configured by bot admins, through chatting with the bot.

The `config.py` configuration file already plays nice with configuration management systems (they can template the file and restart errbot on changes). Plugin configuration on the other hand doesn't, at the moment.

I propose adding a command-line program (either standalone or as part of the `errbot` command directly, the latter being preferred) which is capable of setting the configuration for plugins.

Example usage
--------------------

Get the plugin configuration for the webserver plugin:

```
$ errbot --get-plugin-config Webserver
{'HOST': '0.0.0.0',
 'PORT': 3141,
 'SSL': {'certificate': '',
         'enabled': False,
         'host': '0.0.0.0',
         'key': '',
         'port': 3142}}
```

Set a different configuration for the webserver plugin:

```
$ echo "{'HOST': 'localhost', 'PORT': 1234, 'SSL': {'certificate': '', 'enabled': False, 'host': '0.0.0.0', 'key': '', 'port': 3142}} | errbot --set-plugin-config Webserver
Webserver plugin config updated
```

Similar to passing `--config` to errbot in order to start it, the command would take `--config` here as well when needed:

```
$ errbot --config /opt/errbot/ --get-plugin-config Webserver
{'HOST': '0.0.0.0',
 'PORT': 3141,
 'SSL': {'certificate': '',
         'enabled': False,
         'host': '0.0.0.0',
         'key': '',
         'port': 3142}}
```

Implementation
--------------------

Under the hood this plugin should:

1. Check `config.py` to know where storage is and what storage backend is used.
2. Load storage and update it directly if errbot **isn't running**.
3. Connect to errbot on a socket (somewhere in it's data directory) and have errbot proxy the configuration change if it **is running**.

This would allow configuration management systems to update the configuration with some specific, *"static"* configuration. It would let people do this *before* even starting the bot, so plugins are configured as desired the first time it even starts up.

Pitfalls
--------

Some issues I see, which may require more thinking about:

1. When the bot is running, any configuration that is set can be verified by the plugin, similar to how `!config` verifies it. If the bot isn't running this obviously isn't possible. It may be desirable to have a flag which tells errbot to only set the config if it can connect to a running instance.

**Comment by gbin** [comment]
I think it is better to implement 3 as a second step as it would be related to a more general effort of HA (High availability). For example we could implement a change detection in the storage backends as some DB already have that implemented like Redis or Firebase and reload the relevant plugin accordingly.
Another possibility: we could also start another instance and force a failover.
So it might be better to not paint us in a corner for now and concentrate on the initial provisioning first.

**Comment by zoni** [comment]
> I think it is better to implement 3 as a second step as it would be related to a more general effort of HA (High availability)

Yes and no. We can and probably should do 2 without immediately doing 3 ("minimal viable product" and all that, very agile :wink:) as this would definitely already help please a lot of people. But I think we definitely should think about how to update the config if the bot **is** running now, not later.

For one, if the bot is running and we just change the configuration out from underneath it, unexpected things could happen, from plugins using old data to outright corruption of the database. We have to at least make sure we disallow that if we don't support it.

**Comment by gbin** [comment]
Maybe simply leaving a key in the DB saying errbot is up ? If it is forbid the update ?

**Comment by zoni** [comment]
That may work. If the both crashes the state wouldn't match, but that's not a terribly big issue.

How'd we make this work with multiple instances though? Two bots sharing the same storage is now possible with various of the new storage backends.

**Comment by gbin** [comment]
I would propose...

For the bot crash, we can make a --force or somethingto be able to restart it and reset the state.

For now we don't make the several instances work, if errbot sees that the running flag is up, it doesn't start (except if --force).

Same thing for plugin conf update, don't do it if it is running except --force that will reset the state as non-running.

There will be way way more challenges to make 2 bots run at the same time: identity on the backend ? data race conditions ? notification of change ? master slave ?

**Comment by shuhaowu** [comment]
Is there a way to specify the web server configuration via a text file on disc rather than having to execute the command, which as far as I can tell serializes the configuration via shelf, or whatever backend one wants?
