### ISSUE TITLE
Certificate error on https://errbot.io

### ISSUE THREAD

**Issue by gbin** [errbotio/errbot#620]
I wonder if it is possible to fix this ? Can we put our own certificate on rtd ?

**Comment by zoni** [comment]
Not unless we bounce traffic through our own loadbalancers I'm afraid.

For more background, see https://read-the-docs.readthedocs.org/en/latest/alternate_domains.html#cname-ssl

**Comment by zoni** [comment]
(Sidenote: this wasn't supported with GitHub pages either)

**Comment by jayvdb** [comment]
This can be fixed by migrating to @netlify ; they provide HTTPS (and lots of other cool features) for free.

**Comment by sijis** [comment]
I'm not sure if we have the custom domain feature or not, but this may be relevant.
https://docs.readthedocs.io/en/latest/custom_domains.html?highlight=SSL#custom-domain-ssl

**Comment by sijis** [comment]
I'm not longer seeing an issue with the domain. We are good now.
