### ISSUE TITLE
rocket.chat backend ?

### ISSUE THREAD

**Issue by Djiit** [errbotio/errbot#627]
It might be cool to support [Rocket.chat](https://rocket.chat/).

**Comment by bnikolaus** [comment]
+1

**Comment by xPrcek** [comment]
+1

**Comment by gbin** [comment]
Like the discord backend, I am willing to give it a shot if somebody using the backend daily takes over the maintenance (report bugs early, check compatibility with head etc...), any volunteers?

**Comment by jean-feltrin-movile** [comment]
+1

**Comment by ayashjorden** [comment]
+1

**Comment by zoni** [comment]
Please don't post +1 comments but use [reactions](https://cloud.githubusercontent.com/assets/25792/13683303/d55b8b7e-e6ba-11e5-9b31-59a8db92e456.gif) instead. Posting +1 comments causes emails to be sent to all participants (which gets annoying) and increases the risk of any relevant discussion getting lost among all the +1 messages.

**Comment by AoiKuiyuyou** [comment]
I have made a Rocket.Chat backend [AoikRocketChatErrbot](https://github.com/AoiKuiyuyou/AoikRocketChatErrbot).

Please tell me the modifications needed before submitting a pull request.

**Comment by gbin** [comment]
@Djiit @qk4l @jean-feltrin-movile @midse @ayashjorden, please give it a shot.

**Comment by gbin** [comment]
@AoiKuiyuyou thanks for your contribution, you are making a lot of people happy ! I perused the code and it looks like only one-to-one messages are supported at the moment right ? It looks like a really good starting point to build on for the community and add more features,

**Comment by AoiKuiyuyou** [comment]
The backend uses Rocket.Chat's [stream-room-messages](https://rocket.chat/docs/developer-guides/realtime-api/subscriptions/stream-room-messages) API to receive messages from rooms the login user has joined. And uses the [sendMessage](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/send-message) API to send messages. That's what have been implemented so far.

**Comment by midse** [comment]
Thanks a lot for your contribution @AoiKuiyuyou ! 
I'm not very familiar with errbot yet (I was waiting for a rocket chat backend to play with it).
I was able to interact with the bot (one-to-one message) and launch a few commands.
Some commands output looked a bit weird because RocketChat doesn't support markdown syntax (for example titles or colors are not displayed).

**Comment by jhermann** [comment]
Link this in the README (Chat servers support · With add-ons)?

**Comment by nicoddemus** [comment]
> Link this in the README (Chat servers support · With add-ons)?

I agree, but it seems @AoiKuiyuyou's implementation does not work on the latest RocketChat version (AoiKuiyuyou/AoikRocketChatErrbot#1) so @cardoso has made [a fork](https://github.com/cardoso/errbot-rocketchat).

**Comment by torgeirl** [comment]
FYI: it seems Rocket.Chat is changing how bots are interacted with, judging from the issues in their bot roadmap: https://github.com/RocketChat/Rocket.Chat/projects/16

**Comment by nicoddemus** [comment]
https://github.com/cardoso/errbot-rocketchat/pull/5 has now been merged which fixes the above. 👍

**Comment by sijis** [comment]
@ywyt738 I've realized that there is no link to the backend, so i created a PR to add a link to the repo so other folks can easily find it.

https://github.com/errbotio/errbot/pull/1263.

This is a community supported backend and I'm sure they'd be glad to address any issues with it.

**Comment by monokal** [comment]
Rocket Chat is now being increasingly used internally by organisations who don't want to rely on hosted solutions, including in my own use-case. It'd be great to get this fully onboarded.
