### ISSUE TITLE
HipChat backend must adapt to Identifier changes

### ISSUE THREAD

**Issue by zoni** [errbotio/errbot#637]
#631 changed some things around related to Identifiers, the HipChat backend must still be updated to work with the new API.

**Comment by zoni** [comment]
I think that with the porting of the XMPP backend, HipChat may have been done already as well, but somebody should definitely try this out for real against an instance of HipChat.

**Comment by gbin** [comment]
Actually not, because Hipcjat redefines rooms, roomoccupants etc -_-
