### ISSUE TITLE
slack AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by ytjohn** [errbotio/errbot#640]
Using python3 + errbot 3.2.3 on slack, I encounter the following issue.  I didn't encounter it on 3.2.2 on python 2.7, but it seems to specific to the `.decode` option on slack response (which might not be required on python 3). 

Tracking the code, this seems to be related to PR #610 and this commit: https://github.com/errbotio/errbot/commit/91e8c079db98245a2eeb2fd42117ab1250305a98#diff-4d2174262014c51fc8b38e02b99962bdR207

By modifying line 203 and removing `.decode('utf-8')`, the slack backend was able to process the response and connect. 

https://docs.python.org/3/howto/pyporting.html    
> (e.g., the decode() method is usable on the equivalent binary data type in either Python 2 or 3, but it can’t be used by the text data type consistently between Python 2 and 3 because str in Python 3 doesn’t have the method)

```
06:27:39 ERROR    errbot.backends.base      Exception occurred in serve_once:
Traceback (most recent call last):
  File "/Users/hogenj/projects/err-chatfluence/env3/lib/python3.4/site-packages/errbot/backends/base.py", line 620, in serve_forever
    if self.serve_once():
  File "/Users/hogenj/projects/err-chatfluence/env3/lib/python3.4/site-packages/errbot/backends/slack.py", line 214, in serve_once
    self.auth = self.api_call("auth.test", raise_errors=False)
  File "/Users/hogenj/projects/err-chatfluence/env3/lib/python3.4/site-packages/errbot/backends/slack.py", line 203, in api_call
    response = json.loads(self.sc.server.api_call(method, **data).decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

pinging @zoni who is familiar with the changes.

**Comment by zoni** [comment]
> Using python3 + errbot 3.2.3 on slack

That's 3.2.3 installed from pip right? It's already fixed on master and the 3.2 branch, but no 3.2.x release on PyPI has the fix yet. See https://github.com/errbotio/errbot/issues/622#issuecomment-190901592 on what you can do to get around this (there's a few options available to you :smile:).
