### ISSUE TITLE
Users should be able to change the checked-out branch of a plugin

### ISSUE THREAD

**Issue by zoni** [errbotio/errbot#641]
As explained in the last paragraph of https://github.com/errbotio/errbot/issues/184#issuecomment-192895024, I think working with plugins can become a little more flexible if errbot allows you to change what branch to use for a plugin.

This would allow more mature plugins to version-tag releases and maintain a development branch alongside master (I suggest keeping the master branch as the stable branch because this has always been the branch used by errbot for installing plugins).

I see this taking shape in the following form:
- `!repos install some-plugin` gains an extra, optional argument, to denote the branch/tag/ref to check out after cloning.
- `!repos` gains an option to refresh upstream data for plugins (ie, it can run `git fetch` in all installed plugin directories). Maybe this should even happen automatically with the option to force it.
- `!repos` gains an option to see which branch a given plugin/all plugins are on (bonus points: It should show how many commits the branch is behind its upstream counterpart, if it has a remote tracking branch)
- `!repos` gains an option to switch a given plugin to another branch/tag/ref

Having this in place would also make it easy to in the future let a version checker notify you when plugins you have installed have updates (by checking the tracking branches and notifying the admins in case they're behind).

**Comment by sijis** [comment]
+1 I can see the value in doing this.

**Comment by gbin** [comment]
It looks fine to me after the v4 release.
If the thing gets smart it can even give you the branches that are compatible with your version of errbot :)
The version check is also an awesome idea.
