### ISSUE TITLE
err does not recurse plugins/pluginname directory

### ISSUE THREAD

**Issue by ytjohn** [errbotio/errbot#646]
If you install a plugin from a git repo, err (yapsy probably) does not recurse into that subdirectory

This means that if you have your .plug and .py file in a sub-directory of your git repo, then err will check out the repository, but now load the plugin.  It also means that if you have one repository with multiple plugins, that will not work either.

Example:
```
err-chatfluence
├── err-chatfluence
│   ├── chatfluence.plug
│   └── chatfluence.py
├── requirements-dev.txt
├── requirements.txt
├── .gitignore
```

**Comment by zoni** [comment]
Interestingly, this does work correctly for a directory set in `BOT_EXTRA_PLUGIN_DIR`.

**Comment by zoni** [comment]
Recent work on the plugin manager and repo stuff changed the yapsy plugin locator to no longer scan directories recursively, which is a change from previous behaviour.

@gbin I think we should let yapsy scan plugin directories recursively. You're more familiar with this section of the code than I am though. Any reason we wouldn't want to do this?
