### ISSUE TITLE
irc backend trims leading space

### ISSUE THREAD

**Issue by benjumanji** [errbotio/errbot#652]
I don't know if this is intended behaviour, but it ruins all my ascii tables.

```
    @botcmd
    def leading_spaces(self, msg, args):
        """leading spaces test"""
        return "           there should have been tons of leading space"
````

This shows up with no leading whitespace.

Is there anyway to disable this behaviour?

**Comment by gbin** [comment]
The bot expects markdown as output and you can format tables from there. Note that there is also a compact formatting mode for IRC too.

**Comment by benjumanji** [comment]
It expects markdown. I see. I guess I needed to RTFM :sob:

**Comment by benjumanji** [comment]
Ok, I can see the bits about markdown, but as far as I am aware markdown doesn't standardise tables, which flavour does errbot use?

Also I tried grepping the docs for the irc compact stuff and I couldn't see anything. Any hints?

**Comment by gbin** [comment]
This is `COMPACT_OUTPUT = True` in config.py

For the tables it uses
http://pythonhosted.org/Markdown/extensions/tables.html

Please file a big if the documentation is lacking thx !

**Comment by benjumanji** [comment]
Great, I'll have a read, and close this for now. Thanks for your help!
