### ISSUE TITLE
Slack Plugin should probably have an option to supress expansion

### ISSUE THREAD

**Issue by Synforge** [errbotio/errbot#668]
I run into this quite often when I'm configuring a plugin:
`e.g. !plugin config Test {'USERNAME': 'test@example.org'}`

Slack automatically expands this so the plugin receives the following:
`{'USERNAME': '<mailto:test@example.org|test@example.org>'}`

This is also true when sending a hostname:
`!ping example.org`

The plugin will receive:
`<http://example.org|example.org>`

Now this obviously makes writing backend agnostic plugins difficult since you then have to check for these cases and you end up writing Slack specific functionality within the plugin. What I believe should be available (and please correct me if I've missed this in the documentation) is an option to convert this expansion back, and presumably for backwards compatibility this should be an option in user configuration or on a per plugin basis. e.g. If a user types example.org the plugin should receive example.org and if they type test@example.org the plugin should receive test@example.org.

I'm happy to contribute and amend the Slack plugin to have an option to do this, just wondering about others input on this since this could potentially have breaking changes to existing plugins based on user configuration?

**Comment by Synforge** [comment]
Just another note on this, it seems like the Slack backend plugin does have some functionality to strip angle brackets but doesn't go any further than this to suppress the expansion of links.

**Comment by sijis** [comment]
I've run into this multiple times myself and it sucks!
I haven't looked too closely but from their docs (https://api.slack.com/docs/formatting), it looks like we can pass `parse=none` and that may give the behavior expected. It would have to be added to `errbot/backends/slack.py`.

**Comment by sijis** [comment]
This is probably a better link: https://api.slack.com/methods/chat.postMessage

**Comment by Synforge** [comment]
I believe that only affects messages going out, incoming messages from RTM you can't specify not to have those links expanded. At least that's my understanding, it's probably going to require parsing logic within the Slack plugin.

**Comment by Synforge** [comment]
I've created a PR for this:
https://github.com/errbotio/errbot/pull/671

Please note this doesn't have the option, it's just the default. This also mirrors the existing stripping of <http://www.example.org> formats.

**Comment by zoni** [comment]
#671 was merged so I believe this can now be closed. :smile: 

And for completeness sake, there's no way to opt-out of these message modifications for incoming messages from the Real Time Messaging API, so we have to resort to undoing these things manually.
