### ISSUE TITLE
Problem with errbot 4.0 and imports in python 2.7.10

### ISSUE THREAD

**Issue by fernand0** [errbotio/errbot#677]
Hello,

I've updated in two different machines the errbot (Ubuntu 15.10 and Raspbian) and I've found what seems to be a problem with html version. The relevant messages are:

>   File "/home/user/.pyenv/versions/2.7.10/lib/python2.7/site-packages/errbot/backends/xmpp.py", line 8, in <module>
>    from html import _invalid_codepoints, _invalid_charrefs
> ImportError: cannot import name _invalid_codepoints

The same error appears in several steps of the process.

Maybe it is a problem with html module or futures or something like that?

Thanks!

**Comment by gbin** [comment]
This is a shameful hack to support xhtml-im back which is incompatible with py2, expect a fix shortly.
