### ISSUE TITLE
RFE: Unit Test for IRC backend

### ISSUE THREAD

**Issue by qlixed** [errbotio/errbot#683]
I see that there is no unit test available for the IRC backend, I want to propose a initial implementation of this.
The idea is to use the [python-irc simple server](https://github.com/jaraco/irc/blob/master/irc/server.py) to setup a IRC server on localhost and connect two bots that send to each one predefined messages and monitor the dialogue, and the interaction with the server.
Let me know any ideas or comments that you have.

**Comment by sijis** [comment]
There's been no traction on this. If there's progress, feel free to open a new issue and reference this one.
