### ISSUE TITLE
additional callbacks

### ISSUE THREAD

**Issue by sijis** [errbotio/errbot#699]
There was a discussion over a week about having callbacks for several events that would be available to plugins. This is to capture that summarized conversation on gitter.

```
gbin - March 17 16:53
...
we do a callback per identity type
callback_presence is for person
we need to add callback_room for rooms (creations, topic etc...)
and callback_roomoccupant (for join, leave, kicked, ...)
```

https://gitter.im/errbotio/errbot?at=56eb2756acb317593df523a8

**Comment by gbin** [comment]
Duplicate of #474
