### ISSUE TITLE
ACL allowrooms not working with Slack, or format unclear.

### ISSUE THREAD

**Issue by jakosky** [errbotio/errbot#711]
I want to restrict Salt:* commands to a specific room.  I have tried 3 different formats for the Slack room: cfops, #cfops, and its Slack channel id G0YRZBSMS. All respond with "You're not allowed to access this command from this room".

I am also not allowing these commands as private messages, which appears to work fine.

# G0YRZBSMS
17:30:36 DEBUG    errbot.backends.slack     Processing slack event: {u'text': u'Cob, salt stg .* test.ping', u'ts': u'1460223035.000046', u'user': u'U02FD73UX', u'team': u'T02FBFM8R', u'type': u'message', u'channel': u'G0YRZBSMS'}
17:30:36 DEBUG    errbot.backends.slack     Saw an event: {u'channel': u'G0YRZBSMS',
 u'team': u'T02FBFM8R',
 u'text': u'Cob, salt stg .* test.ping',
 u'ts': u'1460223035.000046',
 u'type': u'message',
 u'user': u'U02FD73UX'}
17:30:36 DEBUG    errbot.backends.slack     Escaped IDs event text: Cob, salt stg .* test.ping
17:30:36 DEBUG    errbot.errBot             *** frm = #cfops/jayjakosky
17:30:36 DEBUG    errbot.errBot             *** username = U02FD73UX
17:30:36 DEBUG    errbot.errBot             *** text = Cob, salt stg .* test.ping
17:30:36 DEBUG    errbot.errBot             Called with alternate prefix 'Cob'
17:30:36 DEBUG    errbot.plugins.ACLS       Check salt for ACLs.
17:30:36 INFO     errbot.plugins.ACLS       Matching ACL {'allowprivate': False, 'allowrooms': 'G0YRZBSMS'} against username @jayjakosky for command Salt:salt
17:30:36 DEBUG    errbot.backends.slack     Sending channel message to cfops (G0YRZBSMS)
17:30:36 DEBUG    errbot.backends.slack     Message size: 56
17:30:36 INFO     errbot.errBot             Command None blocked or deferred.
17:30:36 DEBUG    errbot.errBot             Triggering callback_message on Help
17:30:36 DEBUG    errbot.errBot             Triggering callback_message on Utils
17:30:36 DEBUG    errbot.errBot             Triggering callback_message on Health
17:30:36 DEBUG    errbot.errBot             Triggering callback_message on ACLS
17:30:36 DEBUG    errbot.errBot             Triggering callback_message on Plugins
17:30:36 DEBUG    errbot.errBot             Triggering callback_message on VersionChecker
17:30:36 DEBUG    errbot.errBot             Triggering callback_message on Backup
17:30:36 DEBUG    errbot.errBot             Triggering callback_message on Salt
17:30:36 DEBUG    errbot.errBot             Triggering callback_message on ChatRoom
17:30:37 DEBUG    errbot.backends.slack     Ignoring non-event message: {u'reply_to': None, u'text': u"You're not allowed to access this command from this room", u'ok': True, u'ts': u'1460223036.000047'}

# cfops
17:29:02 DEBUG    errbot.backends.slack     Processing slack event: {u'text': u'Cob, salt stg .* test.ping', u'ts': u'1460222941.000044', u'user': u'U02FD73UX', u'team': u'T02FBFM8R', u'type': u'message', u'channel': u'G0YRZBSMS'}
17:29:02 DEBUG    errbot.backends.slack     Saw an event: {u'channel': u'G0YRZBSMS',
 u'team': u'T02FBFM8R',
 u'text': u'Cob, salt stg .* test.ping',
 u'ts': u'1460222941.000044',
 u'type': u'message',
 u'user': u'U02FD73UX'}
17:29:02 DEBUG    errbot.backends.slack     Escaped IDs event text: Cob, salt stg .* test.ping
17:29:02 DEBUG    errbot.errBot             *** frm = #cfops/jayjakosky
17:29:02 DEBUG    errbot.errBot             *** username = U02FD73UX
17:29:02 DEBUG    errbot.errBot             *** text = Cob, salt stg .* test.ping
17:29:02 DEBUG    errbot.errBot             Called with alternate prefix 'Cob'
17:29:02 DEBUG    errbot.plugins.ACLS       Check salt for ACLs.
17:29:02 INFO     errbot.plugins.ACLS       Matching ACL {'allowprivate': False, 'allowrooms': 'cfops'} against username @jayjakosky for command Salt:salt
17:29:02 DEBUG    errbot.backends.slack     Sending channel message to cfops (G0YRZBSMS)
17:29:02 DEBUG    errbot.backends.slack     Message size: 56
17:29:02 INFO     errbot.errBot             Command None blocked or deferred.
17:29:02 DEBUG    errbot.errBot             Triggering callback_message on Help
17:29:02 DEBUG    errbot.errBot             Triggering callback_message on Utils
17:29:02 DEBUG    errbot.errBot             Triggering callback_message on Health
17:29:02 DEBUG    errbot.errBot             Triggering callback_message on ACLS
17:29:02 DEBUG    errbot.errBot             Triggering callback_message on Plugins
17:29:02 DEBUG    errbot.errBot             Triggering callback_message on VersionChecker
17:29:02 DEBUG    errbot.errBot             Triggering callback_message on Salt
17:29:02 DEBUG    errbot.errBot             Triggering callback_message on Backup
17:29:02 DEBUG    errbot.errBot             Triggering callback_message on ChatRoom
17:29:03 DEBUG    errbot.backends.slack     Ignoring non-event message: {u'reply_to': None, u'text': u"You're not allowed to access this command from this room", u'ok': True, u'ts': u'1460222942.000045'}

# #cfops
17:18:10 DEBUG    errbot.backends.slack     Processing slack event: {u'text': u'Cob, salt stg .* test.ping', u'ts': u'1460222290.000042', u'user': u'U02FD73UX', u'team': u'T02FBFM8R', u'type': u'message', u'channel': u'G0YRZBSMS'}
17:18:10 DEBUG    errbot.backends.slack     Saw an event: {u'channel': u'G0YRZBSMS',
 u'team': u'T02FBFM8R',
 u'text': u'Cob, salt stg .* test.ping',
 u'ts': u'1460222290.000042',
 u'type': u'message',
 u'user': u'U02FD73UX'}
17:18:10 DEBUG    errbot.backends.slack     Escaped IDs event text: Cob, salt stg .* test.ping
17:18:10 DEBUG    errbot.errBot             *** frm = #cfops/jayjakosky
17:18:10 DEBUG    errbot.errBot             *** username = U02FD73UX
17:18:10 DEBUG    errbot.errBot             *** text = Cob, salt stg .* test.ping
17:18:10 DEBUG    errbot.errBot             Called with alternate prefix 'Cob'
17:18:10 DEBUG    errbot.plugins.ACLS       Check salt for ACLs.
17:18:10 INFO     errbot.plugins.ACLS       Matching ACL {'allowprivate': False, 'allowrooms': '#cfops'} against username @jayjakosky for command Salt:salt
17:18:10 DEBUG    errbot.backends.slack     Sending channel message to cfops (G0YRZBSMS)
17:18:10 DEBUG    errbot.backends.slack     Message size: 56
17:18:10 INFO     errbot.errBot             Command None blocked or deferred.
17:18:10 DEBUG    errbot.errBot             Triggering callback_message on Help
17:18:10 DEBUG    errbot.errBot             Triggering callback_message on Utils
17:18:10 DEBUG    errbot.errBot             Triggering callback_message on Health
17:18:10 DEBUG    errbot.errBot             Triggering callback_message on ACLS
17:18:10 DEBUG    errbot.errBot             Triggering callback_message on Plugins
17:18:10 DEBUG    errbot.errBot             Triggering callback_message on VersionChecker
17:18:10 DEBUG    errbot.errBot             Triggering callback_message on Backup
17:18:10 DEBUG    errbot.errBot             Triggering callback_message on Salt
17:18:10 DEBUG    errbot.errBot             Triggering callback_message on ChatRoom
17:18:11 DEBUG    errbot.backends.slack     Ignoring non-event message: {u'reply_to': None, u'text': u"You're not allowed to access this command from this room", u'ok': True, u'ts': u'1460222290.000043'}
17:19:28 DEBUG    errbot.backends.slack     No event handler available for reconnect_url, ig

**Comment by zoni** [comment]
You're passing a string for the value of `allowrooms`, it should be a tuple (or list) containing strings instead. Try `{'allowrooms': ('#cfops',)}` instead.

I will say we could probably made the UX here better (by warning when using incorrect data types, or converting a string -> tuple containing a single string element) here though.

**Comment by jakosky** [comment]
That makes sense. Thanks.

**Comment by zoni** [comment]
My pleasure! Sounds like it's working now for you so I'm closing this, but please let me know if you're still running into issues with the ACLs.
