### ISSUE TITLE
Response from err-salt diverted to private message though config.py not set to divert.

### ISSUE THREAD

**Issue by jakosky** [errbotio/errbot#712]
Since this started after fixing #711, I thought it may be related. Reverting my change to config.py did not change this behavior.

# Config.py
```
# A list of commands which should be responded to in private, even if
# the command was given in a MUC. For example:
#DIVERT_TO_PRIVATE = ('help', 'about', 'status')
DIVERT_TO_PRIVATE = ()
```

# Log
19:12:39 DEBUG    errbot.backends.slack     Processing slack event: {u'text': u'Cob, salt stg .*app.* test.ping', u'ts': u'1460229158.000009', u'user': u'U0A1F7G0J', u'team': u'T0A1F8PL1', u'type': u'message', u'channel': u'C0ZBQ2MSA'}
19:12:39 DEBUG    errbot.backends.slack     Saw an event: {u'channel': u'C0ZBQ2MSA',
 u'team': u'T0A1F8PL1',
 u'text': u'Cob, salt stg .*app.* test.ping',
 u'ts': u'1460229158.000009',
 u'type': u'message',
 u'user': u'U0A1F7G0J'}
19:12:39 DEBUG    errbot.backends.slack     Escaped IDs event text: Cob, salt stg .*app.* test.ping
19:12:39 DEBUG    errbot.errBot             *** frm = #ops/jayjakosky
19:12:39 DEBUG    errbot.errBot             *** username = U0A1F7G0J
19:12:39 DEBUG    errbot.errBot             *** text = Cob, salt stg .*app.* test.ping
19:12:39 DEBUG    errbot.errBot             Called with alternate prefix 'Cob'
19:12:39 DEBUG    errbot.plugins.ACLS       Check salt for ACLs.
19:12:39 INFO     errbot.plugins.ACLS       Matching ACL {'allowprivate': False, 'allowrooms': ['#ops']} against username @jayjakosky for command Salt:salt
19:12:39 INFO     errbot.plugins.ACLS       Check if salt is admin only command.
19:12:39 INFO     errbot.errBot             Processing command 'salt' with parameters 'stg .*app.* test.ping' from #ops/jayjakosky
19:12:39 DEBUG    errbot.errBot             Triggering callback_message on Help
19:12:39 DEBUG    errbot.errBot             Triggering callback_message on Utils
19:12:39 DEBUG    errbot.errBot             Triggering callback_message on Health
19:12:39 DEBUG    errbot.errBot             Triggering callback_message on ACLS
19:12:39 DEBUG    errbot.errBot             Triggering callback_message on Plugins
19:12:39 DEBUG    errbot.errBot             Triggering callback_message on VersionChecker
19:12:39 DEBUG    errbot.errBot             Triggering callback_message on Salt
19:12:39 DEBUG    errbot.errBot             Triggering callback_message on Backup
19:12:39 DEBUG    errbot.errBot             Triggering callback_message on ChatRoom
19:12:40 WARNING  errbot.backends.base       /home/ec2-user/errbot/plugins/jakosky/err-salt/salt.py:88 : msg.type is deprecated and will be removed soon ! Use msg.is_direct or msg.is_group.
19:12:40 WARNING  errbot.plugins.Salt       send message_type is DEPRECATED. Either pass a user identifier or a room to send.
19:12:40 DEBUG    errbot.backends.slack     This is a divert to private message, sending it directly to the user.
19:12:40 INFO     requests.packages.urllib3 Starting new HTTPS connection (1): slack.com
19:12:40 DEBUG    requests.packages.urllib3 "POST /api/im.open HTTP/1.1" 200 None
19:12:40 DEBUG    errbot.backends.slack     Sending direct message to jayjakosky (D0ZAFK283)
19:12:40 DEBUG    errbot.backends.slack     Message size: 229

# err-salt code
```
    @botcmd
    def salt(self, msg, args):
        ''' executes a salt command on systems,
            using the specified environment
            example:
            !salt prod log*.local cmd.run 'cat /etc/hosts'
            !salt prod log*.local test.ping
        '''
        parser = OptionParser()
        (options, args) = parser.parse_args(shlex.split(args))

        if len(args) < 3:
            response = '3 parameters required. see !help salt'
            self.send(msg.frm,
                      response,
                      message_type=msg.type,
                      in_reply_to=msg,
                      groupchat_nick_reply=True)
            return

        environment = args.pop(0)
        targets = args.pop(0)
        action = args.pop(0)

        config_dict = {entry['environment']:entry for entry in self.config}

        api = pepper.Pepper(config_dict[environment]['api_url'], debug_http=False)
        auth = api.login(config_dict[environment]['api_user'],
                         config_dict[environment]['api_pass'],
                         config_dict[environment]['api_auth'])
        ret = api.local(targets,
                        action,
                        arg=args,
                        kwarg=None,
                        expr_form='pcre')
        results = json.dumps(ret, sort_keys=True, indent=4)
        self.send(msg.frm,
                  results,
                  #self.pastebin(config_dict[environment], results),
                  message_type=msg.type,
                  in_reply_to=msg,
                  groupchat_nick_reply=True)
```

**Comment by zoni** [comment]
You're seeing this behaviour because you're sending a groupchat-type message to a person (with this piece of code):

```python
            self.send(msg.frm,
                      response,
                      message_type=msg.type,
                      in_reply_to=msg,
                      groupchat_nick_reply=True)
```

That normally only happens internally for `DIVERT_TO_PRIVATE` messages, hence the confusing *" This is a divert to private message, sending it directly to the user."* message.

As of 4.0.0, we've improved the handling of Identifiers (and by extension, `send()`), so there's no reason to set `message_type` at all. Remove it and you should be fine.

That said though, I would strongly suggest not using `self.send` directly and instead using `return` or `yield` to return responses to the proper user/chatroom automatically.

(If you were using `self.send()` specifically for the `groupchat_nick_reply=True` part, note that as of 4.0.0 setting `GROUPCHAT_NICK_PREFIXED=True` in `config.py` will properly do this for all bot responses.)
