### ISSUE TITLE
Facebook Messenger Platform backend ?

### ISSUE THREAD

**Issue by Djiit** [errbotio/errbot#715]
It might be cool to support [Messenger Platform](https://developers.facebook.com/docs/messenger-platform) (didn't have time to read all the guide, don't know if it's really relevant - I put it here for the record).

**Comment by TetraEtc** [comment]
Just thought I'd mention. To utilize the Messenger API it needs to be connected to a Facebook page and be registered (and approved) as an App there.

**Comment by x0y-gt** [comment]
Is there a plugin to connect with facebook messenger already?

**Comment by zoni** [comment]
I'm not aware of anyone having made one yet, no.

**Comment by x0y-gt** [comment]
@zoni is there a tutorial or something to help me to create a plugin to do that?

**Comment by zoni** [comment]
@x0y-gt Yes, there's some docs on it available at http://errbot.io/en/latest/user_guide/backend_development/index.html. The Telegram and Slack backends are also good to look at as examples.

**Comment by x0y-gt** [comment]
Thanks!

**Comment by cimenx** [comment]
Also, there is Python Wrapper for Facebook Messenger https://github.com/davidchua/pymessenger
Maybe it will help.

**Comment by sijis** [comment]
I'm closing this. There are no plans for the team to include this and it will depend on external contributors to create the necessary backend to make this possible.
