### ISSUE TITLE
xmpp channel message failing

### ISSUE THREAD

**Issue by Betriebsrat** [errbotio/errbot#717]
`self.send(self.build_identifier('dev@conference.jabber.domain.tld'), "test",)`  fails with 

`WARNING errbot.backends.xmpp Received error message: <message to="devbot@jabber.domain.tld/9oednv6no3" type="error" xml:lang="en" from="dev@conference.jabber.domain.tld"><body>test</body><error code="400" type="modify"><bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /></error></message>`

Tested with errbot 4.0.3 on openfire 4.0.2

**Comment by gbin** [comment]
planning on using http://xmpp.org/extensions/xep-0045.html#disco-rooms to check if this is a room or a person

Then port this behavious to other backends
