### ISSUE TITLE
init.d script

### ISSUE THREAD

**Issue by cweiske** [errbotio/errbot#726]
It would be nice if errbot would ship with a init.d script, so that I can let it run automatically on system startup.

I did read http://errbot.io/en/latest/user_guide/setup.html#starting-the-daemon

> If you are going to run your bot all the time then using some process control system such as supervisor is highly recommended. Installing and configuring such a system is outside the scope of this document however.

It would still be nice to have that pre-configured.

**Comment by Djiit** [comment]
As stated in the docs, this is a bit out of scope but we could provide a minimal supervisor configuration like this: 

```ini
# /etc/supervisor/conf.d/errbot.conf

[program:errbot]
# The root dir of your errbot installation (with a valid config.py)
directory=/path/to/your/errbot/dir
# If your are using a virtualenv, make sure to use the correct errbot
command=errbot
# Start Errbot at Supervisor startup.
autostart=true
# Restart Errbot if it crashes.
autorestart=true
```

**Comment by rroemhild** [comment]
You can try my init.d script https://gist.github.com/rroemhild/2e4d7ee5061f56f3300843c6ee8e67b5 I use on Ubuntu 12.04. Copy this script to `/etc/init.d/errbot` and edit the variables. Finally `chmod ug+x /etc/init.d/errbot` and run `service errbot start`.

**Comment by rroemhild** [comment]
And another example for [systemd](https://gist.github.com/rroemhild/6c2c70b659741ab2ba9ba6f5f8be9f46), tested on debian jessie.

Save this file to /etc/systemd/system/errbot.service, reload systemd `systemctl daemon-reload` and start errbot `systemctl start errbot`. Default config is `/etc/errbot/config.py`.

To use another config file modify `Environment="CONFIGFILE=/etc/errbot/config.py"`.
To run errbot from an virtualenv modify `ExecStart`.

Or overwrite the parts in `/etc/systemd/system/errbot.service.d/errbot.conf`:

```
[Service]
Environment="CONFIGFILE=/home/errbot/config.py"
ExecStart=
ExecStart=/home/errbot/venv/bin/errbot --daemon --config $CONFIGFILE
```

At least enable errbot as a service `systemctl enable errbot`.

**Comment by cweiske** [comment]
Thanks for the systemd example - after my upgrade to debian8 this was the easiest to get going.

I added the errbot user at first:
```
$ useradd --no-create-home --no-user-group -g nogroup -s /bin/false errbot
```
and gave it ownership to the log file and the data directory.

**Comment by sijis** [comment]
@cweiske is there anything else that needs to be addressed? If not, can we close this issue?

**Comment by cweiske** [comment]
Maybe explain in the README that running it as separate user improves security.

The systemd file "Service" section would need

> User=errbot

for that, and the useradd command I gave in my previous comment.

**Comment by sijis** [comment]
I've created PR #1030. I didn't think it would make sense to add it to README. Instead I opted to add the suggestions in the daemon confugration section.

If you have some copy that makes sense to add to the README, let me know.
