### ISSUE TITLE
Support a better rendering of cards on errbot -T

### ISSUE THREAD

**Issue by gbin** [errbotio/errbot#731]
BotPlugin.send_card  is a mapping to Slack Attachments and Hipchat Cards.
It is also implemented on the graphics backend (-G) to display nicely the various elemets.
Now for all the other backends included Text, it rolls back to a card.md template to generate the card the best it can.

This generation is pretty ugly on the Text backend, we might want to present it in a more simple way with no table etc like:
_Card_
**Title**
content
Link to image: _link_
key: value
key:value

**Comment by sijis** [comment]
Could this issue be elaborated? Are there issues in Test or is it adding additional supported formats?

**Comment by gbin** [comment]
@sijis done. Thx !
