### ISSUE TITLE
Discord backend ?

### ISSUE THREAD

**Issue by Djiit** [errbotio/errbot#733]
It might be cool to support [Discord](https://discordapp.com/developers/docs/intro).

**Comment by Betriebsrat** [comment]
+1

**Comment by zoni** [comment]
Support for this was started by @gbin in https://github.com/gbin/err-backend-discord and early-user feedback would be welcome.

We're looking for somebody to take over maintenance/maintainership for this backend in the long-term though in order to keep it supported.

**Comment by gbin** [comment]
Now that we have something, please report bugs on the other repo.

Thanks
