### ISSUE TITLE
Allow CHATROOM_PRESENCE to be optional for some backends

### ISSUE THREAD

**Issue by gimmic** [errbotio/errbot#734]
Either CHATROOM_PRESENCE should be ignored for some backends or an optional attribute. 

When using Slack backend the default api method(bot) isn't allowed to join channels, but instead can be invited to channels. This means on each errbot launch you either throw a backend error(due to the script trying to join a channel) or errbot fails to launch if you omit a channel. 

> 16:40:26` DEBUG    urllib3.connectionpool    "POST /api/channels.join HTTP/1.1" 200 None
> ERROR:errbot.plugins.ChatRoom:Joining room '' failed
> Traceback (most recent call last):
>   File "/root/slack3/lib/python3.4/site-packages/errbot/backends/slack.py", line 733, in join
>     self._bot.api_call('channels.join', data={'name': self.name})
>   File "/root/slack3/lib/python3.4/site-packages/errbot/backends/slack.py", line 233, in api_call
>     error=response['error']
> yapsy_loaded_plugin_Slack_0.SlackAPIResponseError: Slack API call to channels.join failed: user_is_bot
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/slack3/lib/python3.4/site-packages/errbot/core_plugins/chatRoom.py", line 28, in callback_connect
>     self._join_room(room)
>   File "/root/slack3/lib/python3.4/site-packages/errbot/core_plugins/chatRoom.py", line 44, in _join_room
>     self.query_room(room).join(username=self.bot_config.CHATROOM_FN, password=password)
>   File "/root/slack3/lib/python3.4/site-packages/errbot/backends/slack.py", line 736, in join
>     raise RoomError("Unable to join channel. " + USER_IS_BOT_HELPTEXT)
> errbot.backends.base.RoomError: Unable to join channel. Connected to Slack using a bot account, which cannot manage channels itself (you must invite the bot to channels instead, it will auto-accept) nor invite people.
> 
> If you need this functionality, you will have to create a regular user account and connect Err using that account. For this, you will also need to generate a user token at https://api.slack.com/web.
> 16:40:26 ERROR    errbot.plugins.ChatRoom   Joining room '' failed
> Traceback (most recent call last):
>   File "/root/slack3/lib/python3.4/site-packages/errbot/backends/slack.py", line 733, in join
>     self._bot.api_call('channels.join', data={'name': self.name})
>   File "/root/slack3/lib/python3.4/site-packages/errbot/backends/slack.py", line 233, in api_call
>     error=response['error']
> yapsy_loaded_plugin_Slack_0.SlackAPIResponseError: Slack API call to channels.join failed: user_is_bot
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/slack3/lib/python3.4/site-packages/errbot/core_plugins/chatRoom.py", line 28, in callback_connect
>     self._join_room(room)
>   File "/root/slack3/lib/python3.4/site-packages/errbot/core_plugins/chatRoom.py", line 44, in _join_room
>     self.query_room(room).join(username=self.bot_config.CHATROOM_FN, password=password)
>   File "/root/slack3/lib/python3.4/site-packages/errbot/backends/slack.py", line 736, in join
>     raise RoomError("Unable to join channel. " + USER_IS_BOT_HELPTEXT)
> errbot.backends.base.RoomError: Unable to join channel. Connected to Slack using a bot account, which cannot manage channels itself (you must invite the bot to channels instead, it will auto-accept) nor invite people.
> 
> If you need this functionality, you will have to create a regular user account and connect Err using that account. For this, you will also need to generate a user token at https://api.slack.com/web.
> DEBUG:errbot.errBot:Trigger callback_connect on Backup

`

**Comment by zoni** [comment]
Hi @gimmic, would you be willing to make a PR to make `CHATROOM_PRESENCE` optional? This would require the same process as explained in https://github.com/errbotio/errbot/issues/753#issuecomment-219277452, only instead of modifying `main.py` it will be necessary to change [chatRoom.py](https://github.com/errbotio/errbot/blob/4.1.3/errbot/core_plugins/chatRoom.py#L25). There it will have to assume an empty tuple if `CHATROOM_PRESENCE` wasn't defined.

**Comment by gbin** [comment]
This is solved, it defaults to an empty tuple now (see the work on errbot --init).
Thanks for reporting usability issues like that !
