### ISSUE TITLE
command doc replaces the wrong '!' in case of alternative prefix.

### ISSUE THREAD

**Issue by gbin** [errbotio/errbot#741]
``` python
     def get_doc(self, command):
        """Get command documentation
        """
        if not command.__doc__:
            return '(undocumented)'
        if self.prefix == '!':
            return command.__doc__
        return command.__doc__.replace('!', self.prefix)
```

so you change your prefix from '!' to '$' and your comment is 'hello !'... you'll end up with 'hello @' ?

**Comment by boidolr** [comment]
What do you want this to be instead? There needs to be some heuristic to find commands.
```
pat = re.compile(r'!(?=\S)')
re.sub(pat, '$', '!test hello! bar! ')
```
would return `''$test hello! bar! '`

**Comment by gbin** [comment]
the quick wat: the commands are available in the bot itself at the self._bot.commands dictionary keys. so basically a regexp match exactly like the one you propose + test the capturing group in self._bot.commands.keys(). + another thing to handle subcommands.

But the best maybe is to refactor and extract from the bot this logic that already exists to detect commands and reuse it here.

**Comment by zoni** [comment]
There's one other approach we could take as well. Use string formatting with `.format()`. So in a docstring you could use:

```
"""
Bla bla, use {prefix}another_command to bla bla
"""
```

and the code which ties the docstring to commands could then replace it using something like `.format(prefix=self._bot.config.BOT_PREFIX)`

**Comment by boidolr** [comment]
That's what I actually already used locally.
Anyway, I've sent you a possible fix.

**Comment by gbin** [comment]
@boidolr I like it thanks !
