### ISSUE TITLE
Hipchat SRV record check failing

### ISSUE THREAD

**Issue by wroersma** [errbotio/errbot#745]
So I've been struggling with this issue for a few days now and I have updated my records to have SRV records in place that it should be picking up. I've used external website checks for the SRV records in which they find them however errbot is still not picking everything up properly. I've read through the [documentation ](https://media.readthedocs.org/pdf/errbot/latest/errbot.pdf)heavily so if it's something I'm simply missing I'm sorry but I can't figure this out. Please let me know if you have any suggestions or need any more information. 

07:55:16 INFO     errbot.storage            Init storage of Backup
DEBUG:errbot.main:serve from <yapsy_loaded_plugin_Hipchat_0.HipchatBackend object at 0x7fa2970991d0>
07:55:16 DEBUG    errbot.main               serve from <yapsy_loaded_plugin_Hipchat_0.HipchatBackend object at 0x7fa2970991d0>
DEBUG:sleekxmpp.xmlstream.resolver:DNS: Querying SRV records for mydomain.com
07:55:16 DEBUG    sleekxmpp.xmlstream.resol DNS: Querying SRV records for mydomain.com
DEBUG:sleekxmpp.xmlstream.resolver:DNS: No SRV records for mydomain.com.
07:55:16 DEBUG    sleekxmpp.xmlstream.resol DNS: No SRV records for mydomain.com.
DEBUG:sleekxmpp.xmlstream.resolver:DNS: Querying mydomain.com for AAAA records.
07:55:16 DEBUG    sleekxmpp.xmlstream.resol DNS: Querying mydomain.com for AAAA records.

**Comment by zoni** [comment]
Are you using the hosted/cloud version of HipChat, or an on-premises install of HipChat server?

**Comment by wroersma** [comment]
It's based on the ami image hosted on aws. So on-premises install of hipchat.

**Comment by zoni** [comment]
Are you absolutely sure you have your SRV records setup correctly? Most likely they are misconfigured.

Can you connect to your HipChat server without issue using a regular XMPP client such as Gajim or Psi?

That said though, you should be able to bypass the SRV lookup and directly specify the server errbot should connect to. They keyword for that is `server` in `BOT_IDENTITY`, should it would look along the lines of:

```
BOT_IDENTITY = {
    'username': 'err@yourdomain.tld',
    'password': 'secret',
    'server': ('host.domain.tld',5222), # here's the important server override
    'token'    : 'secret',
    'endpoint' : 'https://host.domain.tld'
```

**Comment by wroersma** [comment]
I have the server set and it still doesn't work. I can connect to hipchat using pidgin and Gajim but I had to manually configure the server setting. Direct message me if you want the domain name if you want to check if I messed it up(I don't want the domain public)

**Comment by wroersma** [comment]
Ok I actually got further down the path here with an issue with it trying to connect to mydomain.com vs hipchat.mydomain.com 
ERROR:sleekxmpp.xmlstream.xmlstream:Could not match certficate against hostname: mydomain.com
08:52:40 ERROR    sleekxmpp.xmlstream.xmlst Could not match certficate against hostname: mydomain.com
I also have XMPP_CA_CERT_FILE = None in the config

**Comment by wroersma** [comment]
Actually It's a problem with the hipchat server currently returning the wrong cert. However still slightly confused why it things the domain name is "mydomain.com" vs hipchat.mydomain.com which is what the server is using

**Comment by zoni** [comment]
I'd be real curious as to your actual SRV records and your configured `BOT_IDENTITY`. If you could share those with me that would be helpful (with token/password sanitized, obviously :smile:).

Feel free to send those to me via [Gitter](https://gitter.im/zoni) or [email](mailto:nick@groenen.me) ([gpg](https://nick.groenen.me/about/NickGroenen.pgp)).

**Comment by wroersma** [comment]
Thanks for all the awesome help!!!! go ahead and close this out

**Comment by gbin** [comment]
@wroersma w00t

**Comment by venuinu** [comment]
@wroersma  What was the fix? I am facing similar issue.

**Comment by wroersma** [comment]
hmm it was working but it's currently broken now on a different issue and I haven't had time to go back to it

**Comment by venuinu** [comment]
Never mind. I have found the problem, user should have all the permissions(including manage rooms) to login in to hipchat room.
