### ISSUE TITLE
sentry config entries cannot be removed

### ISSUE THREAD

**Issue by cweiske** [errbotio/errbot#753]
Despite being advertised as "optional" in the config comments, I cannot remove the sentry configuration settings:

```
root@dojo:~> errbot -c /etc/errbot/bookmarks/config.py 
14:48:09 ERROR    errbot.err                You are missing configs defined from the template :
14:48:09 ERROR    errbot.err                Missing config : SENTRY_DSN
14:48:09 ERROR    errbot.err                Missing config : BOT_LOG_SENTRY
14:48:09 ERROR    errbot.err                Missing config : SENTRY_LOGLEVEL
```

**Comment by zoni** [comment]
In the early days of errbot we didn't have as flexible config checking, so we enforced (and still do) that every option defined in `config-template.py` needs to be in your own `config.py` as well.

To make the sentry items optional in the sense that they can be omitted from the config entirely, we will have to comment out the [\*SENTRY\*](https://github.com/errbotio/errbot/blob/4.1.3/errbot/config-template.py#L119-L123) variables in `config-template.py`.

We'll also have to handle the possibility of the config item not being present in the user config then by modifying some [code in errbot/main.py](https://github.com/errbotio/errbot/blob/4.1.3/errbot/main.py#L35-L48). Using [getattr](https://github.com/errbotio/errbot/blob/4.1.3/errbot/main.py#L115) we can make it get a default value of `False` if it was unspecified.

Would you be willing to make a PR for this?

**Comment by cweiske** [comment]
Sorry, no.

**Comment by zoni** [comment]
I'll fix this before our next (non-patch) release goes out then, but leave this open for now in case anyone else would like to try working on this. It's a perfect issue for new contributors to work on.

**Comment by gbin** [comment]
This is fixed, now the config can be truly minimal (see the new feature errbot --init and the generated config.py). Thanks for pointing out usability issues like this !
