### ISSUE TITLE
Slack backend: Sending a message to an identifier created from "#channel/user" sends a direct message

### ISSUE THREAD

**Issue by tynril** [errbotio/errbot#757]
This seems to have started recently, most likely with 4.1.3. Previously, this type of identifier would send a message on the channel, which is the expected behavior.

To reproduce this issue, the simplest way is to implement `callback_message` and simply use `self.send(message.frm, "something")`. When the received message is posted on a channel, `frm` will use this type of identifier, and "something" will be sent as a private message to the author of the channel message, instead of as a reply on the channel.

A workaround for this issue is to re-build another identifier:
```
send_to = self.build_identifier("<#{}>", message.frm.channelid)
self.send(send_to, "something")
```
(Of course, this only works if the input message has a defined `channelid`, and it is specific to the Slack backend.)

**Comment by zoni** [comment]
> To reproduce this issue, the simplest way is to implement `callback_message` and simply use `self.send(message.frm, "something")`. When the received message is posted on a channel, `frm` will use this type of identifier, and "something" will be sent as a private message to the author of the channel message, instead of as a reply on the channel.

This is actually the intended behaviour. In generic terms, `message.frm` on a group message points to the user sending that message. Responding directly to that identifier is supposed to go to that user as opposed to the channel itself.

If you always want to respond in the same channel/chat where a message was posted, you must send to `message.frm` when `message.is_direct` and `message.to` when `message.is_group`.

(I agree that can be a little confusing at first sight though. We should stick this somewhere visible in the documentation)

**Comment by tynril** [comment]
Oh alright! That makes sense. I've just used
```
send_to = message.frm if message.is_direct else message.to
```
and it works as I was expecting.

Thank you!
