### ISSUE TITLE
Slack Messaging to Channels

### ISSUE THREAD

**Issue by jlu368** [errbotio/errbot#784]
I was trying to send messages to channels in Slack, but I couldn't get it to work, so I took a look at the backend code in text.py, and I found a bug. 
```
def build_identifier(self, text_representation):
        if text_representation.startswith('#'):
            return self.query_room(test_representation[1:])
        return TestPerson(text_representation)
```
The 3rd line of the function should be `return self.query_room(text_representation[1:])`, I think.

**Comment by gbin** [comment]
this should be correct on master, can you give it is try ? Thanks !

**Comment by jlu368** [comment]
Ah yeah, it works now.  Thanks!

**Comment by gbin** [comment]
np
