### ISSUE TITLE
Plugin unblacklist does not work anymore

### ISSUE THREAD

**Issue by ramonamis** [errbotio/errbot#789]
Hello,

After upgrade to 4.2.1 the unblacklist function of plugin is not working anymore.

[5:22 PM] Ramona Misaila: !plugin activate VersionChecker
[5:22 PM] Hilda-san (Bot): Plugin VersionChecker activated.
[5:22 PM] Ramona Misaila: !plugin unblacklist VersionChecker
[5:22 PM] Hilda-san (Bot): Plugin VersionChecker removed from blacklist

I can also see the plugin active in the !plugin status. After restart, I still get this message:

Notice: ! is blacklisted, use VersionChecker plugin unblacklist VersionChecker to unblacklist it.

Do you have any ideas about how i can disable this? is not a very critical bug, however is very annoying to the bot admins to get that message after every restart.

Best,
Ramona

**Comment by gbin** [comment]
I can't reproduce it, do you try on the Text backend ? Can you try on another plugin than the VersionChecker to see if it works ?

**Comment by gbin** [comment]
meanwhile I fixed the broken message at least :) 33c7e7532146611d63ce655f77c47b34f188f7e2

**Comment by ramonamis** [comment]
Hello, 

So i tried with another plugin

```
[11:07 AM] Ramona Misaila: !plugin blacklist CookieBot
[11:07 AM] Hilda-san (Bot): Plugin CookieBot is now blacklisted
```
Then restart:
```
[11:07 AM] Hilda-san (Bot): Notice: VersionChecker is blacklisted, use ! plugin unblacklist VersionChecker to unblacklist it
[11:07 AM] Ramona Misaila: !plugin unblacklist CookieBot
[11:07 AM] Hilda-san (Bot): Plugin CookieBot is not blacklisted
[11:07 AM] Ramona Misaila: cookies
[11:07 AM] Hilda-san (Bot): Somebody mentioned cookies? Om nom nom!
```

It looks like the plugin status is saved in memory and is not kept after restart.

**Comment by gbin** [comment]
ha ok, this is the symptom of something else !
How do you stop your bot ?

**Comment by gbin** [comment]
More importantly, do you have that at the end of your log when you shut down the bot ?
```
14:21:42 DEBUG    errbot.storage            Closed storage 'text_backend'
14:21:42 INFO     errbot.plugin_manager     Shutdown.
14:21:42 DEBUG    errbot.storage            Closed storage 'core'
14:21:42 INFO     errbot.plugin_manager     Bye.
14:21:42 DEBUG    errbot.storage            Closed storage 'repomgr'
14:21:42 INFO     errbot.cli                Process exiting

```

**Comment by ramonamis** [comment]
no, it actually does not log anything because these storage plugins are not active. I am checking now how to activate them.

**Comment by ramonamis** [comment]
actually, the bot connects after a while,it just does not react to commands and then it resets and logsout:

```
16:01:42 DEBUG    sleekxmpp.xmlstream.xmlst RECV: <message from="23412414@chat.hipchat.com/mac_macweb||proxy|proxy-b313.hipchat.com|5242" type="chat" mid="7a8ca2c9-7348-44a6-9ce8-b011623ff22b" ts="1467036102.206667" to="61338_1144380@chat.hipchat.com/none||proxy|pubproxy-d300.hipchat.com|5292"><body>!help </body><x xmlns="http://hipchat.com/protocol/muc#room"><type /><notify>1</notify><message_format>text</message_format></x><active xmlns="http://jabber.org/protocol/chatstates" /></message>
```
```
16:03:14 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: socket_error
16:03:14 ERROR    sleekxmpp.xmlstream.xmlst Socket Error #104: Connection reset by peer
16:03:14 DEBUG    sleekxmpp.xmlstream.xmlst reconnecting...
16:03:14 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: session_end
16:03:14 DEBUG    sleekxmpp.xmlstream.xmlst SEND (IMMED): </stream:stream>
16:03:14 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: socket_error
16:03:14 WARNING  sleekxmpp.xmlstream.xmlst Failed to send </stream:stream>
16:03:14 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: session_end
16:03:14 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: socket_error
16:03:14 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: disconnected
16:03:14 INFO     errbot.core               Disconnect callback, deactivating all the plugins.
```

**Comment by gbin** [comment]
Those are not storage plugins, those are namespaces in the current storage (which is pickling by default). If they are not closed at shutdown they have no chance to persist the pending changes. Be sure to close shutdown your bot correctly (with ctrl-c or signal 1)

**Comment by fuzzyami** [comment]
also seeing these annoying messages on my errbot instance every few days...
