### ISSUE TITLE
Hipchat backend asks to join room by id, even thought conf already specifies it

### ISSUE THREAD

**Issue by ramonamis** [errbotio/errbot#801]
```
17:07:47 INFO     errbot.backends.hipchat   Found 61338_emergency_handling@conf.hipchat.com to be the room Emergency handling, consider specifying this directly.
```

In the config file i have: 

```
CHATROOM_PRESENCE = (u'DH release channel', u'hilda-test', u'Emergency handling')
```

ACL's are specified in the same way. I think this is causing the backend to check with hipchat and get the room id, in which case it will reach the rate limit when users have many rooms.

Also, there are many other requests:

```
17:13:52 DEBUG    requests.packages.urllib3 "GET /v2/user?include-guests=true&start-index=100&max-results=100 HTTP/1.1" 200 3133
17:13:52 DEBUG    requests.packages.urllib3 "GET /v2/user?include-guests=true&start-index=200&max-results=100 HTTP/1.1" 200 None
17:13:52 DEBUG    requests.packages.urllib3 "GET /v2/user?include-guests=true&start-index=300&max-results=100 HTTP/1.1" 200 None
17:13:53 DEBUG    requests.packages.urllib3 "GET /v2/user?include-guests=true&start-index=400&max-results=100 HTTP/1.1" 200 None
17:13:53 DEBUG    requests.packages.urllib3 "GET /v2/user?include-guests=true&start-index=500&max-results=100 HTTP/1.1" 200 3732
17:13:54 DEBUG    requests.packages.urllib3 "GET /v2/user?include-guests=true&start-index=600&max-results=100 HTTP/1.1" 200 1761
```

which can also make hipchat reach the rate limit.

**Comment by gbin** [comment]
It should stay in an LRU cache and not requery everytime, we need to investigate this.

**Comment by ramonamis** [comment]
ok so I think i found the connection between rate limiting and these many requets: as soon as the mentions part works, it sends way too many requests to hipchat to get user mentions.

I have removed the fix the the previous issue and now everything works just fine; that is the only connection i can make.

note: i tried downgrading to version 3, it does not work. it always installs version 4 with it.

**Comment by TonyLeeVT** [comment]
I have this same issue.  Same error and same rate limiting error message.  I have tried specifying the longer room name and that does not fix the issue.

**Comment by pdarg** [comment]
I am also experiencing this issue. I'd be happy to take a stab at a PR if someone can point me in the right direction.

**Comment by sijis** [comment]
Based on that article, there is no need to do this as the service is being shutdown in about 5 weeks.

Atlassian is providing instructions (https://www.atlassian.com/partnerships/slack/migration) how migrate to Slack.

We do have a functional Slack backend to support those organizations migrating.
