### ISSUE TITLE
Webserver Config Plugin [<class 'int'>] is not the same type as [<class 'str'>]

### ISSUE THREAD

**Issue by bnikolaus** [errbotio/errbot#805]
I just setup a new instance of errbot and was trying to configure the Webserver and ran into the following issue. let me know if there is anything more I can do anything to help.

**Issue** 
>>> !plugin config Webserver {'HOST': '0.0.0.0', 'PORT': '3141', 'SSL': {'certificate': '', 'enabled': False, 'host': '0.0.0.0', 'key': '', 'port': 3142}}
Incorrect plugin configuration: 3141 [<class 'int'>] is not the same type as 3141 [<class 'str'>]

**Version Information**
➜  _errbot  ./bin/pip freeze
ansi==0.1.3
apipkg==1.4
beautifulsoup4==4.4.1
bottle==0.12.9
cffi==1.7.0
colorlog==2.7.0
cryptography==1.4
daemonize==2.4.6
dnspython3==1.12.0
docutils==0.12
errbot==4.2.2
execnet==1.4.1
idna==2.1
Jinja2==2.8
Markdown==2.6.6
MarkupSafe==0.23
mock==2.0.0
pbr==1.10.0
pep8==1.7.0
py==1.4.31
pyasn1==0.1.9
pycparser==2.14
Pygments==2.1.3
pygments-markdown-lexer==0.1.0.dev39
pyOpenSSL==16.0.0
pytest==2.9.2
pytest-xdist==1.14
requests==2.10.0
rocket-errbot==1.2.5
six==1.10.0
threadpool==1.3.2
waitress==0.9.0
WebOb==1.6.1
WebTest==2.0.21
Yapsy==1.11.223

**Comment by zoni** [comment]
It looks like you're passing the `port` argument as a string rather than an integer. Note the difference between `'PORT': '3141'` (incorrect) as opposed to `'PORT': 3141` (correct)

**Comment by bnikolaus** [comment]
Ahh indeed that was the issue, thanks for assist.
