### ISSUE TITLE
Feature: add cmd filter option to allow only rooms while denying private

### ISSUE THREAD

**Issue by Betriebsrat** [errbotio/errbot#807]
Currently allowrooms includes private commands.  
Would be nice to have a cmdfilter that allow a command to be called ONLY in rooms, while denying it in private.

**Comment by zoni** [comment]
This is [already possible](https://github.com/errbotio/errbot/blob/4.2/errbot/core_plugins/acls.py#L94-L99) with ACLs. :smile: Use `allowprivate: False` for this.
