### ISSUE TITLE
Slack backend ignores custom username (Slack Webhooks) 

### ISSUE THREAD

**Issue by nlochschmidt** [errbotio/errbot#812]
I can provide a custom username when I send a message through the Slack webhook API, but when I check the values of `msg.frm`, `msg.frm.username`, etc on the received message in errbot, I only get the bot-id instead of the username. 

I also get this error message 

```
15:40:16 ERROR    errbot.backends.slack     Cannot find user with ID <bot-id>
```

I can send a message via the Slack Webhook with a custom username like so:

``` bash
~ % local payload='
  {
    "channel": "#testroom",
    "username": "acmebot",
    "text": "I am alive"
  }'
~ % curl -X POST --data-urlencode "payload=$payload" https://hooks.slack.com/services/<team-id>/<bot-id>/<hook-id>
```

With debugging turned on, I can see that the message arrives in errbot with the username I have set, but this information seems to be discarded by the Slack backend for errbot:

```
Saw an event: {u'bot_id': u'<bot-id>',
 u'channel': u'<channel-id>',
 u'subtype': u'bot_message',
 u'team': u'<team-id>',
 u'text': u'I am alive',
 u'ts': u'1469022016.000022',
 u'type': u'message',
 u'user_team': u'<team-id>',
 u'username': u'acmebot'}
```

**Comment by zoni** [comment]
I believe this was fixed with #895. If this is still not working (on master) then please re-open.
