### ISSUE TITLE
Requiring BOT_DATA_DIR

### ISSUE THREAD

**Issue by medecau** [errbotio/errbot#817]
I'm trying to use errbot on heroku. These are disposable environments. 
I've been using [err-storage-sql](https://github.com/errbotio/err-storage-sql) to persist data on postgresql.

But I have found the BOT_DATA_DIR requirement to be out of place for this kind of deployment.
BOT_DATA_DIR should be unnecessary when using other storage plugins. Currently I have to maintain a "DO_NOT_DELETE" file under the directory structure.

*I may be doing something wrong if so please tag this issue as a question.*

**Comment by gbin** [comment]
We are actually using BOT_DATA_DIR to store the Errbot plugins themselves. If you are only using static plugins (not using `!repos install`) it is true that this directory becomes useless.

Maybe we can put it optional with a good error message if a user tries to do `!repos install` or is trying to use the pickled persistence ?

**Comment by medecau** [comment]
I did not consider the plugin repos.

Making it optional would be the best way to go.
If a user tries to use pickled persistence and BOT_DATA_DIR is missing then maybe fail.

Better messages are always a plus.

I also noticed I cannot change BOT_LOG_FILE to use stdout.
I tried pointing it to /dev/stdout but am getting errors. Should this be a new issue?

**Comment by zoni** [comment]
> I also noticed I cannot change BOT_LOG_FILE to use stdout.

Errbot logs to stderr by default (at least I think it's stderr rather than stdout, because that's default python logging behaviour).

So you could set `BOT_LOG_FILE = None` but you'll still get your logs on stderr. Wouldn't that work for your use-case? If not, please do open a separate issue on that so we can discuss it.

**Comment by medecau** [comment]
@zoni it works fine. Thank you.
