### ISSUE TITLE
Check if we are in a virtual env is broken for python3

### ISSUE THREAD

**Issue by RaphYot** [errbotio/errbot#826]
Looking at this line:
https://github.com/errbotio/errbot/blob/master/errbot/plugin_manager.py#L56

And this thread:
http://stackoverflow.com/questions/1871549/python-determine-if-running-inside-virtualenv

The check for virtual env doesn't work for python3, this is broken in the official docker image, installing plugin with requierements will break as the code think we are outside a venv.

The following (edit):
```
    if hasattr(sys, 'real_prefix') or (hasattr(sys, 'base_prefix') and (sys.base_prefix != sys.prefix)):
```

Should work in our case.

**Comment by gbin** [comment]
Thanks ! Can you directly open a pull request ?

**Comment by RaphYot** [comment]
Sure, there you go!
https://github.com/errbotio/errbot/pull/828

**Comment by jasedit** [comment]
Is this what's causing my log files to stop the moment a requirements.txt file is processed? I had noticed that behavior, but hadn't dug into it enough to figure out what was happening.

**Comment by RaphYot** [comment]
I don't think so, this will cause the packages in requierement.txt to be installed with the `--user` option in pip. Which means that if you run errbot in a virtualenv the packages won't be available after the plugin installation.
I don't see how this could stop logs for working, but I could see logs going on in the console while and after the pip install were done.
