### ISSUE TITLE
Inject HTML directly to HipChat backend

### ISSUE THREAD

**Issue by dtroberts** [errbotio/errbot#827]
From what I can see, it is not possible to insert HTML directly into a response to HipChat, but only through a Markdown template. This disallows the use of table formatting. Is there a way to do so which I'm missing, or is this not implemented? Is there any reason to not allow the use of HTML directly?

**Comment by zoni** [comment]
>  Is there a way to do so which I'm missing, or is this not implemented?

HipChat `room` objects have a [notify](http://errbot.io/en/latest/errbot.backends.hipchat.html#errbot.backends.hipchat.HipChatRoom.notify) method for this which you can call to send a native notification. Note that by using this, your plugin will obviously only work on HipChat.

> Is there any reason to not allow the use of HTML directly?

Yes. Errbot is meant to work with various different chat networks which all have their own way of formatting;  XMPP uses XHTML-IM, Slack  has a custom markdown-inspired format, HipChat has limited XHTML-IM or HTML depending on the used API call, Telegram does markdown, etc, etc.

Errbot plugins use markdown which the bot automatically translates internally for you into a representation that is supported by the network. This way a plugin works with no code changes on every backend.
