### ISSUE TITLE
[QUESTION] Errbot Deployment Model?

### ISSUE THREAD

**Issue by tspicer** [errbotio/errbot#833]
Was exploring the possibility of leveraging AWS API Gateway and Lamda for errbot. The original approach we were thinking of taking was wrapping errbot into a docker container and deploy it that way. This certainly works, but was curious if using API Gateway and Lamda was a viable path and if it was, is anyone using that pattern? If it is not currently possible, is this something that is technically not feasible or more a situation that would require customization/enhancement to make a reality?

**Comment by zoni** [comment]
I'm unfamiliar with Lambda and the API gateway, however, it is my understanding that those work by temporarily spawning a service which handles a request, then dies once it has been handled.

Errbot runs as a daemon, permanently connected to a chat network of your choice. I believe that makes it unsuitable. But as I said, I'm not familiar with it, so I may be completely wrong.

**Comment by sijis** [comment]
What is the flow you envision with that setup?
Something to consider that wasn't explicitly noted in @zoni's comment is that there's no state in lambda and there is a max of a 5 min execution limit. So, as errbot connects to a backend service (slack, irc, hipchat, etc), that will count towards the execution time on your lambda function. This isn't necessarily a show stopper but something to consider in your approach.

**Comment by zoni** [comment]
This looks stale, so I'm going to close it. Feel free to post back with more information if there are still unanswered questions though.

**Comment by GavrielNsof** [comment]
Hello @tspicer I would like to know if you implemented this and if somebody knows if Errbot on lambda + api gateway is a good practice (if I want to keep a state there do I must use some kind of a DB or I can go stateless?)
Otherwise, what is a good way to keep Errbot highly available?
