### ISSUE TITLE
Pip should not be invoked from pip.main(), and is not thread safe

### ISSUE THREAD

**Issue by rawouter** [errbotio/errbot#835]
This is linked to the issue I opened at pypa/pip#3889

It was stated that pip has no programming interfaces, and so pip.main() should be avoided at:
https://github.com/errbotio/errbot/blob/master/errbot/plugin_manager.py#L58

The only supported way of calling pip from within another program is via subprocess.Popen().

As pip is not thread safe, invoking pip.main() from within a thread may result in corrupted packages. Also, it will not work in the case of the plugin_manager because of pypa/pip#3889 breaking the pip install in threading.

This issue is preventing the bot to install packages when used in threading mode, which break the usage of threading mode in my case.

**Comment by zoni** [comment]
> It was stated that pip has no programming interfaces, and so pip.main() should be avoided at:
https://github.com/errbotio/errbot/blob/master/errbot/plugin_manager.py#L58

> The only supported way of calling pip from within another program is via subprocess.Popen().

I do not think switching from `pip.main(....)` to using `subprocess` would be very difficult, nor should it affect any functionality. We'd have to try some variations of installing inside a virtualenv, outside a virtualenv, with missing packages, etc etc though.

Are you in a position to experiment yourself and report back your results?

**Comment by rawouter** [comment]
@zoni created PR #836 
Made some tests in python3 venv, this seems ok and solve my original issue.
