### ISSUE TITLE
Failed getting from storage with plugin namespace

### ISSUE THREAD

**Issue by asfaltboy** [errbotio/errbot#865]
I am trying to get stored data with `errbot --storage-get`, and it's failing quietly (no traceback):

```
$ ENV_FILE=/opt/mybot/.env errbot --storage-get ReportBusPlugin
12:35:26 INFO     errbot.cli                Config check passed...
12:35:26 INFO     errbot.specific_plugin_ma storage search paths {'/opt/mybot/.virtualenvs/mybot/lib/python3.5/site-packages/errbot/storage'}
12:35:26 INFO     errbot.specific_plugin_ma Found those plugings available:
12:35:26 INFO     errbot.specific_plugin_ma         Memory  (/opt/mybot/.virtualenvs/mybot/lib/python3.5/site-packages/errbot/storage/memory.py)
12:35:26 INFO     errbot.specific_plugin_ma          Shelf  (/opt/mybot/.virtualenvs/mybot/lib/python3.5/site-packages/errbot/storage/shelf.py)
12:35:26 INFO     errbot.bootstrap          Found Storage plugin: 'Shelf'
Description: This is the storage plugin for the traditional shelf store for errbot.
12:35:26 WARNING  yapsy                     Plugin candidate '/opt/mybot/.virtualenvs/mybot/lib/python3.5/site-packages/errbot/storage/memory.plug'  rejected by strategy 'SpecificBackendLocator'
No module named 'yapsy_loaded_plugin_Telegram_0'
```

I'm obviously using the Telegram backend, and errbot is not currently running (otherwise I get a "Storage does not appear to have been opened yet" error).

Additionally, setting/getting config via chat fails too, with the message: "Unknown plugin or the plugin could not load ReportBusPlugin".

**Comment by sijis** [comment]
Errbot version?

**Comment by asfaltboy** [comment]
Python 3.5.1, `errbot` version 9.9.9 (checked out from git, commit `f2af0d7`)

**Comment by zoni** [comment]
I notice your log only shows INFO and WARNING level messages. Do you get more details when you set the log level to DEBUG in `config.py`? Perhaps this can point us in the right direction.

**Comment by asfaltboy** [comment]
I can't recall what I did to resolve this last time, so this may be a different issue, but...

I still have issues with using `storage-get` command, now returning `{}` for a plugin that clearly has configuration stored in persistent store (MyPlugin.config has a lot of data when used in commands).

@zoni I can't seem to be able to set logging to DEBUG level as the call to bootstrap (which sets logging level according to configuration) happens after this command runs, and [the `root_logger` defaults to INFO][1]. I tried to upgrade to latest errbot release on pypi (5.1.3) and have the same issue.

Also, we're still returning the misleading error `Storage does not appear to have been opened yet` when errbot is running (should we update docs to mention this requirement?).

[1]: https://github.com/errbotio/errbot/blob/4.3.3/errbot/logs.py#L16

**Comment by sijis** [comment]
It does seem that the issue has been answered. Also, the command seem to work as expected in latest release (6.1.0)
```
$ errbot --storage-get core
{'configs': {'Webserver': {'HOST': '0.0.0.0', 'PORT': 3141, 'SSL': {'certificate': '', 'enabled': False, 'host': '127.0.0.1', 'key': '', 'port': 3142}}}}
$ errbot --storage-get repomgr
...
```
