### ISSUE TITLE
Plugin breaks when multiple instances of same plugin found 

### ISSUE THREAD

**Issue by asfaltboy** [errbotio/errbot#870]
We should probably have a detection precedence when searching for plugin to load:
- local plugin dir
- custom plugin dir
- github maintained plugin dir

**Comment by sijis** [comment]
What order does it match now?
Also which errbot version?

**Comment by asfaltboy** [comment]
Honestly, I have no clue! Yapsy is a weird creature, and I couldn't follow the code to understand how errbot's `BotPluginManager` really loads all the plugins. Regardless, it's less about the order and more that it might count the same plugin in different locations multiple times (it should only allow a unique plugin to be loaded once).

**Comment by sijis** [comment]
Gotcha. To be clear, the issue is that the same plugin is found in multiple locations (and loaded), so your suggestion is to find it (via a precedence order) and load it once.

**Comment by asfaltboy** [comment]
Correct, at least as far as I understand the cause

**Comment by sijis** [comment]
Last thing. Python and errbot version

**Comment by asfaltboy** [comment]
Python 3.5.1, `errbot` version 9.9.9 (checked out from git, commit f2af0d7)

**Comment by sijis** [comment]
yapsy is no longer managing plugins, so its likely this issue has been resolved.
If not, a new issue can be opened with newer data.
