### ISSUE TITLE
Slack backend sanitize_uris() breaks links of shared files

### ISSUE THREAD

**Issue by capdevc** [errbotio/errbot#872]
As far as I can tell, it's impossible to get the file URL for a shared file from the slack event.

example from the file_shared notification message:

```
 'text': '<@U18CKQZSM|cc> uploaded a file: '
         '<https://liveintent.slack.com/files/cc/F2PK11R6K/core.py|core.py>',
```

that message text in the event gets turned into:

```
@cc uploaded a file: core.py
```

The whole URL gets deleted by the regex at line 812 in sanitize_uris():

```
text = re.sub(r'<([^\|>]+)\|([^\|>]+)>', r'\2', text)
```

Maybe there should be a way to turn the sanitation off? I'm happy to send a PR with a fix if given some guidance on what the correct fix should be.

**Comment by sijis** [comment]
What if the term 'uploaded a file:' is a term to use to then filter that regex from running? That's just a quick thought.

**Comment by capdevc** [comment]
The file shared events actually set the event subtype to 'file_shared' so we can check against that before sanitizing.

**Comment by sijis** [comment]
I wasn't sure if it came as a different msg type. Using that does seem like a better filter key

**Comment by capdevc** [comment]
I now think that this requires a little more thought about how to handle file sharing. For my particular use case, I'm going to use a fork that catches the file_share subtype message and pulls the file private_url from the 'file' part of the event and packs that into the message 'extras' dict.

I'm not sure how/if this should be handled in errbot

**Comment by sijis** [comment]
Closing. If this is still needed, this can be reopened.
