### ISSUE TITLE
Does webhook support specify port?

### ISSUE THREAD

**Issue by MarloweW** [errbotio/errbot#877]
Hi, all:

I am writing webhook for my plugin. I found the docs says:

>This will listen for POST requests on http://yourserver.tld:yourport/test/, and return "OK" as the response body.

so, what is yourport? And how could I specify it with config?

```
!config Webserver
```
respond:
```
Command "config" / "config Webserver" not found.
Did you mean "!plugin config" ?
```

**Comment by MarloweW** [comment]
It seems I need to run 
```
!plugin activate Webserver
!plugin config Webserver 
{'HOST': '0.0.0.0',
'PORT': 3141,
'SSL': {'certificate': '',
        'enabled': False,
        'host': '0.0.0.0',
        'key': '',
        'port': 3142}}
```
Where does those configuration stored?

**Comment by asfaltboy** [comment]
I may be wrong, but I think the docs need to be updated to replace every instance of `!config` with `!plugin config`

**Comment by sijis** [comment]
@asfaltboy You are right, the docs should be updated appropriately.
@MarloweW The details are stored in the plugin store, (default: Webserver.db file), unless you use another backend.

**Comment by MarloweW** [comment]
@sijis  I found Webserver.db file, but I didn't find docs about storage backend. Put *.db file into git repo seems inappropriate, and it'll mess production config with development config.

**Comment by sijis** [comment]
@marlowew there are several backend plugins that support SQL based databases (postgres, mariadb, MySQL, etc). You'll see those in the plugin section.

There is also a feature where you can extract the bot configs. I believe it does all the plugin data too. More details about that are here: http://errbot.io/en/latest/user_guide/provisioning.html

**Comment by sijis** [comment]
Also, anything stored in the db is persistent across errbot restarts, assuming the db files themselves aren't deleted.

**Comment by MarloweW** [comment]
That helps. Thank you @sijis.
