### ISSUE TITLE
Support matrix

### ISSUE THREAD

**Issue by derek-austin** [errbotio/errbot#884]
In order to let us help you better, please fill out the following fields as best you can:
### I am...
- Suggesting a new feature
### I am running...
- Errbot version: 4.3.4
- OS version: Fedora 23
- Python version: 3.4.3
- Using a virtual environment: yes
### Issue description

My suggestion is support http://matrix.org/ 
Why?
- Open standard
- Open source
- Server on premises
- Decentralized persistent communication
- Client (riot) on multiple platforms
- Optional end-to-end encryption
### Steps to reproduce

Feature missing
### Additional info

Sending the issue just to draw attention into it.

**Comment by zoni** [comment]
This would have to come from somebody in the community willing to write and maintain such a backend. Our core contributors currently already have their hands full staying on top of the current backends we support.

We are definitely willing to offer guidance and help to anyone willing to implement and support a matrix backend for errbot though. Just get in touch with me or @gbin on [Gitter](https://gitter.im/errbotio/errbot) if you need help.

**Comment by derek-austin** [comment]
Seem that someone is on it: https://github.com/SShrike/err-backend-matrix

**Comment by andrewthetechie** [comment]
#closeit

**Comment by sijis** [comment]
A more "recent" seems to be https://github.com/0xffea/err-backend-matrix.

**Comment by dud1337** [comment]
Why was this closed?

**Comment by andrewthetechie** [comment]
@dud1337 there are existing backend for matrix already. Also, backends are maintained by the community, not part of errbot-core
