### ISSUE TITLE
Send message from cli using the xmpp session of a errbot deamon

### ISSUE THREAD

**Issue by s-nt-s** [errbotio/errbot#891]
This is the scenario: 
- I have a errbot daemon with a open session in some xmpp server.
- I have a external script that have to send a xmpp message

Is there any way this script could run a command to send the message through the errbot daemon like it was a service?

**Comment by zoni** [comment]
> Is there any way this script could run a command to send the message through the errbot daemon like it was a service?

Definitely! My suggestion would be to write a plugin which listens for a specific [webhook](http://errbot.io/en/latest/user_guide/plugin_development/webhooks.html) and posts a given message to a given room when this webhook is hit.

Here's some example code which should work (untested, may contain some mistakes):

```python
from errbot import BotPlugin, webhook

class ExamplePlugin(BotPlugin):
    @webhook('/message/')
    def send_message(self, payload):
        self.send(
            self.build_identifier(payload['room']),
            message=payload['message']
        )
        return "OK: Message sent"
```

Configure the webserver plugin if not configured yet (check `!plugin config Webserver`) then send JSON encoded requests to http://your.bot.hostname/message/ with a payload of `{"room": "room.yourserver.tld", "message": "Test message"}`.
