### ISSUE TITLE
Slack backend should convert @mentions and #channel names in outgoing messages

### ISSUE THREAD

**Issue by zoni** [errbotio/errbot#892]
On slack, if a plugin sends a response such as `Hi @zoni, how are you?` the @zoni part is not recognized by slack as a user handle automatically. In order to make this work we must convert @zoni into the `<U123456|zoni>` representation which is basically doing the inverse operation of what we do on incoming messages.

Although I have not verified, I believe the very same applies to channels as well.

---

See also: https://github.com/errbotio/errbot/issues/684#issuecomment-250215872

**Comment by r3m0t** [comment]
Why not just send `link_names=1` on the `chat.postMessage` API call? Also, I have found sending `<U123456>` is left unchanged by the markdown converter and looks correct on the client. It would be useful to have a property giving that text on the `SlackPerson` object.

**Comment by zoni** [comment]
> Why not just send `link_names=1` on the `chat.postMessage` API call?

Huh, I either overlooked that option entirely or it didn't exist back when I implemented the relevant portions of the Slack backend originally. :smile: 

Would you have time to try that out and seeing if it correctly links names/channels and opening a PR then? If not, I will get around to this myself somewhere over the coming couple of weeks for sure.
