### ISSUE TITLE
Using Monit with Errbot?

### ISSUE THREAD

**Issue by tspicer** [errbotio/errbot#894]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [X] Here about something else

### I am running...

* Errbot version: Latest
* OS version: Alpine 3.4
* Python version: 3.4
* Using a virtual environment: No

### Issue description

I wanted to know if anyone is using a process monitor, like Monit, to keep watch over Errbot. If you are using Monit, can you share some of the approaches and/or configs you have employed?

**Comment by zoni** [comment]
#863 (which is a work in progress) contains example configurations for supervisord and systemd which I think is related because both will restart errbot if the process crashes entirely.

I know monit can do more but I do not personally know of anyone using it. Are you trying to achieve any specific goals or just looking for general suggestions on monitoring errbot's health?

**Comment by tspicer** [comment]
Thanks for the reply and pointer. 

Errbot will run in Docker, so there are container level controls for making sure it (the container) is always running. However, the idea for using Monit was to make sure Errbot was running properly within the container. Monit would be performing operations (restarts, initialization, checks...) in the event some condition was met. For example, if the Errbot process is running, but not functioning, Monit can perform a check and restart or re-initialize everything cleanly. Monit may also check internal or external ports for "I'm alive". Monit may scan logs for exceptions and respond accordingly.  

Using Alpine Linux and I'm not familiar supervisord and/or systemd in that context, but will take a look!

**Comment by zoni** [comment]
> Errbot will run in Docker, so there are container level controls for making sure it (the container) is always running.

Gotcha. The systemd/supervisord issue I mentioned is irrelevant here then as you'd use something like docker restart policies or a higher-level container scheduler the keep the container going.

> However, the idea for using Monit was to make sure Errbot was running properly within the container. Monit would be performing operations (restarts, initialization, checks...) in the event some condition was met. For example, if the Errbot process is running, but not functioning, Monit can perform a check and restart or re-initialize everything cleanly. Monit may also check internal or external ports for "I'm alive". Monit may scan logs for exceptions and respond accordingly.

There's currently nothing within errbot's ecosystem (that I know of) for this, but it sounds like you already came up with some options. :smile:. You could even run a second bot and have it message the first (`!status` comes to mind) and check the output.

I'll leave this issue open a while longer in case anyone else comes by and has something to add which could help.

**Comment by sijis** [comment]
Here's an idea:
What if there was a custom webhook plugin that would respond to '/health' and return a 'OK' (or something). You could probably configure monit to query that webhook path and validate its response. Obviously if it doesn't respond in X time, its probably hung/dead/etc. 
http://errbot.io/en/latest/user_guide/plugin_development/webhooks.html

**Comment by tspicer** [comment]
That health check query is a good example. Monit has some built in http request checks that can assess a response (i.e. OK) and then do something if it is something other than that.

**Comment by zoni** [comment]
@tspicer did you get a satisfactory monitoring setup with monit? Do you mind if I close this issue or there anything more we can help you with?
