### ISSUE TITLE
Help writing plugins about sending message to room

### ISSUE THREAD

**Issue by hanks** [errbotio/errbot#906]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [x] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 4.3.4
* OS version: Ubuntu 1404
* Python version: 3.4
* Using a virtual environment: yes

### Issue description

Hi, I want to use webhook to send message data in the request to Hipchat room, and I have two questions:

1. How to send message to a specify room?

```
@webhook
def alert(self, request):
    """A webhook which simply returns 'Example'"""
    self.send(
        self.query_room('104136_chatbot-test@conf.hipchat.com'),
        'hello'
    )
```

I use `query_room` to get the Identifier of room, but it does not work, the error is 

```
23:52:05 INFO     Rocket.Requests           127.0.0.1 - "GET /alert/ HTTP/1.1" - 200 0
23:52:05 WARNING  errbot.backends.xmpp      Received error message: <message type="error" to="104136_3671080@chat.hipchat.com/none||proxy|pubproxy-d400.hipchat.com|5232" from="chatbot-test"><body>hello</body><error type="modify" code="400"><bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /></error></message>
```

2. How to build a Message object from str?

I want to use `send_card` to send a canned notification, and the API is like:

```
self.send_card(	 
    to=self.query_room('104136_chatbot-test@conf.hipchat.com'),
    title='Title + Body',
    body='text body to put in the card',
    thumbnail='https://raw.githubusercontent.com/errbotio/errbot/master/docs/_static/errbot.png',
    image='https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png',
    link='http://www.google.com',
    fields=(('First Key','Value1'), ('Second Key','Value2')),
    color='red',
    in_reply_to=self.build_message('hello')  # need a Message object here
)
```

Thank you for your time.

**Comment by gbin** [comment]
using `in_reply_to` is not mandatory (it is a shortcut to not have to fill up `to`).

have you tried with a simple `self.build_identifier()` hardcoded with a person then a room ?

**Comment by hanks** [comment]
@gbin  Thank you for your reply.

1. I tried `self.build_identifier()` with user id, it works fine, but with room id, it dose not work.  The error message seems to show the message format is bad for room message.

```
23:52:05 INFO     Rocket.Requests           127.0.0.1 - "GET /alert/ HTTP/1.1" - 200 0
23:52:05 WARNING  errbot.backends.xmpp      Received error message: <message type="error" to="104136_3671080@chat.hipchat.com/none||proxy|pubproxy-d400.hipchat.com|5232" from="chatbot-test"><body>hello</body><error type="modify" code="400"><bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /></error></message>
```

2.  I use `self.build_identifier()`  with `send_card()`, it works, can send the card to the room. I think I can just use `send_card` to solve my problem.

**Comment by kishorekumark** [comment]
Hi,
Im facing same issue, post msg to room doesn't work but do work with userid, is anyone overcome this issue?

**Comment by mks617** [comment]
same problem here

**Comment by zoni** [comment]
Please open a new issue with a description of the problem you're facing. Your situation may not be the same as originally reported here.
