### ISSUE TITLE
Configuration cannot be completed from a plugin.

### ISSUE THREAD

**Issue by txomon** [errbotio/errbot#909]
In order to let us help you better, please fill out the following fields as best you can:

### I am running...
* Errbot version: master
* OS version: Archlinux
* Python version: 3.5.2
* Using a virtual environment: yes

### Issue description

I am using [Cerberus](http://docs.python-cerberus.org/en/stable/) to validate the configuration, is way more powerful and flexible.

It has a feature that lets me normalize the configuration, converting values on validation. However, both plugin configuration functions on the BotPlugin class don't let a new value for the configuration be returned.

The change should be a two line patch in `errbot.plugin_manager.BotPluginManager.activate_plugin_with_version_check`, where if the function returns something, `errbot.plugin_manager.BotPluginManager.set_plugin_configuration` is called.

### Additional info

There are two use cases, the first one is when you want to correct the configuration at runtime, but still have stored the malformed/incomplete configuration. The one that this patch would support would be the one in which you want to correct the stored configuration too.

**Comment by zoni** [comment]
I'm open to changes to errbot itself to make this possible, but I wonder, can't you just as easily get the behaviour you desire by overriding your plugin's `configure` and `check_configuration` methods?

Especially by overwriting `check_configuration`, I believe you could just let `Cerberus` verify the incoming data and call `self.configure()` with the result of that if it passes validation.

**Comment by txomon** [comment]
Sure, that's what I am doing already. The only missing part really is to
change the configuration from the bot when `configure` is called.

The rest is already supported

**Comment by andrewthetechie** [comment]
#closeit

**Comment by sijis** [comment]
A solution seems to have been provided.
If that's not the case, please file a new issue and reference this one.
