### ISSUE TITLE
how to format a table to render as html in hipchat backend?

### ISSUE THREAD

**Issue by dennisobrien** [errbotio/errbot#926]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [x] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 4.3.4
* OS version: Ubuntu 14.04
* Python version: 3.5
* Using a virtual environment: yes (conda, running in Docker)
* Hipchat backend

### Issue description

I have a bot command that returns data in tabular format.  I'm using pandas as the table data structure.  My first attempt was to have the command return `df.to_html(index=False)` but this just presents raw html in the chat window.  I've tried this with `XMPP_XHTML_IM` on and off, and I get the same results.

From the documentation it seems the return values should be markdown.  So I've tried many variants of table markdown using the tabulate module, but none result in nicely formatted html tables.

Is anyone else able to output nicely formatted html tables with the Hipchat backend?

I've been able to do this with [will](https://github.com/skoczen/will) so I know the Hipchat platform can support it.

### Steps to reproduce

```
from errbot import BotPlugin, botcmd
import pandas as pd

class Example(BotPlugin):
    """
    This is a very basic plugin to try out your new installation and get you started.
    Feel free to tweak me to experiment with Errbot.
    You can find me in your init directory in the subdirectory plugins.
    """

    @botcmd  # flags a command
    def tryme(self, msg, args):  # a command callable with !tryme
        """
        Execute to check if Errbot responds to command.
        Feel free to tweak me to experiment with Errbot.
        You can find me in your init directory in the subdirectory plugins.
        """
        df = pd.DataFrame([{'a': 1.0, 'b': 1.1}, {'a': 2.2, 'b': 2.5}])
        return df.to_html(index=False)
```

Returns raw html.

### Additional info

Here's an example of how 'will' does it.
https://github.com/skoczen/will/blob/d074cb2b577264f0ab23215b3dd5cab590551abb/will/mixins/hipchat.py#L18

**Comment by zoni** [comment]
If you execute `!render test`, do you get a properly formatted table in the output?

**Comment by dennisobrien** [comment]
I get an error when I execute `!render test`:
```
Computer says nooo. See logs for details:
[Errno 2] No such file or directory: '/opt/conda/lib/python3.5/site-packages/errbot/core_plugins/test.md'
```

It looks like setup.py is not including that markdown file.
https://github.com/errbotio/errbot/blob/master/setup.py#L110

I looked at some of the other commands that include tables in the markdown so I tried `!status plugins`.  The table is not html formatted.  So maybe this is not about finding the write markdown table format, but to somehow configure the hipchat backend to support html.

**Comment by dennisobrien** [comment]
I'm picking this back up after moving on to other things.  It seems related to issues #827 and #335

These are suggesting getting the hipchat `room` object and calling `notify` directly on it.  But I don't see an obvious way to get to room object from the message in a botcmd handler.

Of course, returning markdown that gets converted to an html table would be ideal.

I'm happy to try any experiments suggested.

**Comment by andrewthetechie** [comment]
https://techcrunch.com/2018/07/26/atlassians-hipchat-and-stride-to-be-discontinued-with-slack-buying-up-the-ip/

**Comment by andrewthetechie** [comment]
#closeit

**Comment by sijis** [comment]
Based on that article, there is no need to do this as the service is being shutdown in about 5 weeks.

Atlassian is providing instructions (https://www.atlassian.com/partnerships/slack/migration) how migrate to Slack.

We do have a functional Slack backend to support those organizations migrating.
