### ISSUE TITLE
Hipchat is dropping XMPP, we need to port the backend fully to their API.

### ISSUE THREAD

**Issue by gbin** [errbotio/errbot#937]
In the past it was not possible but it now it should if they drop XMPP, reevaluate and remplace the XMPP calls to native API ones.

**Comment by robert-kisteleki** [comment]
Reference: https://confluence.atlassian.com/hipchatkb/external-nonbosh-xmpp-ports-disabled-in-hipchat-server-2-0-7-859442760.html

**Comment by barakschiller** [comment]
Any ideas what that entails?
I see a way to install a webhook to get notified on room messages but that requires the bot to have an externally visible IP address.

**Comment by Maijin** [comment]
Same question as @barakschiller ^

**Comment by lingfish** [comment]
I've just hit this too, attempting to stand a bot up.  It seems that the way forward is merely XMPP over TLS = BOSH?

**Comment by lingfish** [comment]
I'm working with Atlassian now on all this, and when cleared to do so, will post more info.

**Comment by lingfish** [comment]
Ok, so this is the situation from Atlassian:

For Data Centre/Server:

* XMPP itself is not retired, but the supported way to use it is over BOSH
* The other option is using the v2 API, including webhooks (which implies some form of web server required at the bot end)

For Stride:

* No XMPP support at all, v2 API is the only way forward

So yeah, looking ahead, the API seems the right way to go, or using something like [punjab](https://github.com/twonds/punjab) as a proxy.

Atlassian themselves seem to have a [good, basic library](https://bitbucket.org/atlassianlabs/ac-flask-hipchat/src) based on Flask, perhaps as a reference?

**Comment by lingfish** [comment]
Devs? Any thoughts here? @gbin

**Comment by andrewthetechie** [comment]
https://techcrunch.com/2018/07/26/atlassians-hipchat-and-stride-to-be-discontinued-with-slack-buying-up-the-ip/

**Comment by sijis** [comment]
Based on that article, there is no need to do this as the service is being shutdown in about 5 weeks.

Atlassian is providing instructions (https://www.atlassian.com/partnerships/slack/migration) how migrate to Slack.

We do have a functional Slack backend to support those organizations migrating.
