### ISSUE TITLE
Gitter: Errbot should ignore itself

### ISSUE THREAD

**Issue by nemaniarjun** [errbotio/errbot#942]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version:
* OS version:
* Python version: 
* Using a virtual environment: yes/no

### Issue description

Errbot should not respond to messages made by itself.
This will prevent infinite loop of messages.

### Steps to reproduce

Example: `!echo !echo !echo hi`

**Comment by nemaniarjun** [comment]
CC @Meetmangukiya

**Comment by gbin** [comment]
This is a backend bug, which one are you using ?

**Comment by nemaniarjun** [comment]
The gitter adapter.

**Comment by nemaniarjun** [comment]
I think @Meetmangukiya did message on your gitter channel.

**Comment by meetmangukiya** [comment]
gitter-backend @gbin

**Comment by zoni** [comment]
I've opened https://github.com/errbotio/err-backend-gitter/issues/12 as this is specific to the gitter backend, not errbot itself.
