### ISSUE TITLE
Support peer approval of bot commands

### ISSUE THREAD

**Issue by yangliping** [errbotio/errbot#948]
### I am...

* [ ] Reporting a bug
* [x] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### Issue description

Can Errbot support command approval feature like [hubot-approval](https://github.com/michaelansel/hubot-approval)? It's helpful in our workflow.

**Comment by zoni** [comment]
Errbot can absolutely support this, yes. We have the concept of [command filters](http://errbot.io/en/latest/user_guide/administration.html#command-filters) which can hook into the command sequence and prevent commands from being executed under certain situations.

We have an example of using these for implementing [2-factor authentication via OTP](https://github.com/errbotio/err-otp) and the access controls that come with errbot out of the box are [implemented](https://github.com/errbotio/errbot/blob/7e115b091edf383a4bd56fd9540b2759688cce15/errbot/core_plugins/acls.py) with them as well.

It is unlikely we'll develop this ourselves but I would invite you or anyone else from the community to develop such a plugin. I'll be available for help if you get stuck and need a hand here or there.

**Comment by andrewthetechie** [comment]
#closeit

**Comment by sijis** [comment]
A solution seems to have been provided.
If that's not the case, please file a new issue and reference this one.
