### ISSUE TITLE
Text backend doesn’t understand multiline input

### ISSUE THREAD

**Issue by gergelypolonkai** [errbotio/errbot#955]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [X] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 4.3.6
* OS version: Fedora 25 with stock Python
* Python version: 3.5
* Using a virtual environment: yes

### Issue description

While testing my new plugin, I wanted to enable the Webserver plugin for webhooks. I entered `!plugin config Webserver`, to which the bot responds:

    Default configuration for this plugin (you can copy and paste this directly as a command):
     !plugin config Webserver 
    {'HOST': '0.0.0.0',
     'PORT': 3141,
     'SSL': {'certificate': '',
             'enabled': False,
             'host': '0.0.0.0',
             'key': '',
             'port': 3142}}

If I enter it like this:

    !plugin config Webserver {'HOST': '0.0.0.0', 'PORT': 3141, 'SSL': {'enabled': False, 'certificate': '', 'host': '0.0.0.0', 'key': '', 'port': 3142}}

the bot replies `Plugin configuration done`, and the plugin is enabled.

As I would on my normal backend, I copied it as instructed. I got the same message again, and the Webserver plugin is still not configured.

I believe this is because the `Text` backend doesn’t understand multiline messages. It is fine, but it should be either documented, or the `!plugin config` command could be more helpful by converting it to a oneliner.

### Steps to reproduce

See Issue description.

**Comment by zoni** [comment]
This is definitely due to the text backend's line-based nature. I think the easiest way to resolve this is simply to disable pretty-printing of the example config specifically for the text backend (leaving it as-is for the others).

**Comment by iankur** [comment]
@zoni I do not get why pretty-printing should be left as it is for the rest of the backends. It seems that the parsing takes place in the same way for all the backends. So should not it be the case that pretty-printing be disabled for all of them?

**Comment by zoni** [comment]
Pretty-printing itself isn't at fault here, all the other backends can receive a chat message in full including any number of newlines and parse it as a whole, so they're unaffected. As pretty-printing produces considerably more readable output, I don't want to remove it only because it causes undesirable effects in this one very specific scenario.

**Comment by gergelypolonkai** [comment]
Just from the top of my head, a theoretical(?) IRC backend would also suffer from the same limitations.

**Comment by iankur** [comment]
I had checked for Slack backend and I faced the same issue.
![slack_backend_multiline_input_error](https://cloud.githubusercontent.com/assets/17414021/23651578/e544c9a2-034b-11e7-99b1-ae3e94669ec4.jpeg)

**Comment by gergelypolonkai** [comment]
That's strange, it worked fine for me on Slack.

**Comment by Devon-Peroutky** [comment]
Any resolution to this issue? I'm using slack and if I enter:
```
{‘HOST’: ‘0.0.0.0’,
 ‘PORT’: 3141,
 ‘SSL’: {‘certificate’: ‘’,
         ‘enabled’: False,
         ‘host’: ‘0.0.0.0’,
         ‘key’: ‘’,
         ‘port’: 3142}}```
(The default result of entering `!plugin config Webserver`), I get:
```Syntax error in the given configuration```, with a stacktrace of:
```
Traceback (most recent call last):
  File "/mnt/services/tx-bot/venv/lib/python3.5/site-packages/errbot/core_plugins/plugins.py", line 178, in plugin_config
    real_config_obj = literal_eval(' '.join(args[1:]))
  File "/usr/local/lib/python3.5/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/local/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    {‘HOST’: ‘0.0.0.0’, ‘PORT’: 3141, ‘SSL’: {‘enabled’: False, ‘certificate’: ‘’, ‘host’: ‘0.0.0.0’, ‘key’: ‘’, ‘port’: 3142}}
          ^
SyntaxError: invalid character in identifier
```

**Comment by gergelypolonkai** [comment]
I thing this is not related to this issue. If this is literally the text
you paste, it's the UTF8 apostrophes that cause the problem, not the
newline characters.

**Comment by Devon-Peroutky** [comment]
This may be a dumb question, but what do you suggest? I've tried:
```
!plugin config Webserver {‘HOST’: ‘0.0.0.0’, ‘PORT’: 3141, ‘SSL’: {‘certificate’: ‘’, ‘enabled’: False, ‘host’: ‘0.0.0.0’, ‘key’: ‘’, ‘port’: 3142}}
```
```
!plugin config Webserver {'HOST': '0.0.0.0', 'PORT': 3141, 'SSL': {'enabled': False, 'host': '0.0.0.0', 'port': 3142, 'certificate': "", 'key': ""}}
```
As well as HTML encoding the apostrophes, and had no luck with any of them

**Comment by zoni** [comment]
@Devon-Peroutky looks like the problem you're having is related to https://github.com/errbotio/errbot/issues/964#issuecomment-297440720, please see that issue.

**Comment by camposer** [comment]
I'm using Mac, and this solved a similar issue for me: `System Preferences > Keyboard > Text > Uncheck "Use smart quotes and dashes`
