### ISSUE TITLE
Restore backup

### ISSUE THREAD

**Issue by ingtarius** [errbotio/errbot#963]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [x] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: Errbot version 4.3.6
* OS version: Debian 8 in Docker
* Python version: Python 3.5.2
* Using a virtual environment: no

### Issue description

I try to restore running bot in Docker via backup/restore configs and get this error:

```
15:31:10 INFO     errbot.bootstrap          **** RESTORING the bot from /var/lib/err/backup.py
Traceback (most recent call last):
  File "/usr/local/bin/errbot", line 9, in <module>
    load_entry_point('errbot==4.3.6', 'console_scripts', 'errbot')()
  File "/usr/local/lib/python3.5/site-packages/errbot/cli.py", line 296, in main
    bootstrap(backend, root_logger, config, restore)
  File "/usr/local/lib/python3.5/site-packages/errbot/bootstrap.py", line 198, in bootstrap
    bot = setup_bot(bot_class, logger, config, restore)
  File "/usr/local/lib/python3.5/site-packages/errbot/bootstrap.py", line 143, in setup_bot
    ast.literal_eval(f.read())
  File "/usr/local/lib/python3.5/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/local/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 4
    log.info("Restoring plugin_manager")
      ^
SyntaxError: invalid syntax
`
My top of backup file (created via !backup command):
## This file is not executable on its own. use errbot -r FILE to restore your bot.

log.info("Restoring repo_manager")
log.info("Restoring plugin_manager")
bot.plugin_manager["configs"] = {'Webserver': {'SSL': {'certificate': '', 'host': '0.0.0.0', 'key': '', 'enabled': False, 'port': 3142}, 'HOST': '127.0.0.1', 'PORT': 3141}}
log.info("Installing plugins.")
if "installed_repos" in bot.repo_manager:
  for repo in bot.repo_manager["installed_repos"]:
    log.error(bot.repo_manager.install_repo(repo))
log.info("Restoring plugins data.")
bot.plugin_manager.update_dynamic_plugins()
pobj = bot.plugin_manager.get_plugin_by_name("Plugins").plugin_object
pobj.init_storage()
pobj.close_storage()
```

**Comment by ingtarius** [comment]
When i hide all log.info strings, it show me different error:
`07:04:26 INFO     errbot.bootstrap          **** RESTORING the bot from /home/errbot/config_errbot.py
Traceback (most recent call last):
  File "/usr/local/bin/errbot", line 9, in <module>
    load_entry_point('errbot==4.3.7', 'console_scripts', 'errbot')()
  File "/usr/local/lib/python3.5/site-packages/errbot/cli.py", line 296, in main
    bootstrap(backend, root_logger, config, restore)
  File "/usr/local/lib/python3.5/site-packages/errbot/bootstrap.py", line 198, in bootstrap
    bot = setup_bot(bot_class, logger, config, restore)
  File "/usr/local/lib/python3.5/site-packages/errbot/bootstrap.py", line 143, in setup_bot
    ast.literal_eval(f.read())
  File "/usr/local/lib/python3.5/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/local/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 5
    bot.plugin_manager["configs"] = {'Webserver': {'SSL': {'certificate': '', 'host': '0.0.0.0', 'key': '', 'enabled': False, 'port': 3142}, 'HOST': '127.0.0.1', 'PORT': 3141}}
                                  ^
SyntaxError: invalid syntax
`

**Comment by andrewthetechie** [comment]
#closeit

**Comment by sijis** [comment]
I'm unable to reproduce this with the latest version using the dataset provided in your comments.
```
$ errbot -r
01:06:58 INFO     errbot.bootstrap          Found Storage plugin: Shelf.
01:06:58 INFO     errbot.bootstrap          Found Backend plugin: Null
01:06:58 INFO     errbot.bootstrap          **** RESTORING the bot from /tmp/sijis/errbot/data/backup.py
01:06:58 INFO     errbot.bootstrap          Restoring repo_manager.
01:06:58 INFO     errbot.bootstrap          Restoring plugin_manager.
01:06:58 INFO     errbot.bootstrap          Installing plugins.
01:06:58 INFO     errbot.bootstrap          Restoring plugins data.
01:06:58 INFO     errbot                    webhooks:  Flag to bind /echo to echo
01:06:58 INFO     errbot                    webhooks:  Flag to bind /testWeb to testWeb
Restore complete. You can restart the bot normally
```
