### ISSUE TITLE
& escaping (Plugin Config/Slack)

### ISSUE THREAD

**Issue by rcoup** [errbotio/errbot#964]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [X] Reporting a bug

### I am running...

* Errbot version: >4.3.7 (c95300a)
* OS version: Debian Jessie
* Python version: 3.6
* Using a virtual environment: no (Docker)

### Issue description

`&` in a message seem to end up in Errbot as `&amp;`, via Slack at least.

### Steps to reproduce

```
!plugin config SomePlugin {'SUBDOMAIN': 'example','EMAIL': 'me@example.com','PASSWORD': '!bv9#dfW6D&'}
``` 
(note `&` in the password)

In the log:

```
16:27:40 INFO     errbot.core               Processing command 'plugin_config' with parameters 'SomePlugin {'SUBDOMAIN': 'example','EMAIL': 'me@example.com','PASSWORD': ''!bv9#dfW6D&amp;'}' from @rcoup
```

Querying back via Slack:
```
!plugin config SomePlugin
{'EMAIL': '', 'PASSWORD': '', 'SUBDOMAIN': 'example'}

Current configuration:
!plugin config SomePlugin
{'EMAIL': 'me@example.com',
'PASSWORD': '!bv9#dfW6D&',
'SUBDOMAIN': 'example'}
```

Querying back via the Text backend:

```
 >>> !plugin config SomePlugin
Default configuration for this plugin (you can copy and paste this directly as a command):
 !plugin config SomePlugin
{'EMAIL': '', 'PASSWORD': '', 'SUBDOMAIN': 'example'}

 Current configuration:
 !plugin config SomePlugin
{'EMAIL': 'me@example.com',
 'PASSWORD':  '!bv9#dfW6D&amp;',
 'SUBDOMAIN': 'example'}
```

Needless to say the password doesn't work so well with an extra `amp;` in it 😉 

If the config is set via the Text backend then it works fine. Afterwards `!plugin config SomePlugin` returns the message with the `&` ok in Slack.

### Additional info

Python-slackclient is v1.0.5

**Comment by rcoup** [comment]
Semi-related, Slack's more aggressively doing smart quoting now (under OSX at least), so 

```
!plugin config Foo {'OPTION': 'value'}
```
becomes:
```
!plugin config Foo {‘OPTION’: ‘value’}
```

And then the botcmd chokes on it. And you can't prefix with ` or ``` to put it in code-block mode (so slack doesn't smart-quote), since then the botcmd isn't recognised.

One simple idea is to blindly replace any of the 4x smart-quotes (`‘‘ “”`) with regular quotes before passing to `ast.literal_eval()`?

**Comment by zoni** [comment]
Telegram does something similar, it replaces `--` with a fancy hyphen which wreaks havoc when you try to use `@arg_botcmd`-type commands. So those get [changed back](https://github.com/errbotio/errbot/blob/9dfec926f22034864b647bcdab24a519db110d7a/errbot/__init__.py#L343) into `--` already.

Though that's a somewhat more specific, narrow-scoped replacement than would be required here. I'm definitely open to replacing these stylized versions back to their plain representation, but we'll need to think of how to do this in the least-invasive way possible.

**Comment by rcoup** [comment]
@zoni any ideas on this? I presume _no-one_ can do chat-based plugin config in Slack atm?

**Comment by iamkirkbater** [comment]
A year late to the party, but I found a _somewhat_ similar bug.  If you add a trailing single quote `'` to a command, errors don't properly display.

For example, I accidentally hit the quote before I hit enter, on a command and was greeted by:

> Command "mycommand'" not found.
Did you mean "{self.bot_config.BOT_PREFIX}{alternatives}" ?

Also, in regards to @rcoup's comment:
> One simple idea is to blindly replace any of the 4x smart-quotes (‘‘ “”) with regular quotes before passing to ast.literal_eval()?

I used to have to do this when I worked at a university and the professors would blindly copy-paste from Microsoft, and I never saw any pitfalls in the 4 years I worked there.  YMMV, though.

**Comment by dizzi90** [comment]
It should be noted that the smart quoting is sometimes OS-level, rather than Slack itself (if not always). I had problems configuring from a Mac, but going into Settings->Keyboard->Text and turning off smart quoting there worked. Just making a note of it here in case someone else is having the same problem.

**Comment by sijis** [comment]
Quoting the plugin with quotes, has typically worked.

If this persist, create a new issue using latest version of errbot.

Thanks.
