### ISSUE TITLE
Get rid of threadpool

### ISSUE THREAD

**Issue by murinicanor** [errbotio/errbot#965]
### I am...
* [ ] Suggesting a new feature

### I am running...

* Errbot version: 4.3.7
* OS version: any
* Python version: any
* Using a virtual environment: yes

### Issue description

The [description of the threadpool package](https://pypi.python.org/pypi/threadpool) says: 

> This module is OBSOLETE and is only provided on PyPI to support old projects that still use it. Please DO NOT USE IT FOR NEW PROJECTS! Use modern alternatives like the multiprocessing module in the standard library or even an asynchroneous approach with asyncio.

As far as i can see, the module is only used in two places in the errbot code:
- in errbot/flow.py in the FlowExecutor class
- in errbot/core.py in ErrBot's _process_command function

maybe it would be possible, to switch to [multiprocessing](https://docs.python.org/3.5/library/multiprocessing.html) instead? this would remove one dependency

**Comment by zoni** [comment]
This has been on my to-do list for quite a while now, so I'm definitively supportive of this. I just haven't gotten around to it myself yet.

If you feel adventurous, please feel free to dive into the code and open a PR to swap it out. I'll be happy to give some pointers if you get stuck along the way.

**Comment by intrigeri** [comment]
Can this issue be closed, now that #968 was merged?

**Comment by gbin** [comment]
Indeed Thanks
