### ISSUE TITLE
XMPP backend: Unable to reply to Openfire MUC messages

### ISSUE THREAD

**Issue by ekloster** [errbotio/errbot#970]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

 [*] Reporting a bug

### I am running...

* Errbot version:  4.3.7
* OS version: OS X El Capitan (10.11.6)
* Python version:  3.5.2
* Using a virtual environment: no

### Issue description

When using the XMPP backend to connect to an Openfire server, errbot is unable to reply to messages in a multi-user chatroom (MUC).  Each message to errbot is properly processed, but on reply to the room errbot receives an error code 400:

...<error code="400" type="modify"><bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /></error></message>

### Steps to reproduce

Connect errbot to Openfire MUC
Issue commands within the MUC to errbot

### Additional info

It looks like this is caused by errbot attempting to send MUC responses to room@chatserver.tld/username instead of just room@chatserver.tld.  I've fixed this issue by modifying errbot/backends/xmpp.py though I'm not sure the patch is effective.  If it is, or you have suggestions for where best to fix this, I'd be happy to submit a pull request for it:

Current xmpp.py send_message:

    def send_message(self, mess):
        super().send_message(mess)

        log.debug("send_message to %s", mess.to)

        # We need to unescape the unicode characters (not the markup incompatible ones)
        mhtml = xhtmlim.unescape(self.md_xhtml.convert(mess.body)) if self.xhtmlim else None

        self.conn.client.send_message(mto=str(mess.to),
                                      mbody=self.md_text.convert(mess.body),
                                      mhtml=mhtml,
                                      mtype='chat' if mess.is_direct else 'groupchat')

Patched xmpp.py send_message:

    def send_message(self, mess):
        super().send_message(mess)

        log.debug("send_message to %s", mess.to)

        # We need to unescape the unicode characters (not the markup incompatible ones)
        mhtml = xhtmlim.unescape(self.md_xhtml.convert(mess.body)) if self.xhtmlim else None

        if mess.is_direct:
            self.conn.client.send_message(mto=str(mess.to),
                                          mbody=self.md_text.convert(mess.body),
                                          mhtml=mhtml,
                                          mtype='chat')
        else:
            room_rcpt = str(mess.to).split('/')[0]
            self.conn.client.send_message(mto=room_rcpt,
                                          mbody=self.md_text.convert(mess.body),
                                          mhtml=mhtml,
                                          mtype='groupchat')

**Comment by sijis** [comment]
This section of code has completely changed.
If this issue persist please file a new bug.
