### ISSUE TITLE
Support inline buttons on Telegram and Slack

### ISSUE THREAD

**Issue by rlafuente** [errbotio/errbot#976]
This is a specification of sorts for a new feature -- support for [inline buttons](https://core.telegram.org/file/811140659/1/RRJyulbtLBY/ea6163411c7eb4f4dc) on backends that provide those. Right now, only Telegram and Slack allow for this.

(I'm only working on Telegram, so all relevant examples will be closer to Telegram's way of handling these.)

After some discussion on Gitter, this feature requires some thought about how to abstract things; one useful case is to have these inline buttons tightly connected with bot flows. The necessary components would be:

* Add a `send_question` method to the Errbot class, and override it on the relevant backends
* Extend message handling to recognize and take care of callbacks (which we receive when an inline button is pressed)
* Integrate the question and the button callbacks into Errbot's flow logic

The desired usage scenario would then be:

```python
flow.connect('colors', Choice(
        question='What is your favorite color?', 
        options=('blue', 'red', 'green'), 
        ctx_key='my_color')
)

@botcmd
def colors(self, msg, args):
    return 'Your color choice is %s' % msg.ctx['my_color']
```

I'm working on implementing this, so any comments or corrections would be most welcome.

**Comment by rlafuente** [comment]
I found a dilemma when trying to augment FlowNode.

Having "choice" as an optional argument is simple, but how should the node behave when it is specified? From what I see there is no messaging logic on the flow code, so I'm not sure what's the best way to have this node ask the question to the user.

Handling the answer is another issue: the answer is provided through a callback (e.g. when clicking an answer, Telegram sends an object called CallbackQuery specifying the question ID and the selected answer). How should the predicate be specified in order to "watch" for this callback and move on with the flow when it gets it?

**Comment by sheluchin** [comment]
Has been discussed here: https://github.com/errbotio/errbot/issues/794

**Comment by zoni** [comment]
> I found a dilemma when trying to augment FlowNode.

@gbin implemented all the Flow code. He might be able to weigh in here or on [Gitter](https://gitter.im/errbotio/errbot).

**Comment by rlafuente** [comment]
Thank you for the useful references @sheluchin and @zoni! I have been discussing the details with gbin over Gitter.

Right now I'm working on a fork to implement a rough working example using Telegram. From there we'll be able to discuss how to deal with unsupported backends and other required details for eventually merging back into Errbot. Thanks again for your support on this!

**Comment by sheluchin** [comment]
Slack has also added drop-down menus to messages. I'm not entirely sure if it's relevant within the scope of buttons, but thought I'd leave the reference here anyway.
> In a Slack message, apps can unfurl charts and images, surface important data, and include buttons you can use to complete a task in one click. And now, we’re introducing message menus — clickable drop-down menus that bring more intricate and nuanced workflows to the apps you use in Slack.

https://slackhq.com/take-your-pick-75767e13b497

**Comment by rlafuente** [comment]
In the end I underestimated the complexity of this task, and ended up coding something else from scratch. I think I'm unable to help implementing this feature into Errbot. 

Hope this feature comes up at a certain point, in the meantime thanks all for the help.
