### ISSUE TITLE
No notice callback for irc backend

### ISSUE THREAD

**Issue by rattboi** [errbotio/errbot#978]
### I am...

* [x] Suggesting a new feature

### I am running...

* Errbot version: 4.3.7
* OS version: Ubuntu 16.04
* Python version: 3.5.2
* Using a virtual environment: yes

### Issue description

It appears there's nothing to attach to to see pubnotice events from the irc backend, which is affecting me because I'm trying to write an IRC channel logger plugin. Based on on_pubmsg, on_join, on_part, etc, I can log most events, but skipping notices is a big deal because we use our channel for development, and the github notifications come in as notices.

**Comment by gbin** [comment]
Can you check if it works for you with #984 ?

They will be forwarded as normal messages but with an entry 'notice' True/False in the extra field.
