### ISSUE TITLE
Hipchat backend cannot render tables (or other formatting) correctly

### ISSUE THREAD

**Issue by aliciasteen** [errbotio/errbot#982]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [x] Here about something else

### I am running...

* Errbot version: 4.3.7
* OS version: ubuntu
* Python version: 3
* Using a virtual environment: no

### Issue description

Please describe your bug/feature/problem here.
The more information you can provide, the better.

Tables do not render correctly on hipchat. I can run render test and it shows the formatting is not working.

### Steps to reproduce

In case of a bug, please describe the steps we need to take in order to reproduce your issue.
If you cannot easily reproduce the issue please let us know and provide as much information as you can which might help us pinpoint the problem.

### Additional info

If you have any more information, please specify it here.

Output of render test:

Normal Markdown:
image: http://errbot.io/_static/errbot.png
 link: This is a link (http://www.errbot.io).
 bold
 italic
 This is a list:
• element one
• element two
• element three
 This is a ruler:
────────────────────────────────────────────────────────────────────────────────
THIS IS AN H1

 Paragraph in h1

  This is an H2

 Paragraph in h2

    This is an H3

 Paragraph in h3

      This is an H4
 Paragraph in h4

      This is an H5
 Paragraph in h5

      This is an H6
 Paragraph in h6
 Markdown extra (colors):
Red paragraph
 Inline blue text
Inline green text
 Inline emphasis blue text
 Inline yellow on cyan
 Markdown extra (table):
┏━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┓
┃ First Header   ┃ Second Header      ┃
┡━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━┩
│ Content Cell   │ bold               │
├────────────────┼────────────────────┤
│ Normal Content │ Normal content too │
├────────────────┼────────────────────┤
│ Normal Content │ Normal content too │
├────────────────┼────────────────────┤
│ Normal Content │ Normal content too │
├────────────────┼────────────────────┤
│ Content Cell   │ italic             │
└────────────────┴────────────────────┘
 Markdown extra (table multiline):
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ First Header ┃ Second Header ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ Content Cell │ l1            │
│              │ l2            │
├──────────────┼───────────────┤
│ l3           │ l4            │
│ l5           │               │
└──────────────┴───────────────┘
 Special characters:
Copyright: ©
Natural amp: &
Less : <
 Markdown extra (code) with brackets:
 {
"employees":[
    {"firstName":"John", "lastName":"Doe"}, 
    {"firstName":"Anna", "lastName":"Smith"}, 
    {"firstName":"Peter","lastName":"Jones"}
]
}

**Comment by gbin** [comment]
Is it possible to render tables in Hipchat ?

cf https://answers.atlassian.com/questions/38049519/formatting-lists-and-tables-in-hipchat

**Comment by andrewthetechie** [comment]
https://www.theverge.com/2018/7/26/17619482/slack-hipchat-acquisition-stride-atlassian-partnership-microsoft-teams-competition

Hipchat is going away here very soon.

#closeit

**Comment by sijis** [comment]
Based on that article, there is no need to do this as the service is being shutdown in about 5 weeks.

Atlassian is providing instructions (https://www.atlassian.com/partnerships/slack/migration) how migrate to Slack.

We do have a functional Slack backend to support those organizations migrating.
