### ISSUE TITLE
PySide not Working with Python 3.5

### ISSUE THREAD

**Issue by gyleodhis** [errbotio/errbot#986]
In order to let us help you better, please fill out the following fields as best you can:

### I am...
![screenshot from 2017-04-04 23-56-31](https://cloud.githubusercontent.com/assets/19478013/24678316/b804d632-1992-11e7-938f-da35a8034064.png)

* [ ] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 9.9.9
* OS version: Ubuntu 16
* Python version: 3.5
* Using a virtual environment: yes/no : No

### Issue description

Helloo PySide is not working with Python 3.5 so I cannot run "Graphic" backend kindly help

**Comment by zoni** [comment]
PySide [doesn't support Python 3.5](https://github.com/pyside/PySide/issues/132) at the moment and it's not entirely likely it ever will.

Going through the issue linked above, it seems PySide 1.x is deprecated in favor of [PySide 2](http://wiki.qt.io/PySide2). In the long term, errbot should switch over to use PySide 2 instead I'd say. This would require changes to the graphical backend.

**Comment by gbin** [comment]
@zoni: usually downloading pyside from source and changing the python version restriction in setup.py works for me with Errbot (we probably don't use anything fancy anyway). I gonna look at pyside 2.

**Comment by sijis** [comment]
We remove the GUI backend in https://github.com/errbotio/errbot/pull/1495 as it was not maintained.
