### ISSUE TITLE
endpoint not working in hipchat BOT_IDENTITY

### ISSUE THREAD

**Issue by hardymansen** [errbotio/errbot#988]
'endpoint' : 'https://myserver',

Im setting this in config.py but it still takes the value from 'username' : 1_111@chat.btf.hipchat.com and tries to connect to chat.btf.hipchat.com

Errbot version 4.3.7

**Comment by zoni** [comment]
Do you have `BACKEND = 'Hipchat'` set in your `config.py` as well?

**Comment by hardymansen** [comment]
Yes, 
BACKEND = 'Hipchat'

Sorry i have moved on to hubot and got it working so will not look into this anymore. If it is just me that have the issue you can close this one. Thank you very much.

**Comment by zoni** [comment]
That's okay. Good luck with Hubot!
