### ISSUE TITLE
Enable a hook on unknown_command

### ISSUE THREAD

**Issue by qlixed** [errbotio/errbot#994]
### I am...

* [ ] Reporting a bug
* [x] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 4.3.7
* OS version: Fedora 25
* Python version: 3.5
* Using a virtual environment: yes

### Issue description
I would like to have an option to replace, by a hook system, the unknown_command feature, this will enable a command to handle the unknown command situation.
**Rationale**: Check Additional Info.
The idea is to let one or more command to hook in the unknown_command to handle it in the desired way, keeping the current default behavior as a last step:
The basic idea is to:
- Get into the unknown_command.
- Dispatch the signal to the registered commands.
- The command do their magic as needed.
- Each register command can respond with 2 options:
  - A tuple or dict with:
    - A "message" string, that "adds" to the final response of the unknown_command response.
    - A "mask" boolean, that indicate if the default message of the default behavior get masked or not.
  - A None witch means that the default behavior will be done.
Additional explanation in Additional Info.

### Steps to reproduce
- None

#### Rationale:
- Statistics: Let me know how many times the unknown command happens.
- Abuse Control: Detect people that coming to "play" with us.
- Default behavior change: Modify the current friendly behavior for a custom one.

#### Additional explanation:
- With one plugin registered only is straightforward how it works.
- With two or more plugins the things became a little more complex, so:
  1. All the commands make a response in the way it needs to do it, the base unknown_command handler receive all the outputs, making a list of each command response.
  2. Check each command response and if anyone "masks" the default output, the output get masked.
  3. Also there is a couple of things to account:
      - There is no ensured order of execution, so each registered command can't rely on this.
      - The command can't rely on the default behavior as it can be masked by another command.

I might start to work on some on this, but **i want to first come with some discussion about the implementation, so, shoot your ideas!.**

**Comment by sijis** [comment]
I think this is best solved with `CommandNotFoundFilter`, see https://errbot.readthedocs.io/en/latest/user_guide/administration.html#overriding-commandnotfoundfilter.
