### ISSUE TITLE
 ModuleNotFoundError: No module named 'monolithic'

### ISSUE THREAD

**Issue by viniciusd** [errbotio/errbot#998]
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [X] Reporting a bug
* [ ] Suggesting a new feature
* [ ] Requesting help with running my bot
* [ ] Requesting help writing plugins
* [ ] Here about something else

### I am running...

* Errbot version: 5.0.0
* OS version: Debian 8.7
* Python version: 3.5, 3.6
* Using a virtual environment: yes

### Issue description

When installing errbot prior to some specific packages, those packages cannot be pip installed anymore, they throw a ModuleNotFoundError while installing.
That's a blocking problem if we are expanding an existing bot.

### Steps to reproduce
It will fail if you:
```bash
cd /tmp
mkdir foo
python3.6 -m venv foo
cd foo && source bin/activate
pip install errbot python-novaclient
```

Same behavior installing Openstack's python-jenkins. It does not happen installing other packages, though, e.g., fabric3 and sanic.

If installing in the reverse order (errbot after), it works:
```bash
cd /tmp
mkdir bar
python3.6 -m venv bar
cd bar && source bin/activate 
pip install python-novaclient errbot
```

**Comment by viniciusd** [comment]
For now, my only finding:
Running `grep -r monolithic` in both foo and bar finds:
`foo/lib/python3.5/site-packages/rocket_errbot-1.2.5-py3.5.egg-info/entry_points.txt:build_monolithic = monolithic:build_monolithic`
only.

**Comment by zoni** [comment]
I suspect openstack's packaging helper thing somehow chokes on the `monolithic` module and related distutils helpers found in rocket. We don't use it, so I wouldn't object to ripping out all references to it from [our rocket fork](https://github.com/errbotio/rocket).

If you'd be willing to prepare an adequate pull request on that repo and try some tests, I'd be happy to merge and push an updated package to PyPI for it.

**Comment by jmreicha** [comment]
Seeing this as well when doing a `pip install python-jenkins`.

**Comment by sijis** [comment]
This should no longer apply as we switched away from rocket to flask.
See https://github.com/errbotio/errbot/pull/1214.
